### ISSUE TITLE
DNSPOD国际版(dnspod.com)

### ISSUE THREAD

**Issue by lirener** [NewFuture/DDNS#10]
如题dnspod国际版好像没有API-token的相关操作说明呀？
还有如果支持的话要怎么操作呀？

**Comment by NewFuture** [comment]
国际版(DNSPOD.com)的文档 https://www.dnspod.com/docs/index.html

Token获取方式 https://www.dnspod.com/docs/info.html#get-the-user-token
>`curl -X POST https://api.dnspod.com/Auth -d 'login_email=api@dnspod.com&login_password=password&format=json'`

国际版的没有测试过，你可以试试 

如果API的有问题可以把https://github.com/NewFuture/DDNS/blob/master/dns/dnspod.py#L26 换成 `api.dnspod.com`试试

**Comment by lirener** [comment]
谢谢 我刚刚看过帮助文档了 也试过去获取"user_token"但是没获取到……
提示密码错误 因为我密码开头是@符号
<code>10004</code>
<message><![CDATA[Password invalid, must within 6-32 chars]]></message>
不知道如何解决……获取不到token

把API_SITE = "dnsapi.cn"换成API_SITE = "api.dnspod.com"对不 这个勉强看懂了

**Comment by lirener** [comment]
好吧我解决了……不用cmd换成msys2就解决了 是编码问题……获取到了

**Comment by NewFuture** [comment]
应该是Windows 的命令行没有识别单引号`'`

**Comment by lirener** [comment]
确实啊把单引号'换成"双引号cmd也可以了

**Comment by lirener** [comment]
```
========================= Sat Nov  4 21:04:53 2017 =========================
update ipv4 to: 10.10.10.1
Traceback (most recent call last):
  File "E:\caddy\DDNS-2.1.1\run.py", line 91, in <module>
    main()
  File "E:\caddy\DDNS-2.1.1\run.py", line 86, in main
    update_ip('4', cache, dns)
  File "E:\caddy\DDNS-2.1.1\run.py", line 60, in update_ip
    print (dns.update_record(domain, value, record_type=record_type))
  File "E:\caddy\DDNS-2.1.1\dns\dnspod.py", line 147, in update_record
    domainid, sub = get_domain_info(domain)
  File "E:\caddy\DDNS-2.1.1\dns\dnspod.py", line 74, in get_domain_info
    did = get_domain_id(main)
  File "E:\caddy\DDNS-2.1.1\dns\dnspod.py", line 103, in get_domain_id
    info = request('Domain.Info', domain=domain)
  File "E:\caddy\DDNS-2.1.1\dns\dnspod.py", line 64, in request
    raise Exception(data.get('status', {}))
Exception: {'created_at': '2017-11-04 13:04:58', 'code': '10002', 'message': 'Missing user token, login failed'}
```
看啦好久不会改……
https://www.dnspod.cn/docs/accounts.html
https://www.dnspod.com/docs/accounts.html

> curl -X POST https://dnsapi.cn/User.Detail -d 'login_token=LOGIN_TOKEN&format=json'

> curl -X POST https://api.dnspod.com/User.Detail -d 'user_token=730060,e1a8a$f14dc5dcbafd83680b3d2a553c4d553d&format=json'
好像登录的API参数也有点不一样 我改了1个提示成2 代码没跑完……不会整了

**Comment by NewFuture** [comment]
更新了，下载最新的代码,dns提供商选择 `dnspod_com`
示例
```
    "id": "730060",
    "token": "e1a8a$f14dc5dcbafd83680b3d2a553c4d553d",
    "dns": "dnspod_com",   
```

**Comment by lirener** [comment]
```
Traceback (most recent call last):
  File "E:\caddy\DDNS-2.1.2\run.py", line 91, in <module>
    main()
  File "E:\caddy\DDNS-2.1.2\run.py", line 74, in main
    dns = getattr(__import__('dns', fromlist=[dns_provider]), dns_provider)
  File "E:\caddy\DDNS-2.1.2\dns\dnspod_com.py", line 7
    """
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xbd in position 0: invalid start byte
```
报了个错……

**Comment by lirener** [comment]
```
========================= Sat Nov  4 23:42:18 2017 =========================
update ipv4 to: 10.10.10.1
Traceback (most recent call last):
  File "E:\caddy\DDNS-2.1.2\run.py", line 91, in <module>
    main()
  File "E:\caddy\DDNS-2.1.2\run.py", line 86, in main
    update_ip('4', cache, dns)
  File "E:\caddy\DDNS-2.1.2\run.py", line 60, in update_ip
    print (dns.update_record(domain, value, record_type=record_type))
  File "E:\caddy\DDNS-2.1.2\dns\dnspod_com.py", line 157, in update_record
    "utf-8"), value=value, sub_domain=sub, domain_id=domainid, record_type=record_type)
  File "E:\caddy\DDNS-2.1.2\dns\dnspod_com.py", line 64, in request
    raise Exception(data.get('status', {}))
Exception: {'message': 'Record line invalid', 'created_at': '2017-11-04 15:42:32', 'code': '26'}
```

**Comment by lirener** [comment]
我晕 调试吐血了……
record_line=Default中的
Default必须用小写default
搞定了……

**Comment by NewFuture** [comment]
好的,我改一下，辛苦~

**Comment by NewFuture** [comment]
@lirener 更新了,再试试

**Comment by lirener** [comment]
@NewFuture 好像还是不行呢……但是我改好啦 非常感谢！
156L的
record_line=record["line"].encode("utf-8")替换成record_line= 'default'
![1111](https://user-images.githubusercontent.com/19354130/32419522-2b3bac26-c2b6-11e7-80a5-e7edbce8a4bf.png)
![222222](https://user-images.githubusercontent.com/19354130/32419523-2e264b8a-c2b6-11e7-9044-dd8b2cea587b.png)

![333333](https://user-images.githubusercontent.com/19354130/32419556-c22e52d2-c2b6-11e7-811f-51765ac4ca47.png)
![4444444](https://user-images.githubusercontent.com/19354130/32419559-c6beb5b2-c2b6-11e7-8adc-490ed2411ae1.png)

**Comment by NewFuture** [comment]
应该是字符串编码问题,
```
record_line=record["line"].encode("utf-8")
```
改成
```
record_line=record["line"].replace("Default","default").encode("utf-8")
```
这句是对于已经存在的记录保持原来的线路设置

文档上返回的好像是`Default` ,我这测试不了,麻烦修改成这样测试一下

**Comment by lirener** [comment]
可以啦~

**Comment by NewFuture** [comment]
好的代码更新了,可以再试试
