### ISSUE TITLE
大佬，cloudflare支持设置TTL吗？

### ISSUE THREAD

**Issue by PHCSJC** [NewFuture/DDNS#100]
本来手动改成2min的，但总是被改回auto，可能是更新IP的原因，所以请问下在更新时能否设置TTL呢？谢谢！

**Comment by NewFuture** [comment]
#13 可以在这个地方 comment

**Comment by NewFuture** [comment]
https://github.com/NewFuture/DDNS/tree/feat-ttl
这个分支已经加入ttl设置的feat 可以试试(顺便测试一下)
