### ISSUE TITLE
建议增加新特性：检测IP变动后，支持触发回调 可以是一个API或者执行某个脚本

### ISSUE THREAD

**Issue by icekingcy** [NewFuture/DDNS#103]
建议增加新特性：检测IP变动后，支持触发回调 可以是一个API或者执行某个脚本

**Comment by NewFuture** [comment]
#163

**Comment by NewFuture** [comment]
http 版本 @laozhoubuluo 已经实现并合并到master了

* `dns`: `callback`

此时 使用自定义的http请求
* `id` 参数传入 url 
* `token` 参数传入body,token为空使用GET否正使用POST

这两个参数的字符串`__DOMAIN__`和`__IP__`分别替换成对应的IP地址和域名

比如 POST到一个自定义的API
```json
{
"dns":"callback",
"id":"http://ip.update.me",
"token":"{\"customParam\":\"__DOMAIN__\",\"ip\":\"__IP__\"}",
}
```
或者 GET请求
```json
{
"dns":"callback",
"id":"https://sc.ftqq.com/?parm=____DOMAIN__&ip=__IP__"
}
```
