### ISSUE TITLE
<urlopen error [Errno -5] No address associated with hostname>

### ISSUE THREAD

**Issue by Daopr** [NewFuture/DDNS#11]
大佬，你看下我用来更新 dnspod，更新成功了，但是更新后就出现<urlopen error [Errno -5] No address associated with hostname>，然后ddns 的进程就挂了，是什么原因呢

**Comment by NewFuture** [comment]
这个看起来是系统的网络错误，可以看看你的配置。

**Comment by Daopr** [comment]
我在树莓派上跑的，配置也很简单

{
        "id": "11111",
        "token": "xxxxxxxxxxxxxxxxxxxx",
        "dns": "dnspod",
        "ipv4": [
                "xxx.com"
        ],
        "ipv6": [
                "xxx.com"
        ],
        "index4": "public",
        "index6": "public",
        "proxy": null,
        "debug": true
}

**Comment by Daopr** [comment]
应该是没有 ipv6地址，我把 ipv6删了就没报这个错了

**Comment by Daopr** [comment]
感谢大佬写这套脚本， 现在更新 dns很方便了

**Comment by NewFuture** [comment]
已解决
