### ISSUE TITLE
通过pip安装后如何定时执行？

### ISSUE THREAD

**Issue by cachenow** [NewFuture/DDNS#112]
执行create-task脚本后所生成的cron配置执行提示not found

**Comment by NewFuture** [comment]
linux下面可以改一下这个脚本
https://github.com/NewFuture/DDNS/blob/master/task.sh

配置文件路径在修改一下，运行一遍
```bash
CMD="\"ddns\" -c \"/your/path/config.json\" >> \"/tmp/ddns.log\""

echo "*/5 * * * *   root    $CMD" > /etc/cron.d/ddns;
/etc/init.d/cron reload;
```

**Comment by Dep0s1t** [comment]
> linux下面可以改一下这个脚本 https://github.com/NewFuture/DDNS/blob/master/task.sh
> 
> 配置文件路径在修改一下，运行一遍
> 
> ```shell
> CMD="\"ddns\" -c \"/your/path/config.json\" >> \"/tmp/ddns.log\""
> 
> echo "*/5 * * * *   root    $CMD" > /etc/cron.d/ddns;
> /etc/init.d/cron reload;
> ```

`
task.sh: line 2: $'\r': command not found
task.sh: line 3: $'\r': command not found
`

大佬知道这是为什么吗，ubuntu20.04

**Comment by NewFuture** [comment]
@Dep0s1t  换行，文件编码问题？
