### ISSUE TITLE
哥们，顺便搞个多服务器网站宕机域名自动切换IP呗。

### ISSUE THREAD

**Issue by dylanbai8** [NewFuture/DDNS#114]
哥们，顺便搞个多服务器网站宕机域名自动切换IP呗。

**Comment by NewFuture** [comment]
这个最简实现两个功能
1. 监测服务器存活情况，确认可用IP，
2. IP发生变化更新 DNS

DDNS 其实实现的是第二部分，第一部分暂不在整个项目的计划范围内
第一部分有两种
* 本地方案: 可以写一个本地脚本或者命令假设叫 getserverip.py 输出可用的首选服务器IPv4地址, 然后把`index4`设置为 `cmd:python getserverip.py`
* server端方案: 提供一个api获取可用服务器ip如 `https://getmyserver.ip`,返回首选服务器IPv4地址;把`index4`设置为 `url:https://getmyserver.ip`

针对这个场景，很多DNS服务商其实上提供了更好的方案，
比如DNSPod其实有: 多线路+短TTL+monitor的方案,在不同节点监测服务器情况，自动切换线路

**Comment by dylanbai8** [comment]
感谢。其实我目前也用不到这个，就是一时突发奇想。感觉这个功能非常适合附加到你这个项目，顺手就实现了。既然暂时没有开发计划，那就算了吧。再次感谢
