### ISSUE TITLE
Cloudflare怎么控制Proxy status？

### ISSUE THREAD

**Issue by cachenow** [NewFuture/DDNS#115]
想直接更新完IP后，自动加上CDN，参数怎么设置？

**Comment by NewFuture** [comment]
这个场景是什么？

**Comment by daiaji** [comment]
@NewFuture 很简单 因为Cloudflare本身就不是一个DNS解析服务提供商……他是CDN服务提供商……
用它家的DNS多半也会用他家的CDN吧，按LZ的说法，这个脚本更新IP之后会把原先的Proxy ON给Proxy off掉？

**Comment by NewFuture** [comment]
> @NewFuture 很简单 因为Cloudflare本身就不是一个DNS解析服务提供商……他是CDN服务提供商……
> 用它家的DNS多半是因为他家的CDN香吧，按LZ的说法，这个脚本更新IP之后会把原先的Proxy ON给Proxy off掉？
> 如果不会改变Proxy status那倒还好……

所以这个问题实际上是希望，更新IP的时候保留原有设置？(这样更新确实是最佳的)

**Comment by cachenow** [comment]
> > @NewFuture 很简单 因为Cloudflare本身就不是一个DNS解析服务提供商……他是CDN服务提供商……
> > 用它家的DNS多半是因为他家的CDN香吧，按LZ的说法，这个脚本更新IP之后会把原先的Proxy ON给Proxy off掉？
> > 如果不会改变Proxy status那倒还好……
> 
> 所以这个问题实际上是希望，更新IP的时候保留原有设置？(这样更新确实是最佳的)

可以这样理解，但最好是能在配置文件参数上直接实现对proxy status的控制，这样一次性在本地解决了。

**Comment by NewFuture** [comment]
master已更新

**Comment by oneg1** [comment]
> master已更新

请问怎么控制启用Cloudflare CDN, 是手动在CF那启用，还是配置文件设置？

**Comment by NewFuture** [comment]
> 请问怎么控制启用Cloudflare CDN, 是手动在CF那启用，还是配置文件设置？

CF 上设置，更新的时候会保留原来的配置
