### ISSUE TITLE
我有个需求想加入,不知道能不能帮我一下?

### ISSUE THREAD

**Issue by Daopr** [NewFuture/DDNS#12]
我想要在每次我的ip 更新的时候 执行一个 ssh 命令
类似这样
ssh -p 222 root@myserver ''service nginx restart"
@NewFuture, 不知道能不能加入这个啊,
或者能不能指点一下我在哪里加入啊,
起因是这样,
1.我用 vps 搭建的 nginx 反向代理给本地搞了个80出口
2.我是用的域名来代理的
3.每次本地 ip 更新后,nginx 并未更新,所以无法正确代理
4.需要每次 ip 更新后,重启 nginx.
:)

**Comment by NewFuture** [comment]
改一下nginx配置(nginx默认对域名只解析一次)
```
server {
...
resolver 119.29.29.29 valid=5s; 
set $upstream "http://your.domain:8888";
proxy_pass $upstream;
}
```

**Comment by Daopr** [comment]
@NewFuture 感谢感谢") ! 省了好多时间.这招很奇妙

**Comment by lryong** [comment]
通过这种方式， 访问域名（不加端口）， 可以把流量都重定向到我的服务上吗
