### ISSUE TITLE
Cloudflare，更新失败！！！

### ISSUE THREAD

**Issue by snakwu** [NewFuture/DDNS#125]
dddns.*.com(AAAA) ==> 240e:f8:***:***::100 [via DIRECT]
WARNING:root:/*******974eb6dd7f23266efcf143028/dns_records/****61887a6bf9e8f893fa61ca8984 : error[400]:{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 9021,
      "message": "Invalid TTL. Must be between 120 and 2,147,483,647 seconds, or 1 for automatic"
    }
  ],
  "messages": []
}

ERROR:root:{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 9021,
      "message": "Invalid TTL. Must be between 120 and 2,147,483,647 seconds, or 1 for automatic"
    }
  ],
  "messages": []
}

**Comment by GoldJohnKing** [comment]
刚刚我也差不多在1小时前遭遇了同样的情况，推测是Cloudflare的接口发生了变更，要求显式指明TTL值。

**Comment by snakwu** [comment]
对的，是ttl问题，最直接方法是，去域名管理上面删除，让ddns自动建就行了
