### ISSUE TITLE
[feature] 您好，定时时间可调功能。

### ISSUE THREAD

**Issue by EricMzky** [NewFuture/DDNS#126]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
您好，现在这个定时执行的时间在是多少？我们是否可以自定义呢？如果加一个这个功能，岂止是太好用啦！谢谢采纳。

**Comment by NewFuture** [comment]
定时时间在定时任务的脚本中，可以自行修改

**Comment by EricMzky** [comment]
谢谢！
