### ISSUE TITLE
TTL总是被恢复为10分钟

### ISSUE THREAD

**Issue by Wizzercn** [NewFuture/DDNS#13]
如何更改为1秒？

PS：我的DNS是付费用户，可以设置为1秒~~

**Comment by NewFuture** [comment]
在DNS服务商把对应的域名ttl设置成1s试试

这个程序默认创建记录的是设置 600s (https://github.com/NewFuture/DDNS/blob/master/dns/dnspod.py#L165)

修改记录的时候不更新ttl

**Comment by Wizzercn** [comment]
@NewFuture 没用哦，就是在域名解析处设置1s的，每次都被DDNS重置了~~

**Comment by Wizzercn** [comment]
当前分配的DNS服务器是：vip1.alidns.com, vip2.alidns.com

**Comment by Wizzercn** [comment]
ok了，alidns.py 增加了TTL=1~~谢谢

**Comment by NewFuture** [comment]
嗯，这个地方应该增加一个配置项

**Comment by PHCSJC** [comment]
大佬，cloudflare支持设置TTL吗？
本来手动改成2min的，但总是被改回auto，可能是更新IP的原因，所以请问下在更新时能否设置TTL呢？谢谢！

**Comment by NewFuture** [comment]
计划下一个 minor 版本加上 #14

**Comment by NewFuture** [comment]
https://github.com/NewFuture/DDNS/tree/feat-ttl
这个分支已经加入ttl设置的Feature 可以试试

**Comment by PHCSJC** [comment]
> https://github.com/NewFuture/DDNS/tree/feat-ttl
> 这个分支已经加入ttl设置的Feature 可以试试

这个要自己编译吗？

**Comment by PHCSJC** [comment]
用原代码直接运行的方式，没有成功呢，IP更新后TTL还是auto，配置如下：
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.json",
  "dns": "cloudflare",
  "id": "*********",
  "token": "*********",
  "index4": "public",
  "index6": "default",
  "ipv4": ["aa.bb.cc"],
  "ipv6": [],
  "ttl": 120,
  "cache": false
}

**Comment by NewFuture** [comment]
@PHCSJC  ip是不是没有发生变化，是的话记录删了再试试

 还是没变化，debug打开看一下log,请求里面有没有？

**Comment by PHCSJC** [comment]
> @PHCSJC ip是不是没有发生变化，是的话记录删了再试试
> 
> 还是没变化，debug打开看一下log,请求里面有没有？

debug里有太多的个人信息了，怎么搞？你要哪一部分？
