### ISSUE TITLE
双击DDNS后出现 WARNING:root:Cache file is out of dated.

### ISSUE THREAD

**Issue by EricMzky** [NewFuture/DDNS#131]
这个问题是什么呀？耽误使用么？还有一点，我想电脑关机重启后自动启动DDNS和定时任务。我该如何操作？谢谢！
config配置信息如下：

{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": false,
  "dns": "alidns",
  "id": "XXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "index4": "public",
  "index6": "default",
  "ipv4": [
    "XXXXX.com",
    "www.XXXXX.com"
  ],
  "ipv6": [
    "newfuture.cc",
    "ipv6.ddns.newfuture.cc"
  ],
  "proxy": null,
  "token": "XXXXXXXXXXXXXXXXXXXXXXX",
  "ttl": null
}

如果配置信息错误 请指教 谢谢1!

**Comment by EricMzky** [comment]
运行环境：Windows10专业版，谢谢！

**Comment by zhuziyi1989** [comment]
macOS 同样出现这个问题 cache file not exist

**Comment by NewFuture** [comment]
缓存失效，会自动更新，没有问题

**Comment by EricMzky** [comment]
谢谢

**Comment by EricMzky** [comment]
谢谢

> macOS 同样出现这个问题 cache file not exist
> 
> 将 https://api-ipv4.ip.sb/ip 改成 http://ip.3322.net/

请问一下，这个在哪个文件里面去改？谢谢
