### ISSUE TITLE
[debug]

### ISSUE THREAD

**Issue by 1726400669** [NewFuture/DDNS#133]
### 2.8.1

* DDNS Version: 
* OS Version： win10
* Type(运行方式): exe

### config file [配置文件]

```
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "id": "XXXXXXXX@qq.com",  (登陆的邮箱)
  "token": "31XXXXX", （登录密码）
  "dns": "cloudflare",
  "ipv4": [],
  "ipv6": ["XXXXX"], （一个域名，验证过已经通了）
  "index4": 0,
  "index6": 0,（这个地方换成“public”，能检测到正确ipv6地址，但仍然报相同的错误）
  "ttl": 600,
  "proxy": "DIRECT",
  "debug": true
}
```

###  debug output [调试输出]

```sh
DDNS[ v2.8.1@2020-01-14T05:50:44+00:00 ] run: nt win32
Configuration was loaded from <== D:\DDNS\config.json
========================= Mon Feb 24 16:09:57 2020 =========================
2020-02-24 16:09:57,610 <cache.load> 48@util\cache.py
[DEBUG] load cache data from C:\Users\17264\AppData\Local\Temp\ddns.cache
2020-02-24 16:09:57,613 <run.main> 182@run.py
[WARNING] Cache file is out of dated.
2020-02-24 16:09:57,664 <ip.local_v6> 40@util\ip.py
[DEBUG] [(<AddressFamily.AF_INET6: 23>, 0, 0, '', ('fe80::a5f9:2f93:199:4076', 0, 0, 11)), (<AddressFamily.AF_INET6: 23>, 0, 0, '', ('2409:XXXX:8216:3c80:a5f9:2f93:199:XXXX', 0, 0, 0)), (<AddressFamily.AF_INET6: 23>, 0, 0, '', ('fe80::692f:33f5:5d38:b434', 0, 0, 18)), (<AddressFamily.AF_INET6: 23>, 0, 0, '', ('fe80::9e7:8bd8:6e76:8397', 0, 0, 19)), (<AddressFamily.AF_INET6: 23>, 0, 0, '', ('fe80::ad59:7443:68e1:92a6', 0, 0, 45))]

XXXX.ml(AAAA) ==> fe80::a5f9:2f93:199:4076 [via DIRECT]
2020-02-24 16:09:57,667 <cloudflare.update_record> 127@dns\cloudflare.py
[INFO] >>>>>XXXX.ml(AAAA)
2020-02-24 16:09:57,668 <cloudflare.request> 44@dns\cloudflare.py
[INFO] api.cloudflare.com/ : {'per_page': 50}
2020-02-24 16:09:59,747 <cloudflare.request> 68@dns\cloudflare.py
[WARNING] ?per_page=50 : error[400]:{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
2020-02-24 16:09:59,747 <run.change_dns_record> 120@run.py
[ERROR] {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
2020-02-24 16:09:59,758 <cache.sync> 85@util\cache.py
[DEBUG] save cache data to C:\Users\17264\AppData\Local\Temp\ddns.cache
```

**Additional context**

**Comment by cybmp3** [comment]
这个token不是登录密码哦

**Comment by 1726400669** [comment]
@cybmp3
我使用`Edit zone DNS`模板生成，`Zone Resources` 选择了我的域名
我试了`API Tokens `和`API Keys` 中的`Global API Key` 和 `Origin CA Key` 这三个都没有成功，请问token是什么样子的呢？在哪里获取？

**Comment by cybmp3** [comment]
> 
> 
> @cybmp3
> 我使用`Edit zone DNS`模板生成，`Zone Resources` 选择了我的域名
> 我试了`API Tokens `和`API Keys` 中的`Global API Key` 和 `Origin CA Key` 这三个都没有成功，请问token是什么样子的呢？在哪里获取？

你bing一下cloudflare token或者cloudflare 密钥都行。
算了算了，我帮你。。。https://support.cloudflare.com/hc/zh-cn/articles/200167836-%E7%AE%A1%E7%90%86-API-%E4%BB%A4%E7%89%8C%E5%92%8C%E5%AF%86%E9%92%A5

**Comment by 1726400669** [comment]
@cybmp3 
可是我就是按照你发的连接上的第10步上面的 API 令牌 写的啊？
第5b步 Template 选的是Edit zone DNS 
第7步 Zone Resource 我select 我的域名XXXX.ml，其他都一样

```
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "id": "",
  "token": "JLuyZvqcVBb8V688ZY3-37PL85RlTHKJvDReXXXX",
  "dns": "cloudflare",
  "ipv4": [],
  "ipv6": ["XXXXX.ml"], 
  "index4": 0,
  "index6": "public",
  "ttl": 600,
  "proxy": "DIRECT",
  "debug": true
}
```

**Comment by cybmp3** [comment]
> 
> 
> @cybmp3
> 可是我就是按照你发的连接上的第10步上面的 API 令牌 写的啊？
> 第5b步 Template 选的是Edit zone DNS
> 第7步 Zone Resource 我select 我的域名XXXX.ml，其他都一样
> 
> ```
> {
>   "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
>   "id": "",
>   "token": "JLuyZvqcVBb8V688ZY3-37PL85RlTHKJvDReXXXX",
>   "dns": "cloudflare",
>   "ipv4": [],
>   "ipv6": ["XXXXX.ml"], 
>   "index4": 0,
>   "index6": "public",
>   "ttl": 600,
>   "proxy": "DIRECT",
>   "debug": true
> }
> ```

id写上你的邮箱了吗

**Comment by 1726400669** [comment]
@cybmp3 
我写上我的邮箱试过，报的是一样的错。

**Comment by cybmp3** [comment]
> 
> 
> @cybmp3
> 我写上我的邮箱试过，报的是一样的错。

用这个
![1](https://user-images.githubusercontent.com/14276116/75221860-cbfd8580-57dd-11ea-91e5-b358462a5291.png)

**Comment by 1726400669** [comment]
@cybmp3 
通了。
介绍界面上应该是不准确的，我单独使用API token或者API Key都不正常，使用邮箱+API token不正常，只有使用邮箱+API Key一种是正常的。应该是我试的时候遗漏了。非常感谢。
