### ISSUE TITLE
[debug]宝塔运行失败

### ISSUE THREAD

**Issue by 24021438** [NewFuture/DDNS#135]
![宝塔ddns](https://user-images.githubusercontent.com/56147487/75620652-43f4f280-5bc6-11ea-9bbc-9b535d2b5558.png)
bao'y宝塔运行不会创建配置文件，手动创建指定读取失败

**Comment by NewFuture** [comment]
宝塔是什么?
是不是路径不对？

**Comment by 24021438** [comment]
bt.cn

> 宝塔是什么？
> 是不是路径不对？

**Comment by NewFuture** [comment]
确认一下配置文件的路径是否正确，
以及用这个web版shell的身份和权限
