### ISSUE TITLE
[debug]华为云解析有bug

### ISSUE THREAD

**Issue by 18017894** [NewFuture/DDNS#136]
华为云解析有bug显示如下

```
Traceback (most recent call last):
  File "run.py", line 189, in <module>
  File "run.py", line 162, in main
AttributeError: module 'dns' has no attribute 'huaweidns'
[18584] Failed to execute script run
```

**Comment by NewFuture** [comment]
@18017894 那个版本的，是编译的二进制版吗？


@cybmp3 帮忙确认一下，另外这个地方需要把新的DNS加进去 https://github.com/NewFuture/DDNS/blob/master/.build/ddns.spec#L23

**Comment by 18017894** [comment]
@cybmp3 是二进制版

**Comment by cybmp3** [comment]
> 
> 
> @cybmp3 是二进制版

因为我从来没用过二进制的。。。忘了这茬了。新的pull request加上了

**Comment by 18017894** [comment]
ok

**Comment by 18017894** [comment]
@cybmp3 话说华为云id一栏填什么啊，邮箱和用户名都不行
```
WARNING:root:/v2/zones : error[401]: {"error_msg":"Incorrect IAM authentication information: Get secretKey failed,ak:zyczy123123,err:ak not exist","error_code":"APIGW.0301","request_id":"c619857aa68f5ca8fdc888f34a50e3f2"}

ERROR:root:{"error_msg":"Incorrect IAM authentication information: Get secretKey failed,ak:zyczy123123,err:ak not exist","error_code":"APIGW.0301","request_id":"c619857aa68f5ca8fdc888f34a50e3f2"}
```

**Comment by 18017894** [comment]
@cybmp3 话说这样是为什么啊
```
WARNING:root:/v2/zones : error[401]: {"error_msg":"Incorrect IAM authentication information: verify aksk signature fail","error_code":"APIGW.0301","request_id":"882e6b1449702d09629402496089a284"}

ERROR:root:{"error_msg":"Incorrect IAM authentication information: verify aksk signature fail","error_code":"APIGW.0301","request_id":"882e6b1449702d09629402496089a284"}
```

**Comment by cybmp3** [comment]
> 
> 
> @cybmp3 话说这样是为什么啊
> 
> ```
> WARNING:root:/v2/zones : error[401]: {"error_msg":"Incorrect IAM authentication information: verify aksk signature fail","error_code":"APIGW.0301","request_id":"882e6b1449702d09629402496089a284"}
> 
> ERROR:root:{"error_msg":"Incorrect IAM authentication information: verify aksk signature fail","error_code":"APIGW.0301","request_id":"882e6b1449702d09629402496089a284"}
> ```

是AS AK啊，不是IAM

**Comment by 18017894** [comment]
@cybmp3 没懂，您能详细说一下嘛

**Comment by cybmp3** [comment]
> 
> 
> @cybmp3 没懂，您能详细说一下嘛

![20200302172426](https://user-images.githubusercontent.com/14276116/75662816-b4753f80-5caa-11ea-968a-de006f63f42f.png)
图来~

**Comment by 18017894** [comment]
@cybmp3 就是填的这个啊，填到了id里

**Comment by 18017894** [comment]
再问下，id和token都是填什么的啊，华为云用不明白

**Comment by 18017894** [comment]
懂了懂了，不用了

**Comment by 18017894** [comment]
@cybmp3 又出问题了，python run.py之后只输出了一个"."

**Comment by 18017894** [comment]
而且域名还没更新解析

**Comment by cybmp3** [comment]
> 
> 
> 而且域名还没更新解析

加一下南极生物:"⑤酒667766"

**Comment by 18017894** [comment]
好了好了

**Comment by cybmp3** [comment]
> 
> 
> @18017894 那个版本的，是编译的二进制版吗？
> 
> @cybmp3 帮忙确认一下，另外这个地方需要把新的DNS加进去 https://github.com/NewFuture/DDNS/blob/master/.build/ddns.spec#L23

路由器没有关闭IPV6防火墙的功能

**Comment by cybmp3** [comment]
LOG显示已经正常成功更新![20200302182736](https://user-images.githubusercontent.com/14276116/75667983-85170080-5cb3-11ea-9f5b-2995d9af9159.png)
![20200302182659](https://user-images.githubusercontent.com/14276116/75667987-86482d80-5cb3-11ea-9d11-e2c18d33d5d5.png)

**Comment by NewFuture** [comment]
等 二进制的fix 了再close

**Comment by cybmp3** [comment]
> 
> 
> 等 二进制的fix 了再close

我测试一下二进制
