### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by kaikai12** [NewFuture/DDNS#138]
## **Describe the bug [描述]**
'NoneType' object has no attribute 'group'

运行十来次成功一次，每次都是这个问题，百度说是re.match 模块出错

**Comment by kaikai12** [comment]
我用的是python3

**Comment by kaikai12** [comment]
很奇怪，同样的源码我在pycharm 上运行成功，在centos7 安装了python3 和同样的模块下运行报这个错误

**Comment by NewFuture** [comment]
可能是ip模快对于提取ip有BUG,可以贴一下配置和log

**Comment by NewFuture** [comment]
是否相关

#153 
#150 


如果没解决重新开一个，贴上 配置和log
