### ISSUE TITLE
是否可以考虑加入IP更新后的通知方式？

### ISSUE THREAD

**Issue by cklx0719** [NewFuture/DDNS#148]
可以考虑加入IP更新后邮箱通知或微信通知(http://sc.ftqq.com/)的方式。

**Comment by NewFuture** [comment]
#103 ？

**Comment by NewFuture** [comment]
master 已更新 

* `dns`: `callback`

此时 使用自定义的http请求
* `id` 参数传入 url 
* `token` 参数传入body,token为空使用GET否正使用POST

这两个参数的字符串`__DOMAIN__`和`__IP__`分别替换成对应的IP地址和域名

比如 POST到一个自定义的API
```json
{
"dns":"callback",
"id":"http://ip.update.me",
"token":"{\"customParam\":\"__DOMAIN__\",\"ip\":\"__IP__\"}",
}
```
或者 GET请求
```json
{
"dns":"callback",
"id":"https://sc.ftqq.com/?parm=____DOMAIN__&ip=__IP__"
}
```

**Comment by obrua** [comment]
这个和"dns": "dnspod" 配置是不是冲突的？如果我是想修改dnspod的配置的同时通知，是不是不支持

**Comment by NewFuture** [comment]
@obrua 是的，暂时只能跑两个job
