### ISSUE TITLE
cloudflare的APItoken配置不生效

### ISSUE THREAD

**Issue by wlmqpsc** [NewFuture/DDNS#152]
### version info [基本信息]

* DDNS Version: 2.9.0
* OS Version： CentOS 8.0 x64
* Type(运行方式): Binary/Python Python
* related issues (相关问题): cloudflare使用不正常

### config file [配置文件]

```json
{
  "id": "我注册的cloudflare邮箱",
  "token": "",
  "dns": "cloudflare",
  "ipv4": ["我的二级域名"],
  "ipv6": [],
  "index4": "url:http://ip.3322.net/",
  "index6": "public",
  "ttl": 600,
  "proxy": "127.0.0.1:1080;DIRECT",
  "debug": false
}
```

###  debug output [调试输出]

```sh
WARNING:root:?per_page=50 : error[400]:{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6102,"message":"Invalid format for X-Auth-Email header"},{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
ERROR:root:{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6102,"message":"Invalid format for X-Auth-Email header"},{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}

```

**Additional context**

我确定我把APItoken复制全了，但是它依旧显示这个信息！id我尝试了邮箱以及账户id。
我的API权限 Zone.DNS
使用API key正常运行！

**Comment by wlmqpsc** [comment]
貌似现在不支持cloudflare的API token。token的那栏要写API key，并在id栏填写好邮箱。

**Comment by NewFuture** [comment]
根据文档上的描述，应该支持这两种方式
邮箱加API key
```json
{
  "id": "注册的cloudflare邮箱",
  "token": "API key"
}
```
或者ID为加API　TOKEN
```json
{
  "id": "",
  "token": "API token"
}
```
可以确认一下

**Comment by wlmqpsc** [comment]
邮箱加API key正常运行，但是ID为空，加API TOKEN还是不行。输出如下

`WARNING:root:?per_page=50 : error[400]:{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6102,"message":"Invalid format for X-Auth-Email header"},{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
ERROR:root:{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6102,"message":"Invalid format for X-Auth-Email header"},{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
`

**Comment by PHCSJC** [comment]
同样的问题，API TOKEN 无论怎么设置都不行，求正确的配置方法。

**Comment by NewFuture** [comment]
@PHCSJC  @wlmqpsc 
代码这个地方现在只有 null 或者 没有ID这个字段才会用Token。
用 null 看看可行不？

**Comment by sht2017** [comment]
@NewFuture 找到原因了 因为如果限制域权限的话需要追加一个域名参数 
详见
https://community.cloudflare.com/t/bug-zone-detail-by-name-requires-zone-list-permission/128042/14

**Comment by robertu7** [comment]
https://blog.crstian.me/en/post/2022-01-19-openwrt-ddns/

**Comment by chengnan049** [comment]
> https://blog.crstian.me/en/post/2022-01-19-openwrt-ddns/

谢谢兄弟，问题解决了，问题出在用户名上，根据 Blog ，应该使用 Bearer
