### ISSUE TITLE
是否能帮忙看看是不是配置文件的错误？

### ISSUE THREAD

**Issue by zhihuiyuze** [NewFuture/DDNS#155]
```sh
PS E:\DDNS-master> python run.py
DDNS[ ${BUILD_SOURCEBRANCHNAME}@${BUILD_DATE} ] run: nt win32
Configuration was loaded from <== E:\DDNS-master\config.json
========================= Sun Mar 22 21:14:35 2020 =========================
2020-03-22 21:14:35,703 <cache.load> 48@E:\DDNS-master\util\cache.py
[DEBUG] load cache data from C:\Users\zhyz\AppData\Local\Temp\ddns.cache
2020-03-22 21:14:35,704 <run.main> 182@run.py
[WARNING] Cache file is out of dated.
2020-03-22 21:14:35,704 <ip._open> 51@E:\DDNS-master\util\ip.py
[DEBUG] open: https://pv.sohu.com/cityjson
2020-03-22 21:14:35,787 <ip._open> 58@E:\DDNS-master\util\ip.py
[ERROR] 'utf-8' codec can't decode byte 0xd5 in position 72: invalid continuation byte
2020-03-22 21:14:35,787 <ip._open> 51@E:\DDNS-master\util\ip.py
[DEBUG] open: http://ipv6-test.com/api/myip.php
2020-03-22 21:14:36,517 <ip._open> 55@E:\DDNS-master\util\ip.py
[DEBUG] response: 161.117.83.60
2020-03-22 21:14:36,525 <ip._open> 58@E:\DDNS-master\util\ip.py
[ERROR] 'NoneType' object has no attribute 'group'
PS E:\DDNS-master>
```

配置文件
```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "cloudflare",
  "id": "",
  "index4": "public",
  "index6": "public",
  "ipv4": [
    "zhyz.ru",
    "www.zhyz.ru"
  ],
  "ipv6": ["ipv6.zhzy.ru"],
  "proxy": "DIRECT",
  "token": "xxxx"
}
```
帮忙看看，谢谢了各位
```
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "cloudflare",
  "id": "",
  "index4": "public",
  "index6": "public",
  "ipv4": [
    "zhyz.ru",
    "www.zhyz.ru"
  ],
  "ipv6": ["ipv6.zhzy.ru"],
  "proxy": "DIRECT",
  "token": "zcQ8hcwOCUL"
}
```

**Comment by NewFuture** [comment]
用这个地址

https://pv.sohu.com/cityjson?ie=utf-8

#150

**Comment by zhihuiyuze** [comment]
`2020-03-24 10:09:48,737 <cache.load> 48@E:\DDNS-master\util\cache.py
[DEBUG] load cache data from C:\Users\zhyz\AppData\Local\Temp\ddns.cache
2020-03-24 10:09:48,746 <run.main> 182@run.py
[WARNING] Cache file is out of dated.`
`{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "cloudflare",
  "id": "",
  "index4": "https://pv.sohu.com/cityjson?ie=utf-8",
  "index6": "https://pv.sohu.com/cityjson?ie=utf-8",
  "ipv4": [
    "zhyz.ru",
    "www.zhyz.ru"
  ],
  "ipv6": ["ipv6.zhzy.ru"],
  "proxy": "DIRECT",
  "token": "zcQ0wOCUL"
}`
但是cloudflare的DNS还是没有记录。
![image](https://user-images.githubusercontent.com/38281461/77381174-2b888a00-6db8-11ea-84ee-74ebfed1a887.png)

API设置应该没有问题吧

**Comment by NewFuture** [comment]
1. sohu的API不支持ipv6
2. 日志不完整

**Comment by zhihuiyuze** [comment]
`PS E:\DDNS-master> python run.py
DDNS[ ${BUILD_SOURCEBRANCHNAME}@${BUILD_DATE} ] run: nt win32
Configuration was loaded from <== E:\DDNS-master\config.json
========================= Tue Mar 24 15:30:43 2020 =========================
2020-03-24 15:30:43,784 <cache.load> 48@E:\DDNS-master\util\cache.py
[DEBUG] load cache data from C:\Users\zhyz\AppData\Local\Temp\ddns.cache
2020-03-24 15:30:43,799 <run.main> 182@run.py
[WARNING] Cache file is out of dated.
PS E:\DDNS-master>`
已经去除ipv6

**Comment by NewFuture** [comment]
cloudflare 如果用token的话 需要 id 设置成 null或者删掉

#157 这个PR合并了才支持空字符串

**Comment by zhihuiyuze** [comment]
目前配置文件如下
`{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "cloudflare",
  "index4": "https://pv.sohu.com/cityjson?ie=utf-8",
  "ipv4": [
    "zhyz.ru",
    "www.zhyz.ru"
  ],
  "proxy": "DIRECT",
  "token": "gP_YyB54qu4qmJP8KOU4fR-G-MWayhtjFe4rLEMf"
}`
依然出现
`PS E:\DDNS-master> python run.py
DDNS[ ${BUILD_SOURCEBRANCHNAME}@${BUILD_DATE} ] run: nt win32
Configuration was loaded from <== E:\DDNS-master\config.json
========================= Tue Mar 24 17:49:59 2020 =========================
2020-03-24 17:49:59,496 <cache.load> 48@E:\DDNS-master\util\cache.py
[DEBUG] load cache data from C:\Users\zhyz\AppData\Local\Temp\ddns.cache
2020-03-24 17:49:59,498 <run.main> 182@run.py
[WARNING] Cache file is out of dated.
PS E:\DDNS-master>`

**Comment by zhihuiyuze** [comment]
目前配置文件如下
`{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "cloudflare",
  "index4": "https://pv.sohu.com/cityjson?ie=utf-8",
  "ipv4": [
    "zhyz.ru",
    "www.zhyz.ru"
  ],
  "proxy": "DIRECT",
  "token": "gP_YyB54qu4qmJP8KOU4fR-G-MWayhtjFe4rLEMf"
}`
依然出现
`PS E:\DDNS-master> python run.py
DDNS[ ${BUILD_SOURCEBRANCHNAME}@${BUILD_DATE} ] run: nt win32
Configuration was loaded from <== E:\DDNS-master\config.json
========================= Tue Mar 24 17:49:59 2020 =========================
2020-03-24 17:49:59,496 <cache.load> 48@E:\DDNS-master\util\cache.py
[DEBUG] load cache data from C:\Users\zhyz\AppData\Local\Temp\ddns.cache
2020-03-24 17:49:59,498 <run.main> 182@run.py
[WARNING] Cache file is out of dated.
PS E:\DDNS-master>`

**Comment by NewFuture** [comment]
```
"index4": "url:https://pv.sohu.com/cityjson?ie=utf-8"
```
自定义URL需要加上前缀

**Comment by zhihuiyuze** [comment]
`[ERROR] {"success":false,"errors":[{"code":0,"message":"Actor 'com.cloudflare.api.token.46f9c6db75ddf646c3046d11cd88c05a' requires permission 'com.cloudflare.api.account.zone.list' to list zones"}],"messages":[],"result":null}
2020-03-24 18:13:02,885 <cache.sync> 85@E:\DDNS-master\util\cache.py`
完整版，DNS还是没记录。
`PS E:\DDNS-master> python run.py
DDNS[ ${BUILD_SOURCEBRANCHNAME}@${BUILD_DATE} ] run: nt win32
Configuration was loaded from <== E:\DDNS-master\config.json
========================= Tue Mar 24 18:13:00 2020 =========================
2020-03-24 18:13:00,050 <cache.load> 48@E:\DDNS-master\util\cache.py
[DEBUG] load cache data from C:\Users\zhyz\AppData\Local\Temp\ddns.cache
2020-03-24 18:13:00,051 <run.main> 182@run.py
[WARNING] Cache file is out of dated.
2020-03-24 18:13:00,051 <ip._open> 51@E:\DDNS-master\util\ip.py
[DEBUG] open: https://pv.sohu.com/cityjson?ie=utf-8
2020-03-24 18:13:00,145 <ip._open> 55@E:\DDNS-master\util\ip.py
[DEBUG] response: var returnCitySN = {"cip": "115.206.246.73", "cid": "330100", "cname": "浙江省杭州市"};

zhyz.ru(A) ==> 115.206.246.73 [via DIRECT]
2020-03-24 18:13:00,148 <cloudflare.update_record> 127@E:\DDNS-master\dns\cloudflare.py
[INFO] >>>>>zhyz.ru(A)
2020-03-24 18:13:00,150 <cloudflare.request> 44@E:\DDNS-master\dns\cloudflare.py
[INFO] api.cloudflare.com/ : {'per_page': 50}
2020-03-24 18:13:00,871 <cloudflare.request> 68@E:\DDNS-master\dns\cloudflare.py
[WARNING] ?per_page=50 : error[403]:{"success":false,"errors":[{"code":0,"message":"Actor 'com.cloudflare.api.token.46f9c6db75ddf646c3046d11cd88c05a' requires permission 'com.cloudflare.api.account.zone.list' to list zones"}],"messages":[],"result":null}
2020-03-24 18:13:00,871 <run.change_dns_record> 120@run.py
[ERROR] {"success":false,"errors":[{"code":0,"message":"Actor 'com.cloudflare.api.token.46f9c6db75ddf646c3046d11cd88c05a' requires permission 'com.cloudflare.api.account.zone.list' to list zones"}],"messages":[],"result":null}

www.zhyz.ru(A) ==> 115.206.246.73 [via DIRECT]
2020-03-24 18:13:00,876 <cloudflare.update_record> 127@E:\DDNS-master\dns\cloudflare.py
[INFO] >>>>>www.zhyz.ru(A)
2020-03-24 18:13:00,877 <cloudflare.request> 44@E:\DDNS-master\dns\cloudflare.py
[INFO] api.cloudflare.com/ : {'per_page': 50}
2020-03-24 18:13:02,880 <cloudflare.request> 68@E:\DDNS-master\dns\cloudflare.py
[WARNING] ?per_page=50 : error[403]:{"success":false,"errors":[{"code":0,"message":"Actor 'com.cloudflare.api.token.46f9c6db75ddf646c3046d11cd88c05a' requires permission 'com.cloudflare.api.account.zone.list' to list zones"}],"messages":[],"result":null}
2020-03-24 18:13:02,880 <run.change_dns_record> 120@run.py
[ERROR] {"success":false,"errors":[{"code":0,"message":"Actor 'com.cloudflare.api.token.46f9c6db75ddf646c3046d11cd88c05a' requires permission 'com.cloudflare.api.account.zone.list' to list zones"}],"messages":[],"result":null}
2020-03-24 18:13:02,885 <cache.sync> 85@E:\DDNS-master\util\cache.py
[DEBUG] save cache data to C:\Users\zhyz\AppData\Local\Temp\ddns.cache`
请问这是关于API的错误？

**Comment by NewFuture** [comment]
> [ERROR] {"success":false,"errors":[{"code":0,"message":"Actor 'com.cloudflare.api.token.46f9c6db75ddf646c3046d11cd88c05a' requires permission 'com.cloudflare.api.account.zone.list' to list zones"}],"messages":[],"result":null}

token的权限不够

**Comment by zhihuiyuze** [comment]
Zone是啥权限？

**Comment by zhihuiyuze** [comment]
这到底是需要什么权限？DNS的zone和Account编辑都试过了还是不行

**Comment by NewFuture** [comment]
> requires permission **'com.cloudflare.api.account.zone.list'** to list zones

错误提示是列出Zone的权限

**Comment by zhihuiyuze** [comment]
![image](https://user-images.githubusercontent.com/38281461/77418218-90b49d80-6e01-11ea-9a78-05a396b37a64.png)
全部编辑权限应该包括读取吧，因为只能选一个。
好悬啊

**Comment by NewFuture** [comment]
Cloudflare 的DNS没用过, 

全部权限或者 zone.list+修改。创建之类的

**Comment by zhihuiyuze** [comment]
谢谢了，用邮箱+Global API Key可以。局部的api玄学

**Comment by andyf1111** [comment]
> 这到底是需要什么权限？DNS的zone和Account编辑都试过了还是不行

![批注 2020-08-13 081237](https://user-images.githubusercontent.com/19814597/90081478-0b923c80-dd40-11ea-9825-9ac8a8c849e0.png)
按上图这么设置才行，看起来这点迷惑了很多人#155 #159 ，Global key毕竟还是不安全，查了一下按目前这个逻辑至少得把权限扩大到域名所在账户才行。参考：https://community.cloudflare.com/t/how-to-get-zone-id-with-zone-specific-api-key/105300

我没太看懂cache文件逻辑是怎么写的，但是看debug每次都会请求获取一遍**区域ID**和**DNS_ID**，好像这俩也没存到cache里，最好还是能把他们放到配置文件里，尤其**区域ID**页面里就能看到，**DNS_ID**怎么手动获取cloudflare文档里也写得很清楚，顶多Windows里的curl语法略有不同，我们可以在README里多加个说明，每次这么请求也会明显拖慢速度#127

**Comment by lirener** [comment]
![全球API](https://github.com/NewFuture/DDNS/assets/19354130/890b3538-fc88-4710-8f08-4a6c3f2ba2b0)
补个图 怕有人不知道全球API怎么获取
