### ISSUE TITLE
[debug] AttributeError: module 'dns' has no attribute 'cloudflare'

### ISSUE THREAD

**Issue by laozhoubuluo** [NewFuture/DDNS#160]
## **Describe the bug [描述]**

使用v2.9.0二进制版本，在Debian 10和Windows 10 1909上使用，Python报错“AttributeError: module 'dns' has no attribute 'cloudflare'”，回滚到v2.8.0或v2.8.1二进制版本无问题。

Traceback (most recent call last):
  File "run.py", line 189, in <module>
  File "run.py", line 162, in main
AttributeError: module 'dns' has no attribute 'cloudflare'
[9444] Failed to execute script run

## **To Reproduce [复现]**

使用v2.9.0二进制版本，配置DNS为Cloudflare即可。

### version info [基本信息]

* DDNS Version: v2.9.0
* OS Version： Windows 10 1909 / Debian 10
* Type(运行方式): 二进制
* related issues (相关问题): https://github.com/NewFuture/DDNS/issues/136

### config file [配置文件]

```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "token": "我的cloudflare密钥",
  "dns": "cloudflare",
  "ipv4": ["域名"],
  "ipv6": ["域名"],
  "index4": "public",
  "index6": "public",
  "ttl": 300,
  "debug": true,
  "cache": true
}
```

###  debug output [调试输出]

```sh
无
```

**Additional context**

**Comment by NewFuture** [comment]
可能是打包的配置有问题，我晚点确认一下

**Comment by NewFuture** [comment]
试一下 2.9.1

**Comment by laozhoubuluo** [comment]
> 试一下 2.9.1

2.9.1 没有这个问题了，谢谢。
