### ISSUE TITLE
[debug] pip2 (python2) install  throw 'module' object has no attribute

### ISSUE THREAD

**Issue by kkbbzjh** [NewFuture/DDNS#164]
### version info [基本信息]

* DDNS Version: v2.9.1@2020-03-26T13:04:46+00:00
* OS Version： Centos7 x64
* Type(运行方式): ddns -c config.json
* related issues (相关问题): 报错

### config file [配置文件]

```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "cloudflare",
  "id": "xxxxxxxxxx@qq.com",
  "index4": "url:http://ipv4.ip.sb",
  "index6": "false",
  "ipv4": [
    "aaa.xxxxxxxxxx.com"
  ],
  "ipv6": [ ],
  "proxy": "127.0.0.1:1080;DIRECT",
  "token": "xxxxxxxxxx",
  "ttl": 120
}
```

###  debug output [调试输出]

```sh
Traceback (most recent call last):
  File "/usr/bin/ddns", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/run.py", line 163, in main
    dns = getattr(__import__('dns', fromlist=[dns_provider]), dns_provider)
AttributeError: 'module' object has no attribute 'cloudflare'

```

**Additional context**

**Comment by laozhoubuluo** [comment]
最新版2.9.1已修复此问题，请下载最新版本再试。

**Comment by kkbbzjh** [comment]
自己顶一下~~~~

**Comment by NewFuture** [comment]
这个貌似之前版本打包的一个BUG #160 

最新版应该没问题了？

**Comment by kkbbzjh** [comment]
我更新一下试试

**Comment by kkbbzjh** [comment]
我更新了一下，还是有这个错误

Traceback (most recent call last):
  File "/usr/bin/ddns", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/run.py", line 163, in main
    dns = getattr(__import__('dns', fromlist=[dns_provider]), dns_provider)
AttributeError: 'module' object has no attribute 'cloudflare'

查过版本是2.9.2

**Comment by NewFuture** [comment]
是 pip 安装的吗？

**Comment by kkbbzjh** [comment]
对，pip install ddns 然后 pip install -U ddns更新过

**Comment by kkbbzjh** [comment]
也已经更新过pip install --upgrade pip

**Comment by NewFuture** [comment]
cloudflare 换成 `dnspod` 是不是也有类似的错误?

**Comment by kkbbzjh** [comment]
对的，试了一下，cloudflare换成dnspod以后，显示的是：

Traceback (most recent call last):
  File "/usr/bin/ddns", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/run.py", line 163, in main
    dns = getattr(__import__('dns', fromlist=[dns_provider]), dns_provider)
AttributeError: 'module' object has no attribute 'dnspod'

**Comment by NewFuture** [comment]
可能是 `__import__` 在python2中安装会有问题，
我用的是python3 pip装的ddns ，运行起来OK

我有空看看，或者你先帮忙调查一下 😹

**Comment by kkbbzjh** [comment]
好的，我是一下pip3

**Comment by kkbbzjh** [comment]
但是我其他的机器，用之前的版本是没问题的

**Comment by kkbbzjh** [comment]
果然PYTHON3是没有问题的，就PYTHON2有问题

**Comment by NewFuture** [comment]
最新测试OK
