### ISSUE TITLE
同时从两个url获取公网ip？

### ISSUE THREAD

**Issue by leonhart118** [NewFuture/DDNS#165]
### version info [基本信息]

* DDNS Version: 
* OS Version： 
* Type(运行方式): Binary/Python
* related issues (相关问题): 

### config file [配置文件]

```json
{
}
```

###  debug output [调试输出]

```sh
粘贴输出日志
paste out put here
```

**Additional context**

**Comment by laozhoubuluo** [comment]
现在应该是只支持一个v4，一个v6。不支持从不同的url获取同类型的地址。

**Comment by leonhart118** [comment]
能不能支持下，万一一个url挂了，还可以备用？

**Comment by EricMzky** [comment]
好建议，可以多加两个，比较一下看看是不是都一样。建议不错，建议采纳噢

**Comment by NewFuture** [comment]
index4/index6 现在可配置数组，这个功能已经支持了

#188
