### ISSUE TITLE
[debug]用计划任务无法成功，手动双击才能成功。

### ISSUE THREAD

**Issue by leonhart118** [NewFuture/DDNS#166]
## **Describe the bug [描述]**

是因为权限的问题吗？

### version info [基本信息]

* DDNS Version: 
* OS Version： 
* Type(运行方式): Binary/Python
* related issues (相关问题): 

### config file [配置文件]

```json
{
}
```

###  debug output [调试输出]

```sh
粘贴输出日志
paste out put here
```

**Additional context**

**Comment by NewFuture** [comment]
查查定时任务执行的log看看执行了没？

**Comment by leonhart118** [comment]
查了，没有执行记录。

**Comment by zhuziyi1989** [comment]
bug 真多，用了大半年，没一次自动执行成功过的...

**Comment by NostalgistL00** [comment]
> bug 真多，用了大半年，没一次自动执行成功过的...

如果是在linux用的话只要把文件放入/home目录下，然后写个.sh文件：
cd /home
/home/ddns
然后再用crontab设置定时任务就可以正常运行了。

**Comment by NostalgistL00** [comment]
如果写个bat文件先cd到当前目录在运行那个程序也许就好了吧

**Comment by Hoshiya233** [comment]
我在windows上的任务计划从来没成功过，在linux上就很容易。
新建一个.sh文件，添加两行代码：cd到源码目录下，python run.py
然后把上面的文件添加执行权限再配个计划任务就好了
