### ISSUE TITLE
[debug]  alidns 运行失败

### ISSUE THREAD

**Issue by hurongyang** [NewFuture/DDNS#167]
[ERROR] {"RequestId":"6A75109D-0D4C-4138-BED4-EE57A4ABEE50","HostId":"alidns.aliyuncs.com","Code":"Forbidden.RAM","Message":"User not authorized to operate on the specified resource, or this API doesn't support RAM."}

申请的 AccessKey ID 和 AccessKeySecret 使用阿里云 Python SDK 是可以添加解析的，但是此项目有以上报错

**Comment by NewFuture** [comment]
哪个API，是不是没有列出域名的权限？

**Comment by chenzhikang** [comment]
@hurongyang 
我也遇到了，通过RAM新建的帐号会提示这个。
我直接用主帐号的accesskey那套，就没问题了；

主账号accesskey查看链接：https://usercenter.console.aliyun.com/#/manage/ak

**Comment by Monsterstars** [comment]
@hurongyang 
感谢 @chenzhikang 提供的解决方法，确实能够解决问题。
但是主账号的accesskey泄露对帐户风险较大，可以在RAM控制台中，人员管理-用户，在刚在生成的accesskey右侧点击添加权限，在弹出的页面下侧系统策略中搜索dns，选择对应权限添加即可。
