### ISSUE TITLE
是否支持windows通过pppoe拨号获取到公网ip地址

### ISSUE THREAD

**Issue by cfyhbb** [NewFuture/DDNS#17]
你好！
我对python不太懂，看了ip.py里面的源码，对于获取windows 本机ip地址源码不太懂。
想问下如果windows主机有多个网卡或有pppoe拨号，程序能自动识别那个网卡是公网的ip地址吗？

**Comment by NewFuture** [comment]
直接设置成 public就行了
```
"index4": "publuc",
```
会自动获取公网出口的IP

**Comment by cfyhbb** [comment]
您说的方式确实可行，但是我的这里有多个动态的公网ip地址，就有个问题有时获取到的公网ip地址正确，有时候获取到的不对，导致访问不到应用。

**Comment by NewFuture** [comment]
是更新不及时？
你可以把定时任务的时间间隔调短一点

但是dns仍然会有缓存(免费的一般是10分钟)

**Comment by cfyhbb** [comment]
谢谢！
