### ISSUE TITLE
[feature]使用systemd的timer替代现有的corn任务计划模式

### ISSUE THREAD

**Issue by GoldJohnKing** [NewFuture/DDNS#174]
使用systemd的timer替代现有的corn任务计划模式。

现代Linux系统推荐使用systemd的timer来替代corn任务计划，因为它更加灵活可控，支持更多的功能，且管理比较集中。

使用systemd的timer方式执行任务，可以实现开机之后立即执行一次ddns操作，然后每隔一定时间就执行一次，也支持执行失败后自动执行其他操作，支持命令行随时启停和查询日志，更加方便。

样例如下：

`/etc/systemd/system/newfuture_ddns.service`
```
[Unit]
Description=NewFuture DDNS Service
Wants=network-online.target
After=network-online.target

[Service]
User=root
Type=simple
ExecStart=/root/newfuture_ddns/ddns -c /root/newfuture_ddns/config.json

[Install]
WantedBy=multi-user.target
```

`/etc/systemd/system/newfuture_ddns.timer`
```
[Unit]
Description=NewFuture DDNS Timer
Wants=network-online.target
After=network-online.target

[Timer]
OnStartupSec=30
OnUnitActiveSec=300

[Install]
WantedBy=timers.target
```

文件创建完成后，执行`systemctl enable newfuture_ddns.timer`和`systemctl start newfuture_ddns.timer`即可启动计时任务，执行`systemctl status newfuture_ddns`即可查询日志，非常方便。

因此，个人建议修改task.sh以增加此功能，并允许用户选择任务计划模式。

**Comment by NewFuture** [comment]
可以在这里https://github.com/NewFuture/DDNS/tree/master/.release 加一个   `create_task.systemd.sh` 来自动创建systemd的定时任务
