### ISSUE TITLE
[debug]关于每5分钟检查一次ip,自动更新

### ISSUE THREAD

**Issue by googooog** [NewFuture/DDNS#177]
在python环境设置后，默认每5分钟检查一次ip,自动更新。
但是只有第一个5分钟会自动在域名解析列表里添加动态的公网IP，以后每个5分钟都不会更新，是因为公网IP还没有变化么？

**Comment by EricMzky** [comment]
> 在python环境设置后，默认每5分钟检查一次ip,自动更新。
> 但是只有第一个5分钟会自动在域名解析列表里添加动态的公网IP，以后每个5分钟都不会更新，是因为公网IP还没有变化么？

如果你公网IP没变化自然不会变啊，就是为了实时解析绑定新的公网IP。你没有变化，就不会动。

**Comment by IZWB-003** [comment]
> 
> 
> > 在python环境设置后，默认每5分钟检查一次ip,自动更新。
> > 但是只有第一个5分钟会自动在域名解析列表里添加动态的公网IP，以后每个5分钟都不会更新，是因为公网IP还没有变化么？
> 
> 如果你公网IP没变化自然不会变啊，就是为了实时解析绑定新的公网IP。你没有变化，就不会动。

您好，请问程序的设计机制是这样的：
- 每五分钟检查一次IP地址
- 如果IP地址有变化，则调用服务商API更新地址
- 如果无变化则不进行任何操作
还是
- 无变化也调用服务商API更新一个相同的地址
这样的？

**Comment by NewFuture** [comment]
@izwb003 如果和上次更新的ip地址一样则跳过更新，避免重复调用。
可以把`cache` 设为 `false`强制更新。

**Comment by googooog** [comment]
谢谢，明白了

**Comment by zcyoop** [comment]
> @izwb003 如果和上次更新的ip地址一样则跳过更新，避免重复调用(输出日志为打点`.`)。
> 可以把`cache` 设为 `false`强制更新。

你好，可以这个加到文档定时任务那一块嘛，我查看日志全是`..`还以为哪出问题了，还来翻了翻issue

**Comment by NewFuture** [comment]
@zcyoop  欢迎提个PR更新一下readme
