### ISSUE TITLE
为什么同样的配置文件在CentOS8上面就是invalid domain

### ISSUE THREAD

**Issue by NostalgistL00** [NewFuture/DDNS#178]
RT，同样的配置文件在Ubuntu 19.10上面可以用，Windows10上面可以用，但是在CentOS8.1.1911就显示invalid domain 呢。。

**Comment by NostalgistL00** [comment]
我枯了，网盘就差一步DDNS了。。

**Comment by NewFuture** [comment]
确定确认配置文件的域名是一样的？

**Comment by NostalgistL00** [comment]
> 确定确认配置文件的域名是一样的？

确实是啊， 我在虚拟机上的CentOS8和实体机上的都显示invalid domain，Windows和Ubuntu 19就好用。

**Comment by NostalgistL00** [comment]
> 确定确认配置文件的域名是一样的？
我还是直接在Windows下测试过直接把配置文件内容复制过去的也不行

**Comment by NewFuture** [comment]
配置和 debug log 打出来看看

**Comment by NostalgistL00** [comment]
> 配置和 debug log 打出来看看
DDNS[ v2.9.2@2020-03-30T12:42:47+00:00 ] run: posix linux
Configuration was loaded from <== /home/nostalgistl00/config.json
========================= Thu Jun  4 11:17:39 2020 =========================
2020-06-04 11:17:39,928 <cache.load> 48@util/cache.py 
[DEBUG] load cache data from /tmp/ddns.cache
2020-06-04 11:17:39,929 <ip.local_v4> 45@util/ip.py 
[DEBUG] [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('127.0.0.1', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('127.0.0.1', 0))]

test.nostalgistl00.plus(A) ==> 127.0.0.1 [via DIRECT]
2020-06-04 11:17:39,930 <dnspod.update_record> 151@dns/dnspod.py 
[INFO] >>>>>test.nostalgistl00.plus(A)
2020-06-04 11:17:39,930 <dnspod.request> 47@dns/dnspod.py 
[INFO] dnsapi.cn/Domain.Info : {'domain': 'nostalgistl00.plus', 'login_token': '***', 'format': 'json'}
2020-06-04 11:17:40,043 <dnspod.request> 47@dns/dnspod.py 
[INFO] dnsapi.cn/Domain.Info : {'domain': 'test.nostalgistl00.plus', 'login_token': '***', 'format': 'json'}
2020-06-04 11:17:40,156 <dnspod.get_domain_info> 91@dns/dnspod.py 
[INFO] domain_id: None, sub: None
2020-06-04 11:17:40,156 <run.change_dns_record> 120@run.py 
[ERROR] invalid domain: [ test.nostalgistl00.plus ] 
2020-06-04 11:17:40,156 <ip.local_v6> 39@util/ip.py 
[DEBUG] [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_RAW: 3>, 0, '', ('::1', 0, 0, 0))]

pan.nostalgistl00.plus(AAAA) ==> ::1 [via DIRECT]
2020-06-04 11:17:40,156 <dnspod.update_record> 151@dns/dnspod.py 
[INFO] >>>>>pan.nostalgistl00.plus(AAAA)
2020-06-04 11:17:40,156 <dnspod.request> 47@dns/dnspod.py 
[INFO] dnsapi.cn/Domain.Info : {'domain': 'nostalgistl00.plus', 'login_token': '***', 'format': 'json'}
2020-06-04 11:17:40,269 <dnspod.request> 47@dns/dnspod.py 
[INFO] dnsapi.cn/Domain.Info : {'domain': 'pan.nostalgistl00.plus', 'login_token': '***', 'format': 'json'}
2020-06-04 11:17:40,381 <dnspod.get_domain_info> 91@dns/dnspod.py 
[INFO] domain_id: None, sub: None
2020-06-04 11:17:40,381 <run.change_dns_record> 120@run.py 
[ERROR] invalid domain: [ pan.nostalgistl00.plus ]

**Comment by xufan6** [comment]
我也出现类似情况，CentOS 7.8.2003 二进制ddns v2.9.2
现象是主域名没有取到，直接去子域名了，子域名没有记录最终失败
怀疑为47@dns/dnspod.py 前后的问题，与前一个日志中现象基本一致。

**Comment by xufan6** [comment]
> 我也出现类似情况，CentOS 7.8.2003 二进制ddns v2.9.2
> 现象是主域名没有取到，直接去子域名了，子域名没有记录最终失败
> 怀疑为47@dns/dnspod.py 前后的问题，与前一个日志中现象基本一致。
> 
> 用源码运行run.py没有问题（系统Python 2.7.5）

根本原因应该还是issue #63 的CA证书问题，在index4的步骤里如果设置了其他获取方式（不走https请求），在 dns/dnspod.py get_domain_id 把错误包住了，即会出现如上现象。

**Comment by NostalgistL00** [comment]
> 我也出现类似情况，CentOS 7.8.2003 二进制ddns v2.9.2
> 现象是主域名没有取到，直接去子域名了，子域名没有记录最终失败
> 怀疑为47@dns/dnspod.py 前后的问题，与前一个日志中现象基本一致。
> 
> 用源码运行run.py没有问题（系统Python 2.7.5）

确实源码运行没有问题，谢谢

**Comment by xufan6** [comment]
fixed in #201
