### ISSUE TITLE
cloudflare 不成功，不知那里问题？

### ISSUE THREAD

**Issue by ck932** [NewFuture/DDNS#180]
我是用  raspberry pi 3B+, buster os, 更新 cloudflare 不成功，不知哪里问题？ 

config.json 如下：
```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": false,
  "dns": "cloudflare",
  "id": null,
  "index4": 5,
  "index6": "public",
  "ipv4": [
    "ddns.newfuture.cc",
    "ipv4.ddns.newfuture.cc"
  ],
  "ipv6": [
    "ddns.newfuture.cc",
    "ipv6.ddns.newfuture.cc"
  ],
  "proxy": "127.0.0.1:1080;DIRECT",
  "token": "mZM3IjcLGp_2O7tF",
  "ttl": 600
}
```
之后，运行：
$ python run.py -c /DDNS-2.9.2/config.json

结果如下：
```
WARNING:root:Cache file is out of dated.
Traceback (most recent call last):
  File "run.py", line 190, in <module>
    main()
  File "run.py", line 185, in main
    update_ip('4', cache, dns, proxy_list)
  File "run.py", line 132, in update_ip
    address = get_ip(ip_type)
  File "run.py", line 90, in get_ip
    value = getattr(ip, "local_v" + ip_type)(index)
  File "/home/tim813/DDNS-2.9.2/util/ip.py", line 46, in local_v4
    return info[int(i)][-1][0]
IndexError: list index out of range
```
请问哪里出问题，先谢过 :-)

**Comment by NewFuture** [comment]
`·"index4": 5,`

有这么多网卡？

**Comment by ck932** [comment]
你好，

问题 "index4": 5, 已经改为 0。

再运行后，发生以下问题：

 sudo python run.py -c /DDNS-2.9.2/config.json
WARNING:root:Cache file is out of dated.

ck32.cf(A) ==> 127.0.1.1 [via 127.0.0.1:1080]
WARNING:root:/531c4b5a280a0dfaca3727e8acf5a4cd/dns_records/d0f4e2445f5eed91c32961f96666c12b : error[401]:{
  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
}

ERROR:root:{
  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
}


ck32.cf(A) ==> 127.0.1.1 [via DIRECT]
WARNING:root:/531c4b5a280a0dfaca3727e8acf5a4cd/dns_records/d0f4e2445f5eed91c32961f96666c12b : error[401]:{
  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
}

ERROR:root:{
  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
}


ipv4.ck32.cf(A) ==> 127.0.1.1 [via 127.0.0.1:1080]
WARNING:root:/531c4b5a280a0dfaca3727e8acf5a4cd/dns_records : error[401]:{
  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
}

ERROR:root:{
  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
}


ipv4.ck32.cf(A) ==> 127.0.1.1 [via DIRECT]
WARNING:root:/531c4b5a280a0dfaca3727e8acf5a4cd/dns_records : error[401]:{
  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
}

ERROR:root:{
  "error": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
}

ERROR:root:'NoneType' object has no attribute 'group'
ERROR:root:Fail to get ipv6 address!

请问如何解决，谢谢！

**Comment by NewFuture** [comment]
> You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard

Cloudflare  不支持免费域名 调用这个API修改域名解析

**Comment by ck932** [comment]
明白了，谢谢耐心解答。:-)
