### ISSUE TITLE
这个ddns 在docker上怎么安装？

### ISSUE THREAD

**Issue by xinqinglhj** [NewFuture/DDNS#182]
本人初次使用docker部署软件，想请教一下，在docker上怎么安装？怎么设置？
有提供docker上 安装吗？

**Comment by xinqinglhj** [comment]
armbian上完美使用。

**Comment by xinqinglhj** [comment]
我最后还是在小钢炮上，直接部署了，没有通过docker。在docker里搜索到一个其他版本的不适用，倒是可以自己做个。

**Comment by ldxw** [comment]
可以套娃？在docker里用源码安装？

**Comment by NewFuture** [comment]
两个方案

1. docker 上配上python环境运行
2. docker 上把源码编译成二进制的，在build一个dockers来运行

docker版 读取本地地址/网卡地址 可嫩取出来的是docker的网络ip 这个方式不能用

**Comment by NN708** [comment]
我试了一下，在运行容器时使用 `--network host` 可以使容器正常获得宿主机的 IP 地址。

**Comment by NewFuture** [comment]
可以试试 https://hub.docker.com/r/newfuture/ddns
thank @NN708
