### ISSUE TITLE
[debug] 尝试使用公网ip时出错

### ISSUE THREAD

**Issue by avesed** [NewFuture/DDNS#183]
## **To Reproduce [复现]**
version info [基本信息]

* DDNS Version: 2.9.2
* OS Version： Ubuntu 20.04LTS
* Type(运行方式): Python3.8.2
* related issues (相关问题): 尝试使用公网ip时出错

config file [配置文件]

```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": false,
  "dns": "cloudflare",
  "id": "id",
  "index4": "pubilc",
  "index6": "pubilc",
  "ipv4": [
    "d.0wn.xin "
  ],
  "ipv6": [
  ],
  "proxy": null,
  "token": "token",
  "ttl": null
}
```

debug output [调试输出]

```
2020-06-13 12:21:15,721 <run.main> 183@run.py
[WARNING] Cache file is out of dated.
Traceback (most recent call last):
  File "run.py", line 190, in <module>
    main()
  File "run.py", line 185, in main
    update_ip('4', cache, dns, proxy_list)
  File "run.py", line 132, in update_ip
    address = get_ip(ip_type)
  File "run.py", line 103, in get_ip
    value = getattr(ip, index + "_v" + ip_type)()
AttributeError: 'module' object has no attribute 'pubilc_v4

**Comment by avesed** [comment]
尝试直接用url获取ip出现以下报错

[ERROR] {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}

**Comment by NewFuture** [comment]
似乎是id,token配置问题

**Comment by avesed** [comment]
emm，刚在虚拟机里测试了一下，同样的配置文件可以用....
不过虚拟机是Ubuntu 18.04LTS

**Comment by nino-James** [comment]
我有同样的问题，
./ddns 
WARNING:root:Cache file is out of dated.
Traceback (most recent call last):
  File "run.py", line 190, in <module>
  File "run.py", line 186, in main
  File "run.py", line 132, in update_ip
  File "run.py", line 103, in get_ip
AttributeError: module 'util.ip' has no attribute 'eno1_v6'
[28575] Failed to execute script run
系统版本：
Linux version 5.6.0-0.bpo.2-amd64 (debian-kernel@lists.debian.org) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP Debian 5.6.14-2~bpo10+1 (2020-06-09) omv 5.3.9
