### ISSUE TITLE
貌似有内存泄漏的BUG

### ISSUE THREAD

**Issue by PHCSJC** [NewFuture/DDNS#185]
ddns是python版本的，版本是2.9.2
操作系统是debian10 x64。
计划任务的命令是：
*/6 * * * * su - -c 'timeout 60 ddns -c /etc/ddns.cf.conf >/dev/null 2>&1 &'

配置文件是：
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.json", 
  "dns": "cloudflare", 
  "id": "*********", 
  "token": "*********",
  "index4": "url:http://myip.ipip.net/s", 
  "index6": "default", 
  "ipv4": ["*********"],
  "ipv6": [],
  "ttl": 120,
  "cache": false
}

发现操作系统的内存在不断减少，每几分钟减少一次，每次大概减少1-3M，包括晚上凌晨，top和ps命令里都看不出是哪个进程占的。

我把几乎所有应用全部关闭还是在不断减少，apt update升级到最新还是不行。
发现把ddns的计划任务关闭后好像可以了，不再减少了。

目前情况是这样的，不知道大佬有什么好的建议吗？或者需要什么其它的信息吗？

**Comment by PHCSJC** [comment]
又测试了一天bin版本，没有这个问题。

**Comment by PHCSJC** [comment]
又跑了2天bin版本的，未发现内存减少的问题。

**Comment by NewFuture** [comment]
这个程序更新完就完全退出了，占用空间会全释放，即使内存泄漏也应该不会持续占用，

**Comment by PHCSJC** [comment]
> 这个程序更新完就完全退出了，占用空间会全释放，即使内存泄漏也应该不会持续占用，

那就不清楚了，目前我发现的情况就这样，我先关了issue吧。
