### ISSUE TITLE
提示无法执行的二进制文件以及添加定时任务脚本无效

### ISSUE THREAD

**Issue by nino-James** [NewFuture/DDNS#191]
今天遇到的很玄学的问题，使用的openmediavault的最新系统基于debian，之前ddns二进制文件是可以正常执行，但是定时脚本无效（crontab -l 没有，同时查看日志没有执行记录），尝试手动添加一直报错（我是小白cron还不会用，百度了一些都不行），想先手动更新一下执行了 .  ddns,结果提示-bash: .: /root/ddns/ddns：无法执行二进制文件，尝试重新安装系统，依旧如此，不知道什么问题（执行权限已给，root执行），主要是曾经正常使用过突然这样，各位朋友有遇到过类似问题的嘛，还请不吝赐教。

**Comment by NostalgistL00** [comment]
直接加入crontab确实不好用，你可以试试写个shell（我也不懂是不是叫这个）：
cd /home/(用户名)/DDNS
/home/(用户名)/DDNS/ddns

里面的内容就是切换到DDNS的目录，然后再输入完整目录+文件名，然后再crontab里面加入这个.sh文件就可以了

**Comment by NewFuture** [comment]
似乎文件是路径不对

**Comment by nino-James** [comment]
omv系统又被我搞崩了（悲惨世界），今天又重新做了一次，非常幸运的是这次的二进制文件可以成功执行，然而使用定时脚本创建定时任务依旧失败，我执行了以下命令;
```
root@maiden:~# ls -l /etc/cron.d
总用量 36
-rw-r--r-- 1 root root 285 5月  19  2019 anacron
-rw-r--r-- 1 root root 355 6月  20  2018 cron-apt
-rw-r--r-- 1 root root  77 8月   2 02:15 ddns
-rw-r--r-- 1 root root 201 1月  26  2020 e2scrub_all
-rw-r--r-- 1 root root 589 1月  16  2019 mdadm
-rw-r--r-- 1 root root 126 3月  26 00:22 openmediavault-mkrrdgraph
-rw-r--r-- 1 root root 257 8月   2 02:08 openmediavault-powermngmt
-rw-r--r-- 1 root root 257 8月   2 02:13 openmediavault-userdefined
-rw-r--r-- 1 root root 712 12月 17  2018 php
root@maiden:~# cat /etc/cron.d/ddns 
*/5 * * * *   root    "/root/ddns" -c "/root/config.json" >> "/root/run.log"
root@maiden:~# cat run.log 
root@maiden:~# crontab -l
no crontab for root
```
间隔10分钟后查看日志依旧没有输出，随后我通过wen-ui界面成功添加定时任务，查看crontab 依旧没有记录（但是任务被成功执行）可能是omv系统问题，上次采用docker临时解决了这个问题，感谢两位提出的建议，谢谢！！
