### ISSUE TITLE
WARNING: root: Cache file is out of dated.

### ISSUE THREAD

**Issue by QQ10709289** [NewFuture/DDNS#192]
![IMG_20200803_123233](https://user-images.githubusercontent.com/24466200/89146138-6d56e780-d585-11ea-88fd-75130d3f9d22.jpg)

**Comment by QQ10709289** [comment]
这个怎么解决，树莓派Ubuntu20.04lts

**Comment by NewFuture** [comment]
这个没有问题，就是缓存失效的提示

**Comment by QQ10709289** [comment]
是不是必须要用root用户才能执行，管理员通过，sudo ddns不行吗？

**Comment by NewFuture** [comment]
修改配置文件或者缓存到期，缓存文件都会失效，然后会重新生成。这个不影响
