### ISSUE TITLE
怎么绑定内网IP?

### ISSUE THREAD

**Issue by winniesi** [NewFuture/DDNS#2]
抱歉，看了一下配置说明，没有看到怎么绑定内网IP。

**Comment by NewFuture** [comment]
如果是单网卡的话
`index4`(使用ipv4)或者`index6`(使用ipv6)不设置(默认default)或者设置为`lcoal`就行了
具体配置

* `default`: 发送网络数据包，局域网中通常是内网IP
* `local`: 系统拿到的本机IP(一般是内网IP)
* `public`: 公网IP，访问公网对应的出口，一定是外网IP

**Comment by winniesi** [comment]
感谢！
