### ISSUE TITLE
请问docker下安装的话，已经默认开启了定时任务更新ddns吗？

### ISSUE THREAD

**Issue by wnark** [NewFuture/DDNS#204]
我直接使用`docker run -d -v /path/to/config.json:/config.json --network host newfuture/ddns`命令成功运行了ddns,还需要我设置定时任务自动重启docker容器来更新ddns吗

**Comment by NN708** [comment]
不需要，Docker image 中包含了每 5 分钟自动更新。

**Comment by wnark** [comment]
好的，谢谢

**Comment by JiangLongLiu** [comment]
> 好的，谢谢

请问如何修改默认的5分钟为1分钟更新？

**Comment by NN708** [comment]
> > 好的，谢谢
> 
> 请问如何修改默认的5分钟为1分钟更新？

你可以修改 Docker 容器中的 `/etc/crontabs/root` 文件，将 `*/5 * * * *   /ddns -c /config.json` 改为 `*/1 * * * *   /ddns -c /config.json`。
