### ISSUE TITLE
[debug]今天下午不能自动更新

### ISSUE THREAD

**Issue by googooog** [NewFuture/DDNS#205]
你好，今天下午不能自动更新了，debug模式怎么可以输出？已经选择是ture了，用的小钢炮添加这个命令：*/5 * * * * python /root/ddns/run.py 之前一直很好用。原谅我是小白……

我重新配置了下文件，还是不自动更新
{
	"$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
	"id": "------",
	"token": "-----------------------",
	"dns": "dnspod",
	"ipv4": [
		"*.------.top",
		"*.-----.------.net"
	],
	"index4": "default",
	"index6": "default",
  	"ttl": null,
	"proxy": "DIRECT",
	"debug": true
        "cache": true
}

**Comment by NewFuture** [comment]
直接运行脚本，就能看到输出。

正常了么？
