### ISSUE TITLE
[debug]为啥运行过一次后，后面就不能再执行了，改过配置文件又能执行了。。。

### ISSUE THREAD

**Issue by skyshinekube** [NewFuture/DDNS#213]
为啥运行过一次后，后面就不能再执行了，改过配置文件又能执行了。。。

然后返回记录是一个.

**Comment by NewFuture** [comment]
IP 没有变化

**Comment by skyshinekube** [comment]
我手动改了阿里云的解析记录值。。。然后运行还是一个.

**Comment by NewFuture** [comment]
这个每次检测的是本机的ip变化。

可以把缓存文件删了(修改配置文件会使缓存失效)，再次更新。

如果不想 可以把`cache`设为false 关掉缓存

**Comment by skyshinekube** [comment]
感谢，已经解决啦！
