### ISSUE TITLE
windows 系统的病毒防护总是杀ddns.exe

### ISSUE THREAD

**Issue by schmiloo** [NewFuture/DDNS#214]
为什么windows 系统的病毒防护总是杀ddns.exe, 大家都这样吗？

**Comment by lirener** [comment]
我没有用win10自带的杀毒软件
使用的版本号是：DDNS-2.7.2
火绒查杀没有问题……

**Comment by CongAn** [comment]
360这边拦截它写 `C:\Windows\Temp\_MEI75642\ucrtbase.dll` 文件，搜索了下项目源码好像没有`ucrtbase`字样……

**Comment by NewFuture** [comment]
在线扫了一下 [v2.9.8](https://github.com/NewFuture/DDNS/releases/tag/v2.9.8) 的 exe 没问题了

https://www.virustotal.com/gui/url/cde400abac54aef5f3ff60231cc405c8f686b184acdb16cf813da246da9df411/detection
