### ISSUE TITLE
[debug]  运行ddns失败

### ISSUE THREAD

**Issue by ShawnQiang1** [NewFuture/DDNS#218]
系统是armbian
使用pip3 install ddns安装 ddns 
运行一次ddns后再次运行时出现如下问题，且无法更新本机ip至阿里云DNS
![TEXT](https://i.loli.net/2021/01/23/upOdTsZ4gFEVtIz.png)

**Comment by NewFuture** [comment]
正常的，这个和上次运行时的ip地址一样没有变化。跳过更新了
