### ISSUE TITLE
Cloud flare 根域名判断和ZoneID获取

### ISSUE THREAD

**Issue by NewFuture** [NewFuture/DDNS#22]
https://github.com/NewFuture/DDNS/blob/c94fe05c699b423843932ccbc5b1aed29c4b1fed/dns/cloudflare.py#L68-L78

@tongyifan 
这里判定根域名是有问题的,
常见的根域名可能是三级的如`domain.net.cn` 这个会无法解析

https://api.cloudflare.com/#zone-list-zones

Cloud Flare的API可以**一次拉取整个List**(max=50):
1. 遍历整个List(数组)
2. 逐个name检查是否满足`domain.endswith(name)`
3.  满足条件即为所查找的ID

修改代码
```python
zones = request('GET', '', per_page=50) 
zone = next((z for z in zones if domain.endswith(z.get('name'))), None)
zoneid = zone and zone['id']
```
@tongyifan 有空测试验证一下

**Comment by tongyifan** [comment]
哎呀写了bug  QAQ最近被课设折磨的欲仙欲死没有跟进问题，真的真的非常抱歉
