### ISSUE TITLE
[feature] 支持从环境变量读取配置

### ISSUE THREAD

**Issue by shuosiw** [NewFuture/DDNS#220]
**Is your feature request related to a problem? Please describe.**
使用 docker 方式运行，还需要准备配置文件挂载到容器内部，稍微麻烦，希望支持读取环境变量配置

**Describe the solution you'd like**
支持启动时读取环境变量，而不是强制要求 config.json

**Describe alternatives you've considered**
如上

**Additional context**
无

**Comment by NewFuture** [comment]
嗯，这个feature 确实需要

**Comment by shuosiw** [comment]
> 嗯，这个feature 确实需要

可以可以，加油~

**Comment by shuosiw** [comment]
@NewFuture 我通过配置渲染的方式临时支持了从环境变量进行渲染：https://github.com/shuosiw/NFddns

并且提供了 unraid 的模板，在 unraid 上使用会变得非常简单：

![image](https://user-images.githubusercontent.com/2578976/116269152-8c02ab80-a7b0-11eb-8f3e-5f45d552ac6f.png)

![image](https://user-images.githubusercontent.com/2578976/116269708-05020300-a7b1-11eb-8d67-f5ce69269b81.png)

**Comment by NewFuture** [comment]
#269  这个PR支持从环境变量读取配置，可以用这个分支体验下
