### ISSUE TITLE
[debug] Failed to execute script run,socket.gaierror: [Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by q123458384** [NewFuture/DDNS#230]
### version info [基本信息]

* DDNS Version: 
* OS Version： 
* Type(运行方式): docker
* related issues (相关问题): 

### config file [配置文件]
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "id": "LTAI********",
  "token": "Vdy**********",
  "dns": "alidns",
  "ipv4": ["***"],
  "ipv6": ["****"],
  "index4": 0,
  "index6": "public",
  "ttl": 600,
  "proxy": "DIRECT",
  "cache": true,
  "debug": false
}
```json
{
}
```

###  debug output [调试输出]

```sh
crond[1]: crond (busybox 1.32.1) started, log level 8
crond[1]: USER root pid   6 cmd /ddns -c /config.json
Traceback (most recent call last):
  File "run.py", line 199, in <module>
  File "run.py", line 194, in main
  File "run.py", line 139, in update_ip
  File "run.py", line 96, in get_ip
  File "util/ip.py", line 44, in local_v4
  File "socket.py", line 745, in getaddrinfo
socket.gaierror: [Errno -2] Name does not resolve
[7] Failed to execute script run
```

**Additional context**

**Comment by moyongshi** [comment]
你没有添加域名，而且可能没有成功获取公网IP
```json
{
  "id": "Access Key Id",
  "token": "Secret Access Key",
  "dns": "huaweidns",
  "ipv4": ["域名（不包含http，如：ddns.newfuture.cc）"],
  "index4": "public",
  "ttl": 600,
  "debug": true
}
```

**Comment by q123458384** [comment]
> 你没有添加域名，而且可能没有成功获取公网IP
> 
> ```json
> {
>   "id": "Access Key Id",
>   "token": "Secret Access Key",
>   "dns": "huaweidns",
>   "ipv4": ["域名（不包含http，如：ddns.newfuture.cc）"],
>   "index4": "public",
>   "ttl": 600,
>   "debug": true
> }
> ```

发现问题了~需要在域名解析那先手动添加一条记录
