### ISSUE TITLE
请问如何区分子域名和跟域名呢

### ISSUE THREAD

**Issue by wbdosx** [NewFuture/DDNS#24]
使用子域名总提示不存在 谢谢
ddns.exe
========================= Wed Sep 26 15:02:33 2018 =========================
s.fpga.net.cn(A) ==> 202.105.47.131 [via DIRECT]
{u'message': u'Domain name invalid, please input tld domain', u'code': u'8', u'created_at': u'2018-09-26 15:02:32'}

**Comment by NewFuture** [comment]
DNS服务商是什么?
方便的话贴一下配置(** id 和 token 去掉 **)

**Comment by wbdosx** [comment]
谢谢啦 后来突然就好了 不知道是不是DNSPot的问题

**Comment by NewFuture** [comment]
好的，close了

**Comment by Argon-Pub** [comment]
我遇到了同样的问题，DNSPod（国内版）
```conf
{
  "$schema": "https://ddns.newfuture.cc/schema.json",
  "debug": false,
  "dns": "dnspod",
  "id": "[已隐藏]",
  "index4": "false",
  "index6": "default",
  "ipv4": [
  ],
  "ipv6": [
    "raspi3.home.pubs.net.cn",
    "raspi3.home.ipv6.pubs.net.cn"
  ],
  "proxy": null,
  "token": "[已隐藏]"
}
```
且，使用AliDNS时同样的配置没有出现问题。
——
作者的Debug功能输出的信息太少了，让人无从判断。希望能在Debug开启时输出更多的信息（比如域名分割的情况）。
另外，假如提供可选的配置项，让用户自行填写一级域名和子域名，就更好了。

**Comment by NewFuture** [comment]
@Argon-Pub 你运行一下最新的代码 #30 ，打开debug看看。这个会有较详细的输出。

> 另外，假如提供可选的配置项，让用户自行填写一级域名和子域名，就更好了。

将子域名和根域名分开实现最简单，但是对于配置者不太友好,
对于使用者不要求知道什么是`根域名`什么是`子域名`
这里会从短到长自动判断和截取

**Comment by Argon-Pub** [comment]
```console
➜  DDNS git:(master) ✗ cat ./config2.json
{
  "$schema": "https://ddns.newfuture.cc/schema.json",
  "debug": true,
  "dns": "dnspod",
  "id": "[已隐藏]",
  "index4": "false",
  "index6": "default",
  "ipv4": [
  ],
  "ipv6": [
    "raspi3.home.argon.org.cn",
    "raspi3.home.ipv6.argon.org.cn"
  ],
  "proxy": null,
  "token": "[已隐藏]"
}
➜  DDNS git:(master) ✗ python run.py -c ./config2.json
raspi3.home.argon.org.cn(AAAA) ==> 2604:6600:0:e::7a18:bf2f [via DIRECT]
{u'message': u'Domain name invalid, please input tld domain', u'code': u'8', u'created_at': u'2018-12-23 13:32:05'}
raspi3.home.ipv6.argon.org.cn(AAAA) ==> 2604:6600:0:e::7a18:bf2f [via DIRECT]
{u'message': u'Domain name invalid, please input tld domain', u'code': u'8', u'created_at': u'2018-12-23 13:32:05'}
➜  DDNS git:(master) ✗ git pull
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 23 (delta 16), reused 23 (delta 16), pack-reused 0
Unpacking objects: 100% (23/23), done.
From https://github.com/NewFuture/DDNS
   4679a78..09b9571  master     -> origin/master
Updating 4679a78..09b9571
Fast-forward
 dns/alidns.py     | 20 ++++++++++----------
 dns/cloudflare.py |  8 ++++----
 dns/dnscom.py     | 19 ++++++++++---------
 dns/dnspod.py     | 10 +++++-----
 dns/dnspod_com.py |  8 ++++----
 run.py            | 15 ++++++++++-----
 util/cache.py     | 17 ++++++++---------
 util/ip.py        | 24 ++++++++++--------------
 8 files changed, 61 insertions(+), 60 deletions(-)
➜  DDNS git:(master) ✗ python run.py -c ./config2.json
2018-12-23 05:33:55,906 - cache.load - 46@/home/pi/DDNS/util/cache.py
[DEBUG] load cache data from /tmp/ddns.cache

raspi3.home.argon.org.cn(AAAA) ==> 2604:6600:0:e::7a18:bf2f [via DIRECT]
2018-12-23 05:33:55,909 - dnspod.update_record - 141@/home/pi/DDNS/dns/dnspod.py
[DEBUG] >>>>>raspi3.home.argon.org.cn(AAAA)
2018-12-23 05:33:55,909 - dnspod.request - 38@/home/pi/DDNS/dns/dnspod.py
[DEBUG] Domain.Info : params:{'domain': u'org.cn', 'login_token': u'[已隐藏],[已隐藏]', 'format': 'json'}
{u'message': u'Domain name invalid, please input tld domain', u'code': u'8', u'created_at': u'2018-12-23 13:33:56'}

raspi3.home.ipv6.argon.org.cn(AAAA) ==> 2604:6600:0:e::7a18:bf2f [via DIRECT]
2018-12-23 05:33:56,299 - dnspod.update_record - 141@/home/pi/DDNS/dns/dnspod.py
[DEBUG] >>>>>raspi3.home.ipv6.argon.org.cn(AAAA)
2018-12-23 05:33:56,299 - dnspod.request - 38@/home/pi/DDNS/dns/dnspod.py
[DEBUG] Domain.Info : params:{'domain': u'org.cn', 'login_token': u'[已隐藏],[已隐藏]', 'format': 'json'}
{u'message': u'Domain name invalid, please input tld domain', u'code': u'8', u'created_at': u'2018-12-23 13:33:56'}
➜  DDNS git:(master) ✗
```
根据报错，应该是域名分割出了问题。

**Comment by NewFuture** [comment]
@Argon-Pub  这里在第一次检查时直接跳出了，最新的应该修复了这个问题

**Comment by Argon-Pub** [comment]
是的，问题已解决。

**Comment by Xuan0318** [comment]
遇到了一样的问题，不知道是不是域名分割的问题，请教一下谢谢
`{
  "$schema": "https://ddns.newfuture.cc/schema/v2.json",
  "debug": true,
  "dns": "dnspod",
  "id": "隐藏",
  "index4": "public",
  "index6": "public",
  "ipv4": [
    "nas.unzsw.ac.nz"
  ],
  "ipv6": [
  ],
  "proxy": null,
  "token": "隐藏"
}`
然后输出的debug内容是这样的：
`2019-07-23 10:40:23,020 <run.main> 155@run.py
[INFO] DDNS[${BUILD_SOURCEBRANCHNAME}@${BUILD_DATE}] run: posix,linux2
2019-07-23 10:40:23,021 <cache.load> 48@/volume2/SEAGATE160G_1/DDNS/DDNS-master/util/cache.py
[DEBUG] load cache data from /tmp/ddns.cache
========================= Tue Jul 23 10:40:23 2019 =========================

nas.unzsw.ac.nz(A) ==> 125.36.37.109 [via DIRECT]
2019-07-23 10:40:23,834 <dnspod.update_record> 145@/volume2/SEAGATE160G_1/DDNS/DDNS-master/dns/dnspod.py
[INFO] >>>>>nas.unzsw.ac.nz(A)
2019-07-23 10:40:23,834 <dnspod.request> 38@/volume2/SEAGATE160G_1/DDNS/DDNS-master/dns/dnspod.py
[INFO] Domain.Info : params:{'domain': u'ac.nz', 'login_token': '***', 'format': 'json'}
2019-07-23 10:40:24,216 <dnspod.request> 58@/volume2/SEAGATE160G_1/DDNS/DDNS-master/dns/dnspod.py
[DEBUG] Domain.Info : result:{u'status': {u'message': u'Domain name invalid, please input tld domain', u'code': u'8', u'created_at': u'2019-07-23 10:40:24'}}
2019-07-23 10:40:24,216 <run.change_dns_record> 107@run.py
[ERROR] {u'message': u'Domain name invalid, please input tld domain', u'code': u'8', u'created_at': u'2019-07-23 10:40:24'}
2019-07-23 10:40:24,217 <cache.sync> 85@/volume2/SEAGATE160G_1/DDNS/DDNS-master/util/cache.py
[DEBUG] save cache data to /tmp/ddns.cache`

**Comment by Argon-Pub** [comment]
@Xuan0318 看起来确实是域名分割的问题。另外，建议贴报错信息时，使用
````
```console
你的DEBUG信息
```
````
通常会好看一些。

**Comment by Xuan0318** [comment]
@Argon-Pub  谢谢，确实好看了。感觉和DNS运营商api的list有关，这种不常见根域名往往会出问题。

**Comment by NewFuture** [comment]
@Xuan0318 这是个BUG

https://github.com/NewFuture/DDNS/blob/5400a41049859e1280406f6c0502fa72eab5bdad/dns/dnspod.py#L104

这个地方处理的有问题，
status不成功request会抛出exception

这应该要try catch (返回空).

可以改一下试试，方便的话提一个PR fix 一下 😄

**Comment by Argon-Pub** [comment]
@Xuan0318 你用的是 DNSPod ，可以在 `./dns/dnspod.py:67` 看到 `get_domain_info(domain)` 这个函数，其实还有改进的空间。思路暂略，容后PR。

**Comment by Argon-Pub** [comment]
@NewFuture 我的打算是在项目里整合 [PublicSuffix](https://github.com/publicsuffix) 你觉得这会是一个好主意吗？

**Comment by NewFuture** [comment]
> @NewFuture 我的打算是在项目里整合 [PublicSuffix](https://github.com/publicsuffix) ，你觉得这会是一个好主意吗？

是指用这个list https://publicsuffix.org/list/public_suffix_list.dat 来判断主域名吗？

**Comment by Argon-Pub** [comment]
@NewFuture
是的。不过可能没必要自己造轮子。
有现成的 Python 包可以代替 `get_domain_info(domain)` 这个函数。

**Comment by NewFuture** [comment]
@Argon-Pub  这个可能不太妥，可能忽略了一种场景，

>  我有一个域名`mydomain.com` （根域名就是 `mydomain.com`）这个的NS记录指向 aliyun域名解析
> 但是子域名 `global.mydomain.com` 这个的所有子域在dnspodcom
上管理，即这个NS记录指向dnspod.com的域名解析解析(付费版可以绑定子域名或者多级域名解析)
>
> 这个时候更新的dnspod上的记录`xxx.global.mydomain.com`和`ipv4.xxx.global.mydomain.com`，对应的根域名其实是`global.mydomain.com`而不是`mydomain.com`

所以这里采用逐级查询的方法来确定实际的根域名

**Comment by Argon-Pub** [comment]
@NewFuture
确实我忽略了这种场景。
那么换一种思路，使用 `Domain.List` 获取当前 DnsPod 账号下的所有域名项，如何？想来其他 DNS 服务商都会提供相似的接口。之后的动作就不过是在这个得到的列表里寻找一个匹配完整域名的项了。
另外考虑到你说的这种“账号下只有次级域名NS记录”的情况，目前匹配域名的函数时是不是应该从长到短匹配？

**Comment by NewFuture** [comment]
@Argon-Pub  是的，从长到短更准确，
list是可以的但是要考虑分页

**Comment by Xuan0318** [comment]
@NewFuture 本人比较菜，没有编程基础，改了下不行，靠大佬们了。我换成阿里dns就可以了。
   ```console else:
       try
       {
        info = request('Domain.Info', domain=domain)
        did = info.get("domain", {}).get("id")
                if did:
                    get_domain_id.domain_list[domain] = did
                    return did
        }
       catch()
       {}

**Comment by NewFuture** [comment]
等我有空更新一下

**Comment by NewFuture** [comment]
新开了一个issue #69 来track
