### ISSUE TITLE
[feature] 希望加入路由器ARM版

### ISSUE THREAD

**Issue by SkyTeamWater** [NewFuture/DDNS#242]
因为ipv6这东西，在路由器上设置端口转发，如果ipv6解析的是下面的设备的地址就没有意义了，当然x86的软路由也是可以的（但是我没钱）

**Comment by NewFuture** [comment]
这个是希望编译 arm 版的？

**Comment by SkyTeamWater** [comment]
是的

**Comment by SkyTeamWater** [comment]
因为本人太过菜鸡，还请各位大佬帮忙

**Comment by AkariMarisa** [comment]
我在樹莓派上運行pip安裝版正常, 不知道你希望什麼樣的arm版.

**Comment by SkyTeamWater** [comment]
就是那种ssh进路由器可以使用的直接运行版

**Comment by NewFuture** [comment]
单文件版(二进制)的,用 pyinstaller 打包的Linux的只编译了Ubuntu和docker的(可能在其它部分系统也能用)。
其它版本的pipelines欢迎pr.

* 如果能够使用python源pip3直接安装就行
* 如果无法访问python 源但是有python执行环境也可以直接下载源码解压运行 run.py
