### ISSUE TITLE
ddns.exe windows 没办法启动

### ISSUE THREAD

**Issue by darkrain88** [NewFuture/DDNS#25]
![image](https://user-images.githubusercontent.com/39786175/46241066-fded9b00-c3e3-11e8-9239-6f13a8b39aa8.png)

麻烦这是怎么回事。

**Comment by NewFuture** [comment]
打包exe的版本有问题，稍后重新打个包

**Comment by NewFuture** [comment]
https://github.com/NewFuture/DDNS/releases/tag/2.4.4
重新打包了

**Comment by NewFuture** [comment]
@darkrain88 最新的包可以了么

**Comment by darkrain88** [comment]
> @darkrain88 最新的包可以了么

h还没有测试， 谢谢

**Comment by xinyu3ru** [comment]
![lily_screenshot_1539437941](https://user-images.githubusercontent.com/3859309/46906082-739f4e00-cf30-11e8-9759-3e8dabf3c917.png)
没法读取配置？

**Comment by NewFuture** [comment]
@xinyu3ru 
没有`config.json` 这个文件

PS: 这个文件是默认的配置文件，不加参数可以自动创建和加载

**Comment by xinyu3ru** [comment]
> @xinyu3ru
> 没有 `config.json` 这个文件
> 
> PS: 这个文件是默认的配置文件，不加参数可以自动创建和加载

回复的这么及时，找到原因了，改域名的时候[]中间最后多了一个逗号，所以造成load config.json 失败

**Comment by NewFuture** [comment]
OK，这就没问题了
