### ISSUE TITLE
dns.he.net 不生效，记录未更新

### ISSUE THREAD

**Issue by iduangy** [NewFuture/DDNS#260]
环境win10 X64   ddns.exe
没有报错，也没有日志输出

{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "id":"" ,
  "token": "********",
  "dns": "he",
  "ipv4": "****4.******.top",
  "ipv6": "****6.******.top",
  "index4": "interface:Qualcomm QCA61x4A 802.11ac Wireless Adapter",
  "index6": "interface:Qualcomm QCA61x4A 802.11ac Wireless Adapter",
  "ttl": 300,
  "proxy": "DIRECT;127.0.0.1:10808",
  "cache": false,
  "debug": true,
}

**Comment by NewFuture** [comment]
index4 /index6 不支持这个格式

**Comment by iduangy** [comment]
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "id":"" ,
  "token": "**********",
  "dns": "he",
  "ipv4": "***4.****.top",
  "ipv6": "***6.****.top",
  "index4": "url:https://api-ipv4.ip.sb/ip",
  "index6": "url:https://api-ipv6.ip.sb/ip",
  "ttl": 300,
  "proxy": "DIRECT;127.0.0.1:10808",
  "cache": false,
  "debug":false,
}

这样写还是不成
