### ISSUE TITLE
docker版时间慢8小时

### ISSUE THREAD

**Issue by doyoman** [NewFuture/DDNS#262]
需要使用ddns那么应该大多数是国内，但是docker版的时间较国内时间晚8小时，在查看日志时有稍许不便，希望build镜像时可修复
![EFCDA574-85C5-4A4B-AEB5-1B1670BFA5A6](https://user-images.githubusercontent.com/63859866/118064827-5ecc1500-b3ce-11eb-8032-db583f3254dc.jpeg)

**Comment by NN708** [comment]
@doyoman 您好！

这是因为 Docker 的默认时区是 UTC，因而比北京时间 (UTC+8) 慢 8 小时。我们的镜像是基于 Alpine 构建的最小镜像，默认不含 `tzdata`，如果需要调整时区，需要首先安装 `tzdata`，这对我们目前 7-8 MB 的镜像而言增加的大小是相当可观的。因此，我不建议将其包含在官方镜像中，如果你有调整时区的需要的话，可以自己在本地安装一下。

**Comment by doyoman** [comment]
> @doyoman 您好！
> 
> 
> 
> 这是因为 Docker 的默认时区是 UTC，因而比北京时间 (UTC+8) 慢 8 小时。我们的镜像是基于 Alpine 构建的最小镜像，默认不含 `tzdata`，如果需要调整时区，需要首先安装 `tzdata`，这对我们目前 7-8 MB 的镜像而言增加的大小是相当可观的。因此，我不建议将其包含在官方镜像中，如果你有调整时区的需要的话，可以自己在本地安装一下。

好的 感谢您的回复
