### ISSUE TITLE
docker默认挂载出来的config.json是个空文件夹，并不是一个默认的config文件模板

### ISSUE THREAD

**Issue by YangDunYu** [NewFuture/DDNS#267]
运行 docker run -d -v /path/to/config.json:/config.json --network host newfuture/ddns 命令后
从docker挂载出来的config.json是个空文件夹，并不是一个默认的config文件模板

**Comment by NewFuture** [comment]
这个位置docker有写入权限么？

**Comment by NN708** [comment]
当路径不存在时，Docker 默认会挂载出一个文件夹。目前的用法是先在宿主机器上写好 config.json 文件，再启动容器挂载配置文件。

**Comment by pengqiangsheng** [comment]
直接进入终端  手动输入config配置。。。。终于可以了，不枉我一个字母一个字母的对照。。。。

**Comment by NewFuture** [comment]
看来确实有用 docker 生成默认配置文件 的需求

**Comment by NN708** [comment]
等环境变量支持做好，Docker 用环境变量来配置可能会更方便一些？

**Comment by NewFuture** [comment]
建一个空文件夹比如 `/my/empty/dir` 然后运行一次
` docker run  -it -v /my/empty/dir/:/config/ newfuture/ddns /ddns -c /config/config.json`
