### ISSUE TITLE
Task.sh 定时器失效

### ISSUE THREAD

**Issue by samondlee** [NewFuture/DDNS#27]
大佬有空编译下arm arm64 mips呜呜呜

**Comment by samondlee** [comment]
另外 task.sh 在armbian下好像用不了无法更新

**Comment by samondlee** [comment]
Nov 13 12:03:25 aml cron[7006]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
Nov 13 12:04:01 aml CRON[7085]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 13 12:04:01 aml CRON[7084]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 13 12:04:01 aml CRON[7087]: (root) CMD (   '"/opt/bin/ddns/run.py" -c "/opt/bin/ddns/config.json" >> "/opt/bin/ddns/run.log"')
Nov 13 12:04:01 aml CRON[7086]: (root) CMD (   '"/opt/bin/ddns/run.py" -c "/opt/bin/ddns/config.json" >> "/opt/bin/ddns/run.log"')
Nov 13 12:05:01 aml CRON[7157]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 13 12:05:01 aml CRON[7156]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 13 12:05:01 aml CRON[7158]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 13 12:05:01 aml CRON[7160]: (root) CMD (   '"/opt/bin/ddns/run.py" -c "/opt/bin/ddns/config.json" >> "/opt/bin/ddns/run.log"')
Nov 13 12:05:01 aml CRON[7159]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
root@aml:/opt/bin/ddns# /opt/bin/ddns/run.py

**Comment by NewFuture** [comment]
有 log吗？

/opt/bin/ddns/run.log

**Comment by samondlee** [comment]
> 有 log吗？
> 
> /opt/bin/ddns/run.log

没有log。。。只能手动运行。。。

会不会和sudo dpkg-reconfigure dash 有关系

**Comment by NewFuture** [comment]
应该是corn没正确执行
你把` /etc/cron.d/ddns` 改成这样试试
```
*/1 * * * * root  /opt/bin/ddns/run.py -c  /opt/bin/ddns/config.json >> /opt/bin/ddns/run.log
```

armbian 和 dash我都没用过

**Comment by samondlee** [comment]
> 应该是corn没正确执行
> 你把` /etc/cron.d/ddns` 改成这样试试
> 
> ```
> */1 * * * * root  /opt/bin/ddns/run.py -c  /opt/bin/ddns/config.json >> /opt/bin/ddns/run.log
> ```
> armbian 和 dash我都没用过

解决了，在armbian下面 直接用这个 就行了 不要加引号

`*/1 * * * *  root /opt/bin/ddns/run.py -c /opt/bin/ddns/config.json >> /opt/bin/ddns/run.log`

**Comment by L-vivi** [comment]
执行完task.sh,然后改/etc/cron.d/ddns为：
*/1 * * * * root /opt/bin/ddns/run.py -c /opt/bin/ddns/config.json >> /opt/bin/ddns/run.log
这样就可以了吗？

**Comment by L-vivi** [comment]
> > 执行完task.sh,然后改/etc/cron.d/ddns为：
> > */1 * * * * root /opt/bin/ddns/run.py -c /opt/bin/ddns/config.json >> /opt/bin/ddns/run.log
> > 这样就可以了吗？
> 
> 用最新的试试，你们路径可能不一样，不能直接改 @L-vivi

路径我按我的试了，没有效果，也没有run.log这个文件

**Comment by zwz050601** [comment]
> > > 执行完task.sh，然后改/etc/cron.d/ddns为：
> > > * / 1 * * * * root /opt/bin/ddns/run.py -c /opt/bin/ddns/config.json >> /opt/bin/ddns/run.log 
> > > 这样就可以了吗？
> > 
> > 
> > 用最新的试试，你们路径可能不一样，不能直接改@ L-维维
> 
> 路径我按我的试了，没有效果，也没有RUN.LOG这个文件

你试试crontab -e
然后添加
* / 1 * * * * root /opt/bin/ddns/run.py -c /opt/bin/ddns/config.json >> /opt/bin/ddns/run.log

**Comment by L-vivi** [comment]
> > > > 执行完task.sh，然后改/etc/cron.d/ddns为：
> > > > 
> > > > * / 1 * * * * root /opt/bin/ddns/run.py -c /opt/bin/ddns/config.json >> /opt/bin/ddns/run.log
> > > >   这样就可以了吗？
> > > 
> > > 
> > > 用最新的试试，你们路径可能不一样，不能直接改@ L-维维
> > 
> > 
> > 路径我按我的试了，没有效果，也没有RUN.LOG这个文件
> 
> 你试试crontab -e
> 然后添加
> 
> * / 1 * * * * root /opt/bin/ddns/run.py -c /opt/bin/ddns/config.json >> /opt/bin/ddns/run.log

昨天试着改了/etc/cron.d/ddns文件，然后发现定时任务开启了，run.log也有实时记录，但是DDNS只有第一次更新，之后的IP地址变动后，域名解析却不更新了，只看到run.log里面有定时任务记录
我用的armbian系统，内核3.14的debian，然后现在不知道怎么的，定时任务又不动了

**Comment by NewFuture** [comment]
> 昨天试着改了/etc/cron.d/ddns文件，然后发现定时任务开启了，run.log也有实时记录，但是DDNS只有第一次更新，之后的IP地址变动后，域名解析却不更新了，只看到run.log里面有定时任务记录
> 我用的armbian系统，内核3.14的debian，然后现在不知道怎么的，定时任务又不动了

可以贴一下Log

**Comment by L-vivi** [comment]
> > 昨天试着改了/etc/cron.d/ddns文件，然后发现定时任务开启了，run.log也有实时记录，但是DDNS只有第一次更新，之后的IP地址变动后，域名解析却不更新了，只看到run.log里面有定时任务记录
> > 我用的armbian系统，内核3.14的debian，然后现在不知道怎么的，定时任务又不动了
> 
> 可以贴一下Log

这个是我手动/opt/ddns/run.py -c /opt/ddns/config.json >> /opt/ddns/run.log的log：
========================= Fri Dec 14 10:32:22 2018 =========================
n1v6.此处有码.top(AAAA) ==> 240e:bc:a733:c100:此处有码:此处有码:d63f:2c7 [via DIRECT]

现在手动执行后，不会再自动执行了

这个是我的/etc/cron.d/ddns的内容：
/opt/ddns/run.py -c /opt/ddns/config.json >> /opt/ddns/run.log

这个是我/var/spool/cron/crontabs/root的内容
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.FxX5Qp/crontab installed on Fri Dec 14 10:13:52 2018)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp $)
*/1 * * * * root /opt/ddns/run.py -c /opt/ddns/config.json >> /opt/ddns/run.log

这个是cron状态：
root@N1:~# crontab -l
*/1 * * * * root /opt/ddns/run.py -c /opt/ddns/config.json >> /opt/ddns/run.log
root@N1:~# pgrep cron
4605

**Comment by NewFuture** [comment]
@L-vivi 这个定时器时每分钟触发一次,
看run.log只有你手动执行的一次结果，没有corntab执行内容，

你看看corntab的日志，是不是没有运行或者运行出差错了

**Comment by konaisland** [comment]
我以前也是这个问题，改一下run.py第一行那个python路径 #! 那个
添加到crontab换了用户 path就不一样了

**Comment by konaisland** [comment]
还有就是，什么config 文件能用绝对路径的就用绝对路径

**Comment by L-vivi** [comment]
> @L-vivi 这个定时器时每分钟触发一次,
> 看run.log只有你手动执行的一次结果，没有corntab执行内容，
> 
> 你看看corntab的日志，是不是没有运行或者运行出差错了

`Dec 14 13:23:01 localhost CRON[6616]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:23:01 localhost CRON[6616]: pam_unix(cron:session): session closed for user root
Dec 14 13:24:01 localhost CRON[6618]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:24:01 localhost CRON[6618]: pam_unix(cron:session): session closed for user root
Dec 14 13:25:01 localhost CRON[6622]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:25:01 localhost CRON[6621]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:25:01 localhost CRON[6622]: pam_unix(cron:session): session closed for user root
Dec 14 13:25:01 localhost CRON[6621]: pam_unix(cron:session): session closed for user root
Dec 14 13:26:01 localhost CRON[6627]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:26:01 localhost CRON[6627]: pam_unix(cron:session): session closed for user root
Dec 14 13:27:01 localhost CRON[6629]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:27:01 localhost CRON[6629]: pam_unix(cron:session): session closed for user root
Dec 14 13:28:01 localhost CRON[6634]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:28:01 localhost CRON[6634]: pam_unix(cron:session): session closed for user root
Dec 14 13:29:01 localhost CRON[6647]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:29:01 localhost CRON[6647]: pam_unix(cron:session): session closed for user root
Dec 14 13:30:01 localhost CRON[6649]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:30:01 localhost CRON[6649]: pam_unix(cron:session): session closed for user root
Dec 14 13:31:01 localhost CRON[6652]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:31:01 localhost CRON[6652]: pam_unix(cron:session): session closed for user root
Dec 14 13:32:01 localhost CRON[6656]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:32:01 localhost CRON[6656]: pam_unix(cron:session): session closed for user root
Dec 14 13:33:01 localhost CRON[6689]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:33:01 localhost CRON[6689]: pam_unix(cron:session): session closed for user root
Dec 14 13:34:01 localhost CRON[6691]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:34:01 localhost CRON[6691]: pam_unix(cron:session): session closed for user root
Dec 14 13:35:01 localhost CRON[6694]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:35:01 localhost CRON[6693]: pam_unix(cron:session): session opened for user root by (uid=0)
Dec 14 13:35:01 localhost CRON[6694]: pam_unix(cron:session): session closed for user root
Dec 14 13:35:01 localhost CRON[6693]: pam_unix(cron:session): session closed for user root`

这是一段日志

**Comment by L-vivi** [comment]
> @L-vivi
> IPV6短时间再次拨号 是不会变动的
> 
> 只有IPV4会变

电信每次重拨ipv6也在变的

**Comment by L-vivi** [comment]
> > @L-vivi 这个定时器时每分钟触发一次,
> > 看run.log只有你手动执行的一次结果，没有corntab执行内容，
> > 你看看corntab的日志，是不是没有运行或者运行出差错了
> 
> ```
> 12月 14 14:27:01 N1 cron[7343]: (*system*ddns) INSECURE MODE (group/other writable) (/etc/cron.d/ddns)
> 12月 14 14:27:01 N1 CRON[7813]: pam_unix(cron:session): session opened for user root by (uid=0)
> 12月 14 14:27:01 N1 CRON[7814]: (root) CMD (root /opt/ddns/run.py -c /opt/ddns/config.json >> /opt/ddns/run.log)
> 12月 14 14:27:01 N1 CRON[7813]: (CRON) info (No MTA installed, discarding output)
> 12月 14 14:27:01 N1 CRON[7813]: pam_unix(cron:session): session closed for user root
> 12月 14 14:28:01 N1 cron[7343]: (*system*ddns) INSECURE MODE (group/other writable) (/etc/cron.d/ddns)
> 12月 14 14:28:01 N1 CRON[7815]: pam_unix(cron:session): session opened for user root by (uid=0)
> 12月 14 14:28:01 N1 CRON[7816]: (root) CMD (root /opt/ddns/run.py -c /opt/ddns/config.json >> /opt/ddns/run.log)
> 12月 14 14:28:01 N1 CRON[7815]: (CRON) info (No MTA installed, discarding output)
> 12月 14 14:28:01 N1 CRON[7815]: pam_unix(cron:session): session closed for user root
> ```
> 这是一段日志
> 
> 另外还发现个问题
> 手动`cd /opt/ddns && ./run.py`之后
> 我把DDNS解析记录删除
> 
> 再手动`/opt/ddns/run.py -c /opt/ddns/config.json >> /opt/ddns/run.log`
> 或者再手动`cd /opt/ddns && ./run.py`
> 都不会添加DDNS解析记录了
> 除非ipv6地址有变化才会正常添加
> 
> ipv6地址没有变化的情况下
> 重启设备之后
> 再手动`/opt/ddns/run.py -c /opt/ddns/config.json >> /opt/ddns/run.log`（这样run.log也会有记录一次）
> 或者手动`cd /opt/ddns && ./run.py`
> 是可以的添加DDNS解析记录了

解决了，终于解决了
`*/1 * * * * python3 /opt/ddns/run.py -c /opt/ddns/config.json >> /opt/ddns/run.log`
不添加root就可以了，另外我指定python3运行脚本，不知道有其他没有问题

**Comment by samondlee** [comment]
你是没给RUN.PY权限吗= =我是给的777权限。。。@L-vivi
