### ISSUE TITLE
cloudflare解析ddns后如果ip变了就会不走cdn

### ISSUE THREAD

**Issue by lsCoding666** [NewFuture/DDNS#271]
如果本机ip变了，那么cloudflare的代理（cdn）会灭了，变成“仅dns”。我希望更新ip的时候不会改变云也就是cdn的状态。
![image](https://user-images.githubusercontent.com/73888354/125834597-61145369-beed-46c3-b2ed-82ff5da9e9fa.png)

**Comment by NewFuture** [comment]
#115 和这个一样的伪问题？

**Comment by xiaofami** [comment]
https://github.com/cloudflare/python-cloudflare/issues/73

https://github.com/cloudflare/python-cloudflare

这个项目应该能通过python控制cloudflare状态

**Comment by phlinhng** [comment]
把這裡的 `proxied` 改成 True 就行
https://github.com/NewFuture/DDNS/blob/914f3c09c3c133b1883d5002462d68cfe59984aa/dns/cloudflare.py#L151
懶得改的話，可以另外設置一個 ddns 專用的域名，然後把要開啟 cdn 的域名 cname 到 ddns 上。

**Comment by NewFuture** [comment]
master已更新，保留之前的配置
