### ISSUE TITLE
[feature] Support environment variables in Docker image

### ISSUE THREAD

**Issue by NN708** [NewFuture/DDNS#276]
Very glad to see environment variables are supported in #269. However, currently environment variables defined from Docker can not be passed to cron jobs. A workaround is needed. This is related to #220 and #267.

**Comment by NewFuture** [comment]
加个 entrypoint.sh

1. 有命令时执行输入命令
2. 只有参数时('-'开头) 运行 `/ddns + 参数`
3. 没有命令和参数说运行 `cron -f` https://stackoverflow.com/questions/27771781/how-can-i-access-docker-set-environment-variables-from-a-cron-job


*  `docker run  -d newfuture/ddns  echo 1`  自定义命令
*  `docker run  newfuture/ddns --help` 等效于 `ddns --help`  
*  `docker run  -d newfuture/ddns` 一直执行corn定时任务

**Comment by NN708** [comment]
@NewFuture 十分感谢提供解决方案！

> 2. 只有参数时('-'开头) 运行 `/ddns + 参数`

有可能有人会用参数来传递配置项，有参数时是不是也用 cron 来执行比较好一些？（但不知道好不好实现）

**Comment by NewFuture** [comment]
两点考虑
* corn 最好是 config 配置文件， 命令行没有缓存
* 直接参数就是运行一次，方便调试和生成配置文件，就和 直接运行ddns效果一样

**Comment by NN708** [comment]
Solved via 9cfdc14fbb07aeb020a255c370b93e3e0a026c6e.
