### ISSUE TITLE
建议在win运行ddns.exe时将解析ip同时添加到hosts里

### ISSUE THREAD

**Issue by iwrwr** [NewFuture/DDNS#278]
因为在内网运行添加解析后  同时又要用到域名做本机的端口转发listen地址
所以一直受本机dns解析不能实时生效的困扰
希望能在上传ip数据的同时把域名和ip对应到hosts里
这样能减少一些困扰

**Comment by NewFuture** [comment]
修改本机hosts的意义在哪，为啥不直接localhost？

**Comment by ZD511751763** [comment]
如果加入这个功能，假设内网中笔记本电脑被带到外网使用时会造成另外的困扰，建议自己写一段脚本加入hosts

**Comment by NewFuture** [comment]
这个功能目前仍不在考虑范围内
