### ISSUE TITLE
内网解析ddns解析出来是本机IP的问题

### ISSUE THREAD

**Issue by xztxy** [NewFuture/DDNS#279]
大佬请问下
公司内网环境
防火墙作为网关路由出口  10.10.10.254
esxi虚拟化环境10.10.20.100 里面虚拟了一台做ddns服务器10.10.20.108
阿里上的解析解析成了自己ddns服务器的IP地址10.10.20.108了，
请问下需要怎么设置吗~~~是不是要在防火墙上做ddns服务器的映射？有没有具体端口呢？

**Comment by sarurifan** [comment]
如果你可以访问外网, 你可以用 ` "index4": "url:http://ip.42.pl/raw", ` 这样的配置 获取ip ,
但公司内网无法访问外网我就不清楚如何做了

**Comment by jackberry** [comment]
> 如果你可以访问外网, 你可以用 `"index4": "url:http://ip.42.pl/raw",` 这样的配置 获取ip , 但公司内网无法访问外网我就不清楚如何做了

使用代理的话获取到的是代理的ip，有没有国内的同类型网站获取链接获取到的是国内的ip

**Comment by phlinhng** [comment]
> > 如果你可以访问外网, 你可以用 `"index4": "url:http://ip.42.pl/raw",` 这样的配置 获取ip , 但公司内网无法访问外网我就不清楚如何做了
> 
> 使用代理的话获取到的是代理的ip，有没有国内的同类型网站获取链接获取到的是国内的ip

@jackberry 這個可以
`http://pv.sohu.com/cityjson?ie=utf-8`

**Comment by NewFuture** [comment]
`public`也可以
