### ISSUE TITLE
cloudflare 不成功，不知是哪里问题？

### ISSUE THREAD

**Issue by wys206** [NewFuture/DDNS#284]
您好：
win10自动运行日志显示如下，（手动运行直接弹窗结束，没找到日志）
DDNS[ v2.10.2@2021-07-30T04:11:47+00:00 ] run: nt win32
Configuration was loaded from <== D:\winDDNS\config.json
========================= Fri Sep  3 17:17:01 2021 =========================

我的免费域名（***.***.cf）(AAAA) ==> 我的ipv6地址 [via DIRECT]

配置如下：
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "cloudflare",
  "id": "我的邮箱",
  "index4": "default",
  "index6": "default",
  "ipv4": [],
  "ipv6": [
    "我的免费域名（***.***.cf）"
  ],
  "proxy": null,
  "token": "我的API key",
  "ttl": null
}

是不支持.cf 等域名吗？有解决办法吗？

**Comment by NewFuture** [comment]
你在cloudflare上手动配置可以么？

**Comment by liwemhao** [comment]
cloudflare使用token时不要填邮箱

**Comment by Huiaei** [comment]
同CloudFlare遇到问题。
## 运行出现
```
WARNING:root:?per_page=50 : error[400]:{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
ERROR:root:{"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6103,"message":"Invalid format for X-Auth-Key header"}]}],"messages":[],"result":null}
```

## cloudflare api设置
权限：区域.DNS:编辑
指定了一个域名

提供的api测试命令没有问题
```bash
curl -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
     -H "Authorization: Bearer Api令牌" \
     -H "Content-Type:application/json"
```

## 配置文件
```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": false,
  "dns": "cloudflare",
  "id": "邮箱",
  "index4": "default",
  "index6": "public",
  "ipv4": [],
  "ipv6": ["二级域名"],
  "proxy": null,
  "token": "api令牌",
  "ttl": null
}
```

**Comment by NewFuture** [comment]
>Cloudflare 为邮箱(使用 Token 时留空)

确认一下是不是这个问题，id 空着试试

**Comment by Huiaei** [comment]
> > Cloudflare 为邮箱(使用 Token 时留空)
> 
> 确认一下是不是这个问题，id 空着试试

我的问题有效

**Comment by Huiaei** [comment]
顺便说一句，cloudflare的api不能对 .cf .ga .ml .tk .ga 这些顶级域名修改了
https://github.com/trojan-tutor/trojan-tutor.github.io/issues/56#issuecomment-625275555
