### ISSUE TITLE
关于内网穿透后的一些问题

### ISSUE THREAD

**Issue by miss85246** [NewFuture/DDNS#289]
各位大佬好，本人小白一个，对网络这块不是很懂，所以可能问的问题很傻，请大家见谅
是这样的，我有两台机器， 一台 win， 一台 centos，外加一个华为云的域名。
最初，我使用 DDNS 进行解析，把解析记录设置成 AAAAA 后无论是外网还是内网都能成功的使用 ssh 连接到我的机器。
后来我部署了 code-server 和 hexo， 并且使用 certbot 申请了泛域名证书之后，配置了 nginx，希望可以使用二级域名对服务进行区分。

问题来了：我这样做之后，在同网段的 win 可以很好地解析，使用二级域名可以直接访问到我的服务，但是当我使用外网进行连接的时候，就什么都访问不到了，提示的是 DNS_PROBE_FINISHED_NXDOMAIN
![image](https://user-images.githubusercontent.com/42527535/136919479-67eb38f0-6383-4cdf-a71e-508181a1f03d.png)
而且就连 ssh 也无法进行连接了... 
不是很懂这是为什么？大佬能帮忙解释一下原因吗？

**Comment by NewFuture** [comment]
确认一下这个机器上z这个域名能正常解析么 （`nslookup your.domain.com`）
