### ISSUE TITLE
旧IPv6地址失效后无法自动选择新地址

### ISSUE THREAD

**Issue by xiaofami** [NewFuture/DDNS#291]
家里的路由器拨号获取ipv6前缀，下面的设备自动获取ipv6地址。路由器PPPOE连接每隔几天会被ISP自动断开重新拨号导致IPv6前缀变化。我在Manjaro ARM中测试发现，NewFuture/DDNS仍然会使用旧前缀的旧地址。在Manjaro系统中使用`ip -6 addr show eth0`查看：

    3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet6 2***:***:848a:e4**::f4a/128 scope global dynamic noprefixroute 
       valid_lft 26293sec preferred_lft 26293sec
    inet6 2***:***:848c:3970:503:3a**:****:670a/64 scope global dynamic noprefixroute 
       valid_lft 256332sec preferred_lft 169932sec
    inet6 2***:***:848a:e4b0:b95c:**f3:****:28a7/64 scope global deprecated dynamic noprefixroute 
       valid_lft 4326sec preferred_lft 0sec
    inet6 fe80::****:****:b1ec:7ee/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

其中848a（第一行地址）是旧前缀，848c：3970是新前缀（第二行地址），在路由器上可以确认。用手机流量测试，可以通过848c地址ssh连接，证明新地址没问题。然而NewFuture/DDNS认为地址仍然是 2***:***:848a:e4b0::f4a/128 ，不会更新。手动执行`curl v6.ipv6-test.com/api/myip.php`测试，命令超时无输出。

在NewFuture/DDNS配置文件中，IPv6获取方式为public。

**Comment by NewFuture** [comment]
可以配置一个稳定的ipv6获取的API
