### ISSUE TITLE
阿里云云解析不起作用

### ISSUE THREAD

**Issue by HADB** [NewFuture/DDNS#3]
运行没有报错，日志里有update ipv4 to: XXX.XXX.XXX
还有很多行只输出了一个点
但是去查询发现并没有修改成功

**Comment by NewFuture** [comment]
输出 `.`表示ip没有改变，

请问DNS服务器上的记录多少，是否更新了?

**Comment by NewFuture** [comment]
@HADB 你更新一下最新版的 ,在配置中把缓存关掉，看一下
```
   "cache": false,
```

**Comment by HADB** [comment]
估计是AccessKey的问题，云解析不支持RAM子账号……
