### ISSUE TITLE
cloudflare免费域名无法更新dns

### ISSUE THREAD

**Issue by PencilNavigator** [NewFuture/DDNS#301]
## **To Reproduce [复现]**
Copy and paste the following code with a Domain ending with .cf, .ga, .gq, .ml, .tk or any TLD

### version info [基本信息]

* DDNS Version: 2.10.3
* OS Version： Windows 10 1909 (Int OS ver: 18363.592)
* Type(运行方式): Python
* related issues (相关问题): 

### config file [配置文件]
{
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": false,
  "dns": "cloudflare",
  "id": "2***********@********m",
  "index4": "default",
  "index6": "default",
  "ipv4": [],
  "ipv6": [
    "p***************.tk"
  ],
  "proxy": null,
  "token": "8******************************c",
  "ttl": null
}
}
```

###  debug output [调试输出]

```sh
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 1038,
      "message": "You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD (top-level domain). To configure the DNS settings for this domain, use the Cloudflare Dashboard."
    }
  ],
  "messages": []
}
403 Forbidden
```

**Comment by NewFuture** [comment]
买一个域名

**Comment by Lehmaning** [comment]
只封了 Freenom 的免费域名。
