### ISSUE TITLE
如何修改为一分钟运行一次 IP检测。

### ISSUE THREAD

**Issue by 110560** [NewFuture/DDNS#302]
我使用的源码运行  ddns目录下执行./run.py 可正常更新IP  
crontab  定时任务应该怎么写 救救孩子 
或者默认提供的 ./task.sh 如何修改为一分钟执行一次。

**Comment by NN708** [comment]
将 [task.sh](https://github.com/NewFuture/DDNS/blob/4679a78013886a0f4008170c8ff6cabcd1d1fc53/task.sh) 第 6 行改为
```
echo "* * * * *   root    $CMD" > /etc/cron.d/ddns;
```

**Comment by 110560** [comment]
好的谢谢 执行 ./task.sh 后   也要执行一下 ./systemd.sh install 对吧

**Comment by NN708** [comment]
> 好的 谢谢 执行 ./task.sh 后 也要执行一下 ./systemd.sh install 对吧

不需要，systemd 和 crontab 是两种不同的方式
