### ISSUE TITLE
armv8二进制文件编译

### ISSUE THREAD

**Issue by jiangxianxu** [NewFuture/DDNS#310]
您好，冒昧打扰了，感谢您发布的软件能解决我的问题，我希望在华硕路由器上运行您的软件，但是路由器上没有python解释器，无法直接运行脚本，所以想运行二进制文件，路由器是armv8体系结构，我在另外一台安装了debian系统的armv8服务器里执行您的setup.py文件试图编译一个可用于armv8的可执行文件，会报如下错误Exception: setup.py should be run in CI (Travis or AzurePipelines)，所以想咨询一下编译的动作是只能在CI平台上执行吗？能否做到可以本地执行，或者能否麻烦您帮忙编译一个armv8版本呢，感谢！！！

**Comment by NewFuture** [comment]
本地debug可以 改 setup.py 跳过检查

编译和发布 是CI时自动做的

**Comment by jiangxianxu** [comment]
感谢指导，已经能正常编译出aarch64体系结构可用的二进制版本，再次感谢！
