### ISSUE TITLE
Script changes zone to DNS Only after running

### ISSUE THREAD

**Issue by Townie-au** [NewFuture/DDNS#311]
Hi
Running the script changes zone to DNS Only after updating.
config.json proxy is null

**Comment by NewFuture** [comment]
it does not keep the previous setting in DNS Server.

Related  #115

**Comment by NewFuture** [comment]
you can help modified those lines
https://github.com/NewFuture/DDNS/blob/9cfdc14fbb07aeb020a255c370b93e3e0a026c6e/dns/cloudflare.py#L139-L140

to (keep the proxied value))
```py
                res = request('PUT', '/' + zoneid + '/dns_records/' + record['id'],
                              type=record_type, content=value, name=domain, proxied=record['proxied'] ,ttl=Config.TTL)
```

```diff
-type=record_type, content=value, name=domain, ttl=Config.TTL)
+type=record_type, content=value, name=domain, proxied=record['proxied'] ,ttl=Config.TTL)
```

My cloud flare account was lost. Please help me test it.

If it works, please create a pull request.

**Comment by Townie-au** [comment]
> you can help modified those lines
> 
> https://github.com/NewFuture/DDNS/blob/9cfdc14fbb07aeb020a255c370b93e3e0a026c6e/dns/cloudflare.py#L139-L140
> 
> to (keep the proxied value))
> 
> ```python
>                 res = request('PUT', '/' + zoneid + '/dns_records/' + record['id'],
>                               type=record_type, content=value, name=domain, proxied=record['proxied'] ,ttl=Config.TTL)
> ```
> 
> ```diff
> -type=record_type, content=value, name=domain, ttl=Config.TTL)
> +type=record_type, content=value, name=domain, proxied=record['proxied'] ,ttl=Config.TTL)
> ```
> 
> My cloud flare account was lost. Please help me test it.
> 
> If it works, please create a pull request.

I'll give it a go

**Comment by Townie-au** [comment]
> you can help modified those lines
> 
> https://github.com/NewFuture/DDNS/blob/9cfdc14fbb07aeb020a255c370b93e3e0a026c6e/dns/cloudflare.py#L139-L140
> 
> to (keep the proxied value))
> 
> ```python
>                 res = request('PUT', '/' + zoneid + '/dns_records/' + record['id'],
>                               type=record_type, content=value, name=domain, proxied=record['proxied'] ,ttl=Config.TTL)
> ```
> 
> ```diff
> -type=record_type, content=value, name=domain, ttl=Config.TTL)
> +type=record_type, content=value, name=domain, proxied=record['proxied'] ,ttl=Config.TTL)
> ```
> 
> My cloud flare account was lost. Please help me test it.
> 
> If it works, please create a pull request.

It works!
I also had to run this command
sudo ln -s /usr/bin/python3.7 /usr/bin/python for the script to successfully run.
I dont know how to do a pull request but Im trying to learn now.

**Comment by NewFuture** [comment]
@Townie-au 
1. **folk** this repo 
2.  **edit** this file in your repo and test again
3.  **commit** and **push**
4.  create a pull-request to this repo 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
