### ISSUE TITLE
[feature]建议自动任务时，能够把执行日志打印出来

### ISSUE THREAD

**Issue by lonelyleaves** [NewFuture/DDNS#313]
建议自动任务时，能够把执行日志打印出来，这样方便分析问题

**Comment by NewFuture** [comment]
cron 的 log 在日志文件中，比如
https://github.com/NewFuture/DDNS/blob/9cfdc14fbb07aeb020a255c370b93e3e0a026c6e/task.sh#L4

systemd 的 用 `systemctl status newfuture_ddns` 看log
