### ISSUE TITLE
[feature]如果修改ip的域名, 则会出现新域名解析, 旧域名任然存在

### ISSUE THREAD

**Issue by hugle-rep** [NewFuture/DDNS#316]
1, 是否可以解决, 更换域名, 删除之前的旧域名(阿里云)
2, 能否在配置项config.json里面增加配置, 多久更新一次IP
3, 能否在配置项配置日志, 日志生成域名ip更新记录, 更新是否成功, 更新后的IP地址和之前的IP地址
4, 使用的是win 二进制

**Comment by StarsRiver-der** [comment]
> 

删除旧解析的功能估计不行，它不是一个管理策略类工具
定时更新解析这个东西用定时任务就可以实现，运行一次就结束。个人认为没必要将这个工具的进程持续保留在系统中

**Comment by NewFuture** [comment]
1. 这个维护旧域名的功能在可见的范围内，不会考虑加入
2. 多久更新这个在定时任务的脚本里可以改(右键编辑)，默认是5分钟
