### ISSUE TITLE
建议将此脚本提交至此页面

### ISSUE THREAD

**Issue by Argon-Pub** [NewFuture/DDNS#32]
我很喜欢这个脚本，尤其是支持分开配置IPv4与IPv6，很有用。
DNSPod的API页面，有一个专门的版块，用来放置优秀的第三方项目，希望作者能联系官方人员，让此项目出现在[这个页面](https://support.dnspod.cn/Support/api)上。

**Comment by NewFuture** [comment]
`官方`是指QQ群么  😂
很久没用QQ了

**Comment by Argon-Pub** [comment]
> `官方`是指QQ群么 😂
> 很久没用QQ了

是的吧…
没准可以试试在DNSPod里提工单管不管用。
