### ISSUE TITLE
[debug]

### ISSUE THREAD

**Issue by xurent** [NewFuture/DDNS#321]
## **Describe the bug [描述]**
![J V@(8ZYV{TM)SBY6I%SLZ0](https://user-images.githubusercontent.com/51280234/174842067-599a75b2-efca-4a60-b1d6-64d6535d8f29.png)

### version info [基本信息]
这个接入dnspod的ipv4列表填什么，怎么一直报错？
* DDNS Version: 
* OS Version： 
* Type(运行方式): Binary/Python
* related issues (相关问题): 

### config file [配置文件]

```json
{
}
```

###  debug output [调试输出]

```sh
粘贴输出日志
paste out put here
```

**Additional context**

**Comment by NewFuture** [comment]
token 配错了吧
