### ISSUE TITLE
关于在docker模式下无法开机启动的问题

### ISSUE THREAD

**Issue by shuiyuewusong** [NewFuture/DDNS#323]
目前只能重新执行脚本才可以启动,有计划进行在docker模式下重启后自动启动吗 我添加命令  --restart=always 无效

**Comment by shuiyuewusong** [comment]
![image](https://user-images.githubusercontent.com/33865520/178087610-2fe8c9a5-9bcd-4a6e-bdb5-70cefa3d174d.png)
![image](https://user-images.githubusercontent.com/33865520/178087627-db50c23d-104d-4148-b942-67cc33794ab4.png)
配置文件如下 第一个截图是我nuc重启后的截图并没有DDNS在启动

**Comment by shuiyuewusong** [comment]
我的电脑是手动关闭不是强制关机的

**Comment by NN708** [comment]
> ![image](https://user-images.githubusercontent.com/33865520/178087627-db50c23d-104d-4148-b942-67cc33794ab4.png)

图中您并未添加 `--restart=always`。

**Comment by shuiyuewusong** [comment]
不好意思 我重新添加这个参数后又可以了
可能是我之前参数放置的位置不对  
给您造成麻烦了抱歉.
