### ISSUE TITLE
[feature] 为 run.log 加上时间戳

### ISSUE THREAD

**Issue by fdxx** [NewFuture/DDNS#326]
example:
```log
. . . . . . . . . . . . 
L 2022-07-04 - 13:23:55: exp.com(A) ==> x.x.x.x [via DIRECT]
```

**Comment by NewFuture** [comment]
实现似乎不难，https://docs.python.org/3/howto/logging.html#displaying-the-date-time-in-messages
不知道是否有广泛需求

**Comment by liker5092** [comment]
顶下，log 内增加。必需求

**Comment by aimai-who** [comment]
顶下，建议每执行一次就记录一次带时间戳的log。log文件膨胀到一定的阈值自动清理。

**Comment by NewFuture** [comment]
可以考虑加一个logger `datefmt` 的配置

**Comment by laozhoubuluo** [comment]
上述功能已于 #372 实现完毕。
