### ISSUE TITLE
多网卡想获取公网IP需要如何配置？

### ISSUE THREAD

**Issue by lyhiving** [NewFuture/DDNS#33]
目前如果将index4 设置为数字获取到的是内网地址，如果改为public就只会获取其中一个IP地址，并不会拿到某个网卡的外网地址。

**Comment by lyhiving** [comment]
> 可以试试正则表达式，
> 
> 不行的话可能要再加一个获取方法

正则表达式和public、default、0-9等数字是属于同一个选择器，一旦选择了就无法指定网卡了。
估计是要有个别的方法。

**Comment by NewFuture** [comment]
出口IP虽然不是固定的但是网段一般是固定的，根据网段写个匹配应该是

**Comment by lyhiving** [comment]
由于在不同的网卡，外网IP目前看获取是正常的，但是无法有参数设置通过某个网卡获取该网卡的外网地址。我目前拿到的都是内网的地址。

**Comment by cjoin** [comment]
我的需求是：指定四个域名的ip地址，分别是内网有线网卡内网ip、无线网卡内网ip，有线网卡外网ip，无线网卡外网ip。请问现阶段支持吗？如果支持，应该如何配置呢？

ps：如果不支持，希望可以支持一下。既然ipv4配置项可以配置多个域名，那index4配置项就应该针对这些域名分别设置获取规则。

**Comment by NewFuture** [comment]
> 我的需求是：指定四个域名的ip地址，分别是内网有线网卡内网ip、无线网卡内网ip，有线网卡外网ip，无线网卡外网ip。请问现阶段支持吗？如果支持，应该如何配置呢？

现在可以允许多个task(多个配置文件）来实现
