### ISSUE TITLE
大佬 又是我 我又来了...task.bat没有正常运行

### ISSUE THREAD

**Issue by sandianyue** [NewFuture/DDNS#34]
我这边刚刚手机发现又无连上PC的FTP了 查了下阿里云的控制台 发现解析IP一直没更新过 （之前昨天已经双击运行了） 我重试了双击运行 和管理员运行 均无效 均等待5-10分钟 没有更新 最后手动运行exe更新的...

**Comment by NewFuture** [comment]
看看系统的计划任务

**Comment by sandianyue** [comment]
> 看看系统的计划任务

GitHub邮件推送真不错...刚才在外面 可惜忘了密码 无法回复 我昨晚就看了计划里没有

**Comment by NewFuture** [comment]
问题还存在么?
