### ISSUE TITLE
IPV4 DDNS 上报 错误

### ISSUE THREAD

**Issue by KiritakeKumi** [NewFuture/DDNS#35]
您好,在启动后出现如下错误:
b'{"success":false,"errors":[{"code":1004,"message":"DNS Validation Error","error_chain":[{"code":9005,"message":"Content for A record is invalid. Must be a valid IPv4 address"}]}],"messages":[],"result":null}'

用的是API的公网IP那挡

请问是否为Bug,以及其是否有解决方案?谢谢!!!

**Comment by NewFuture** [comment]
看看上报的IP是啥？
然后打开这个确认一下 http://v4.ipv6-test.com/api/myip.php

**Comment by pukanxi** [comment]
> 看看上报的IP是啥？
> 然后打开这个确认一下 http://v4.ipv6-test.com/api/myip.php

已确认.两个IP是相同的
LOG:

*******com(A) ==> b'1********.67' [via DIRECT]
b'{"success":false,"errors":[{"code":1004,"message":"DNS Validation Error","error_chain":[{"code":9005,"message":"Content for A record is invalid. Must be a valid IPv4 address"}]}],"messages":[],"result":null}'

**Comment by zhanggangbz** [comment]
(A) ==> b'10.10.10.10' [via DIRECT]
使用的是ddns.exe,2.4.4
输出信息如上显示，应该是IP取错了不应该有b和'

**Comment by pukanxi** [comment]
> (A) ==> b'10.10.10.10' [via DIRECT]
> 使用的是ddns.exe,2.4.4
> 输出信息如上显示，应该是IP取错了不应该有b和'

请问有什么建议的解决方案嘛??

**Comment by zhanggangbz** [comment]
@pukanxi 
才看到你的消息
我是直接用python运行了
刚把这个exe研究了下，发现用2.4.4版本的exe解析出现这种问题时配置文件中index4设置如下
"index4": "public",
你应该也是
把这个修改位
"index4": "default",
就能正常获取IP，exe也就可以正常运行了


作者代码中：
DDNS/util/ip.py 43到54行
```
def public_v4(url="http://v4.ipv6-test.com/api/myip.php"):  # 公网IPV4地址
    try:
        return urlopen(url, timeout=60).read()
    except Exception as e:
        logger.error(e)


def public_v6(url="http://v6.ipv6-test.com/api/myip.php"):  # 公网IPV6地址
    try:
        return urlopen(url, timeout=60).read()
    except Exception as e:
        logger.error(e)
```

应该是这里直接return这个有问题，我猜应该像DDNS/dns/cloudflare.py第61行一样decode('utf8')一下

**Comment by zhanggangbz** [comment]
@pukanxi 
我电脑是直接拨号上网的且拿到的也是公网IP，所以昨天直接改成default是可行的
如果过路由器应该就不行了

**Comment by NewFuture** [comment]
> 应该是这里直接return这个有问题，我猜应该像DDNS/dns/cloudflare.py第61行一样decode('utf8')一下

可能是编码问题，我晚上看看

**Comment by zwpaper** [comment]
`run.py` 改成下面就可以：
```
(domain, record_type, kw['ip'].decode("utf-8") , proxy))
```

**Comment by NewFuture** [comment]
> `run.py` 改成下面就可以：
> 
> ```
> (domain, record_type, kw['ip'].decode("utf-8") , proxy))
> ```

DDNS/util/ip.py 
嗯，改这个文件比较合适，这个地方应该处理一下兼容
