### ISSUE TITLE
[debug] schema 似乎漏了 cache

### ISSUE THREAD

**Issue by IIIlllIIllIIIll** [NewFuture/DDNS#353]
## **描述问题 (Describe the bug)**

VSCode 提示 ```Property cache is not allowed.```

## 版本信息 (version info)

* schema Version: 
https://ddns.newfuture.cc/schema/v2.8.json

### 配置文件 (config file)

```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "cache": true,
}
```

**Comment by NewFuture** [comment]
可以提个PR 😄
