### ISSUE TITLE
哪位大佬可以改编下多ip，ping延时最低的筛选出来，然后自动ddns解析

### ISSUE THREAD

**Issue by wfniub** [NewFuture/DDNS#358]
服务器有多个ip，或者多个ip段，部分段可能会受到攻击，导致延时很大，这个时候就很需要自动解析到延时最小的ip地址了
哪位大佬可以改编下多ip，ping延时最低的筛选出来，然后自动ddns解析

**Comment by NewFuture** [comment]
这种场景,直接配多IP或者多线路解析更好，不需要 DDNS 😂

**Comment by wsy741963** [comment]
腾讯和阿里都有智能解析，比用python程序测速好

**Comment by NewFuture** [comment]
这个不是DDNS要做的事情😀
