### ISSUE TITLE
[debug]在ADGURADHOMEAD下IPV4地址更新失败

### ISSUE THREAD

**Issue by zxbiao** [NewFuture/DDNS#362]
## **描述问题 (Describe the bug)**

如题，最近安装了ADGURADHOME后发现更新失败，debug之后发现IPV4的查询地址（ https://pv.sohu.com/cityjson?ie=utf-8 ）被默认过滤了。
考虑更换一下IPV4的查询地址？
例如：
* https://ip.sb/api/
## 版本信息 (version info)

* DDNS Version: v2.11.5@2022-07-28T14:50:06+00:00
* OS Version： Microsoft Windows [版本 10.0.19044.2130]
* Type(运行方式): Binary
* related issues (相关问题):

**Comment by NewFuture** [comment]
可以自行设置https://github.com/NewFuture/DDNS#index4-%E5%92%8C-index6-%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E
如
```
"index4":"url:http://ip.sb"
```

**Comment by zxbiao** [comment]
> 可以自行设置https://github.com/NewFuture/DDNS#index4-%E5%92%8C-index6-%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E 如
> 
> ```
> "index4":"url:http://ip.sb"
> ```

原来我没有看清README，打扰了。
