### ISSUE TITLE
[debug]win版本无法正常工作

### ISSUE THREAD

**Issue by redzhuang** [NewFuture/DDNS#377]
## 版本信息 (version info)

* DDNS Version: win版本
* OS Version： win10
* Type(运行方式): Binary/Python2/Python3
* related issues (相关问题): 

有两台机器，正常工作了2年了，最近发现连接不上了，好像是获取不到公网ip了，还希望大大更新一下，谢谢

**Comment by laozhoubuluo** [comment]
当前这个问题在主分支上修复了，不过还没发版。
在当前最新版本上按照以下代码修改 config.json 配置文件即可解决：

```
{
...
  "index4": "url:https://myip4.ipip.net/",
  "index6": "url:https://myip6.ipip.net/",
...
}
```
dup #366

**Comment by betakernel** [comment]
G:\myfile\DDNS>ddns.exe
. Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: underlying buffer has been detached
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: underlying buffer has been detached


请问2.12.0  可否放一个二进制版 么？谢谢

**Comment by betakernel** [comment]
python跑的话这样

{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "dnspod",
  "id": "12345",
  "index4": "default",
  "index6": "default",
  "ipv4": [ ],
  "ipv6": [
    "url:https://abc.abcde.cn/"
  ],
  "proxy": null,
  "token": "xxxxxxxx",
  "ttl": null
}

G:\myfile\DDNS\clone>python run.py
2022-12-17 17:05:34,896 <cache.load> 48@G:\myfile\DDNS\clone\util\cache.py
[DEBUG] load cache data from D:\TEMP\ddns.cache
2022-12-17 17:05:34,898 <run.main> 146@G:\myfile\DDNS\clone\run.py
[WARNING] Cache file is out of dated.
2022-12-17 17:05:34,899 <dnspod.update_record> 153@G:\myfile\DDNS\clone\dns\dnspod.py
[INFO] >>>>>url:https://abc.abcde.cn/(AAAA)
2022-12-17 17:05:34,900 <dnspod.request> 48@G:\myfile\DDNS\clone\dns\dnspod.py
[INFO] dnsapi.cn/Domain.Info : {'domain': 'abcde.cn/', 'login_token': '***', 'format': 'json'}
2022-12-17 17:05:35,099 <dnspod.request> 70@G:\myfile\DDNS\clone\dns\dnspod.py
[DEBUG] Domain.Info : result:{'status': {'code': '8', 'message': '域名不正确，请输入主域名，如 dnspod.cn', 'created_at': '2022-12-17 17:05:34'}}
2022-12-17 17:05:35,100 <dnspod.request> 48@G:\myfile\DDNS\clone\dns\dnspod.py
[INFO] dnsapi.cn/Domain.Info : {'domain': 'url:https://abc.abcde.cn/', 'login_token': '***', 'format': 'json'}
2022-12-17 17:05:35,296 <dnspod.request> 70@G:\myfile\DDNS\clone\dns\dnspod.py
[DEBUG] Domain.Info : result:{'status': {'code': '8', 'message': '域名不正确，请输入主域名，如 dnspod.cn', 'created_at': '2022-12-17 17:05:34'}}
2022-12-17 17:05:35,297 <dnspod.get_domain_info> 93@G:\myfile\DDNS\clone\dns\dnspod.py
[INFO] domain_id: None, sub: None
2022-12-17 17:05:35,297 <run.change_dns_record> 81@G:\myfile\DDNS\clone\run.py
[ERROR] invalid domain: [ url:https://abc.abcde.cn/ ]
2022-12-17 17:05:35,298 <cache.sync> 85@G:\myfile\DDNS\clone\util\cache.py
[DEBUG] save cache data to D:\TEMP\ddns.cache
DDNS[ ${BUILD_VERSION}@${BUILD_DATE} ] run: nt win32
Configuration was loaded from <== G:\myfile\DDNS\clone\config.json
========================= Sat Dec 17 17:05:34 2022 =========================

Sat Dec 17 17:05:34 2022 url:https://abc.abcde.cn/(AAAA) ==> xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx [via DIRECT]

**Comment by NewFuture** [comment]
配置不对
```json
"ipv6": [
"abc.abcde.cn"
],
```

**Comment by betakernel** [comment]
> 

{
"$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
"debug": true,
"dns": "dnspod",
"id": "12345",
"index4": "default",
"index6": "default",
"ipv4": [ ],
"ipv6": [
"url:https://abc.abcde.cn/"
],
"proxy": null,
"token": "xxxxxxxx",
"ttl": null
}
上面的  就报那个错



{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "dnspod",
  "id": "12345",
  "index4": "default",
  "index6": "default",
  "ipv4": [ ],
  "ipv6": [
    "abc.abcde.cn"
  ],
  "proxy": null,
  "token": "12345",
  "ttl": null
}
这样写就不报那个错

**Comment by NewFuture** [comment]
`ipv4` `ipv6` 填域名 @betakernel

**Comment by Dingx-t** [comment]
同样的问题，index4 采用public无法获取正确的ip。
系统：win10；版本：2.11.5；运行过程中会报错：warning：root:cache file is out of dated.
已采用输入url的方式正常使用。
