### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by OpticalEngineering** [NewFuture/DDNS#380]
## 描述场景和问题 (Is your feature request related to a problem? Please describe)
获取设备ipv4/ipv6公网地址的公网ip查询服务api一旦出现故障，只能等待热修。ipv4/ipv6的地址的获取方式每次都需要请求公网ip查询服务api，是否可以减少请求的频次，避免对服务api造成压力，更避免对方关闭服务

## 解决方案或者思路 (Describe the solution you'd like)
 
1. 将公网ip查询服务api设置在配置文件中，出现问题可以自行修改可用api
2. 将本地缓存中的ipv4/ipv6地址，与查询的设备所有网卡信息做匹配，判断是否包含该ip地址信息。如果不包含则请求公网ip查询服务api获取

**Comment by laozhoubuluo** [comment]
1. 参考以下配置即可，具体的 URL 可以找第三方或者自建，不是必须等待热修。
```
{
...
  "index4": "url:https://myip4.ipip.net/",
  "index6": "url:https://myip6.ipip.net/",
...
}
```
2. 如果您的路由器直接能拿到地址，可以使用默认获取方式。URL 一般是给下游设备运行 DDNS 的时候（例如需要 IPv6 地址或者路由器不支持第三方应用加载）而导致设备只能看到内网地址的时候用的。
