### ISSUE TITLE
win10定时任务无法更新ipv6地址[debug]

### ISSUE THREAD

**Issue by litaying** [NewFuture/DDNS#381]
## **描述问题 (Describe the bug)**

在两台电脑上测试使用win版本的二进制文件，修改配置文件后可以手动更新dnspod ipv6地址，但是定时任务按照教程用管理员权限创建后发现确实定时执行了，但是ipv6地址并没有更新，不知道什么原因。

## 版本信息 (version info)

* DDNS Version: 
* OS Version： 
* Type(运行方式): Binary/Python2/Python3
* related issues (相关问题): 

### 配置文件 (config file)

```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json", 
  "debug": false, 
  "dns": "dnspod", 
  "id": "3-----8", 
  "index4": "default", 
  "index6": "1", 
  "ipv6": [
    "s.t-----ng.site"
  ], 
```

**Comment by litaying** [comment]
> log 输出的啥？

run.log吗？都是
**_s.t---g.site(AAAA) ==> 240-----:342 [via DIRECT]
. . . . . . . . . . . . . ._** 
格式的日志。

**Comment by litaying** [comment]
> log 输出的啥？

**Comment by litaying** [comment]
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json", 
  "debug": false, 
  "dns": "dnspod", 
  "id": "332068", 
  "index4": "default", 
  "index6": "1", 
  "ipv6": [
    "s.t*g.site"
  ], 
  "proxy": null, 
  "token": "****************", 
  "ttl": null
}

**Comment by litaying** [comment]
使用的软件版本是[v2.11.5](https://github.com/NewFuture/DDNS/releases/tag/v2.11.5)
Windows10 21H2 19044.2364

**Comment by NewFuture** [comment]
看log ipv6地址更新成了 `240-----:342`
之后获取到的ip没有变就跳过了

**Comment by litaying** [comment]
> 

如果我手动删除run.log或者删除了其中内容会影响到IP地址的更新吗？是只检测本地ip的变更，只有变更了才会更新还是说他会实时获取域名的ip进行对比？
我尝试过在配置文件修改获取不同网卡，但不手动执行，等待五分钟后，定时任务是更新地址的。
我想要重新获取ipv6验证 但是百度用_ipconfig /release6 ipconfig /renew6_指令去手动更新ipv6地址报错，“在续订接口 以太网 时出错: 信号灯超时时间已到”。
在正确设置后不去处理过一段时间发现无法从域名访问，最后对比发现ipv6的地址没有更新。所以说我认为是本机ipv6地址变了了，但是没有更新。
因为ipv6地址不知道怎么手动更新，所以我测试比较麻烦，但是每次正常设置好，手动更新后，隔一阵子无法访问，发现ipv6地址没更新。

**Comment by litaying** [comment]
> 看log ipv6地址更新成了 `240-----:342` 之后获取到的ip没有变就跳过了

如果我手动删除run.log或者删除了其中内容会影响到IP地址的更新吗？是只检测本地ip的变更，只有变更了才会更新还是说他会实时获取域名的ip进行对比？
我尝试过在配置文件修改获取不同网卡，但不手动执行，等待五分钟后，定时任务是更新地址的。
我想要重新获取ipv6验证 但是百度用_ipconfig /release6 ipconfig /renew6_指令去手动更新ipv6地址报错，“在续订接口 以太网 时出错: 信号灯超时时间已到”。
在正确设置后不去处理过一段时间发现无法从域名访问，最后对比发现ipv6的地址没有更新。所以说我认为是本机ipv6地址变了了，但是没有更新。
因为ipv6地址不知道怎么手动更新，所以我测试比较麻烦，但是每次正常设置好，手动更新后，隔一阵子无法访问，发现ipv6地址没更新。

**Comment by NewFuture** [comment]
配置文件改了，缓存就失效了，
或者把cache 设置成 false 就不会缓存ip
