### ISSUE TITLE
Mac怎么设置成服务或者定时任务呀？

### ISSUE THREAD

**Issue by mattholy** [NewFuture/DDNS#384]
才用macos不久，发现mac是没有systemctl的，那么要怎么才能把这个注册成服务之类的，满足开机启动并且比如每5分钟刷新一次？

**Comment by ghostLiulang** [comment]
mac 上应该可以使用cron来管理配置定时任务的. 我在网上找了个教程也许你可帮助你.
`https://blog.csdn.net/weixin_41613094/article/details/121995535`

**Comment by mattholy** [comment]
thx
