### ISSUE TITLE
cloudflare 更新问题

### ISSUE THREAD

**Issue by gkl1368** [NewFuture/DDNS#39]
cloudflare更新时 会增加一条A记录 而不是修改原先A记录的值。暂时替换成旧版的cloudflare.py, 无问题

**Comment by NewFuture** [comment]
是 #38 引入的？

**Comment by gkl1368** [comment]
反正最新版不行 恢复上个版本就ok了

**Comment by gkl1368** [comment]
貌似是的

**Comment by NewFuture** [comment]
@gkl1368  应该修复了

**Comment by chendeben** [comment]
这个bug处理了吗？我目前更新ipv6的时候，还是一直提示
『{"success":false,"errors":[{"code":81057,"message":"The record already exists."}],"messages":[],"result":null}』

**Comment by NewFuture** [comment]
@chendeben 最新版？

**Comment by chendeben** [comment]
> @chendeben 最新版？

早上clone下来的，ipv4正常，ipv6一直提示记录已存在。

**Comment by NewFuture** [comment]
把debug打开看一下，还有问题再开一个 issue吧
