### ISSUE TITLE
[debug]

### ISSUE THREAD

**Issue by Capsule7446** [NewFuture/DDNS#397]
## **描述问题 (Describe the bug)**

1. 绑定的都是我本机的ip，就是内网ip。
2. ipv6都没有绑定成功。【昨天是成功绑定】

## 版本信息 (version info)

* DDNS Version:  Docker  image Latest =>2.13.3
* OS Version： windows
* Type(运行方式): Docker
* related issues (相关问题): 

## **复现步骤 (To Reproduce)**

···
docker run -d -v $PWD/config.json:/config.json --network host  newfuture/ddns
···
### 配置文件 (config file)

```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": false,
  "dns": "cloudflare",
  "index4": "url:https://ip.3322.net/",
  "index6": "url:http://ip.sb",
  "ipv4": [
    "xxxx.org"
  ],
  "ipv6": [
    "xxxx.org"
  ],
  "token": "jwsLg--XXXXXXXXX"
}
```

### 调试输出 (debug output)

···sh
WARNING:root:Cache file is out of dated.
ERROR:root:'NoneType' object has no attribute 'group'
ERROR:root:Fail to get ipv6 address!

Mon May  8 03:45:01 2023 xxx.org(A) ==> x.x.x.x [via DIRECT]
Mon May  8 03:45:03 2023 xxx.xxx.org(A) ==> x.x.x.x [via DIRECT]
Mon May  8 03:45:05 2023 xxx.xxx.org(A) ==> x.x.x.x [via DIRECT]
···

## 补充说明 (Additional context)

index4 & index6 的两个url我都是打得开的。
但是code还是报无法获取

**Comment by NewFuture** [comment]
`url:http://api-ipv6.ip.sb/ip` 这个试试

**Comment by PaulLaiA** [comment]
> `url:http://api-ipv6.ip.sb/ip` 这个试试

我并没有更改任意选项，我将我的路由器重启，并将网线重新插入。我就可以获取到IPV6。

因为我在路由器那边查看到我并没有被分配到IPV6。

非常感谢这个回复，同时我将相同的config搬到了我的linux主机上并用同样的docker-compose启动。

这次也是失败的。然后报错的显示和我的在windows之前的是一致的。

**Comment by char-46** [comment]
> `url:http://api-ipv6.ip.sb/ip` 这个试试

`ip.sb`的api现在要求使用`Mozilla/5.0`的UA……

**Comment by NewFuture** [comment]
updated
