### ISSUE TITLE
配置获取IP的网卡

### ISSUE THREAD

**Issue by coldeve** [NewFuture/DDNS#4]
![image](https://cloud.githubusercontent.com/assets/24355466/26672456/d630d990-46eb-11e7-9b2d-719b1094d10d.png)
我这是不是少了环境？

**Comment by coldeve** [comment]
貌似是文件格式的问题，怎样修改？

**Comment by NewFuture** [comment]
贴一下配置，（注意打码  😸 ）

**Comment by coldeve** [comment]
额，是config.json吗
![image](https://cloud.githubusercontent.com/assets/24355466/26682647/ce355c5c-4713-11e7-98d3-01dc41841f5b.png)

**Comment by coldeve** [comment]
![image](https://cloud.githubusercontent.com/assets/24355466/26683319/f8388a2c-4715-11e7-85e7-341265936e33.png)
我尝试用 Python3（也就是我python的版本启动时的界面）

**Comment by NewFuture** [comment]
好的，我测试一下

**Comment by NewFuture** [comment]
@coldeve  index4设置成`3`(数字)

**Comment by NewFuture** [comment]
更新了一下，这一版兼容了

**Comment by coldeve** [comment]
我大概明白你的意思了，我将其换成了
"index4": "public",
但是如果换成
"index4": 3,
又出现另一个错误
![image](https://cloud.githubusercontent.com/assets/24355466/26686603/0e01cbe8-4720-11e7-8507-ba07e44fa014.png)

**Comment by coldeve** [comment]
抱歉，我忘了Linux是从0开始计数网卡的

**Comment by NewFuture** [comment]
参数说明 https://github.com/NewFuture/DDNS#index4和index6参数说明

> 但是如果换成
> "index4": 3,

是第四块网卡

**Comment by NewFuture** [comment]
哈，网卡挺多的

**Comment by coldeve** [comment]
对了，现在dnspod开始整合进腾讯云了，我问过腾讯云之前获得dnspod的token是否继续能用，他没回答我，反而建议我用腾讯云的api，所以我不知道现在我不能用token登是不是因为要换腾讯云的了

**Comment by coldeve** [comment]
我是用做学校内网ipv6和ipv4中转服务器。。。(●'◡'●)

**Comment by NewFuture** [comment]
现在两个是并存的，DNSPOD的这个目前一直能用的

哈可以的 😄

**Comment by coldeve** [comment]
嗯，是的，
@后来者
pppoe登陆获得的ppp0网卡是第0号位
"index4": 0,
还有，dnspod获得token不能用就删掉继续获取，目前还能用
还有用ie或者其他浏览器进不了dnspod登陆界面的用chrome就行了，实在不行挂VPN进国外的dnspod登陆后不退出进国内dnspod网站目前还可行
最后谢谢GitHub这个项目的项目组啦，快12点了，明天我再测试最新的，谢谢啦
