### ISSUE TITLE
Docker支持

### ISSUE THREAD

**Issue by zuosc** [NewFuture/DDNS#40]
尝试为这个项目添加docker支持。

这是粗略的Dockerfile
```
FROM python:3.7-alpine

ENV LIBRARY_PATH=/lib:/usr/lib

WORKDIR /app

RUN echo https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.8/main > /etc/apk/repositories; \
    echo https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.8/community >> /etc/apk/repositories

RUN apk add --no-cache git && \
    git clone https://github.com/NewFuture/DDNS /app

ENTRYPOINT git pull && \
    python ./run.py -c /etc/ddns/config.json
```
使用的时候，只要把配置文件映射到容器的 /etc/ddns/即可。

但是发现这个只能执行一次，遂尝试运行tash.sh  ,似乎只要把ENTRYPOINT改为    ./task.sh即可。

但是发现/task.sh里使用配置文件路径是程序的运行路径。所以如果要映射的话，就要映射整个app文件夹。  感觉不够优雅。

**Comment by NewFuture** [comment]
task.sh 只是把定时任务写入 corn.d/ddns （文件路径根据用户的情况确定的）
https://github.com/NewFuture/DDNS/blob/master/task.sh#L6

docker的话文件路径都已经确定了，
可以直接先把corntab 的命令写好，默认先关闭这个任务
运行task的时候启动这个任务就行了

**Comment by NewFuture** [comment]
docker 的话可以把体积做得更小(大概10M左右)

可以尝试先把 py编译成alpine上运行得二进制的，
然后基于将二进制打包到一个裸得alpine(无python环境)

ps: 没试过编译alpine版得二进制

**Comment by zuosc** [comment]
我这边尝试了一下，这个Dockerfile运行起来没问题。
你觉得如何？

```
FROM python:3.7-alpine


ENV LIBRARY_PATH=/lib:/usr/lib

WORKDIR /app

RUN echo https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.8/main > /etc/apk/repositories; \
    echo https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.8/community >> /etc/apk/repositories

RUN echo "*/5 * * * *   root   python /app/run.py -c /etc/ddns/config.json >> /var/log/ddns.log " > /var/spool/cron/crontabs/root;

RUN apk add --no-cache git && \
    git clone https://github.com/NewFuture/DDNS /app

ENTRYPOINT  python ./run.py -c /etc/ddns/config.json >> /var/log/ddns.log && crond &&  tail -f /var/log/ddns.log 
```

**Comment by zuosc** [comment]
这里有安装git和git clone过程，我觉得也可以直接copy  这样就更小了。

或者按你说的，直接编译alpine版得二进制（ps:这个我就不懂了）。

**Comment by NewFuture** [comment]
项目里面是用pyinstaller 打包的 https://github.com/NewFuture/DDNS/blob/master/build.cmd
这个在 alpine打包不能直接用

有人做了一个alpine版本的 https://github.com/six8/pyinstaller-alpine

合并到一起大概是这样的
```
docker run --rm \
    -v "${PWD}:/ddns" \
    six8/pyinstaller-alpine \
    --onefile --nowindow --noconfirm --clean --hidden-import=dns.dnspod --hidden-import=dns.alidns --hidden-import=dns.dnspod_com --hidden-import=dns.dnscom --hidden-import=dns.cloudflare --name ddns run.py
```

**Comment by zuosc** [comment]
搞搞搞  大佬搞起来

**Comment by zuosc** [comment]
顺便  我刚刚用了一会。  发现缓存时间是不是太长了？

第一次成功修改之后，等了好久。都一直在load cache
```
2019-02-12 06:19:29,640 <cache.sync> 83@/app/util/cache.py 
[DEBUG] save cache data to /tmp/ddns.cache
..............
2019-02-12 06:33:40,561 <cache.load> 46@/app/util/cache.py 
[DEBUG] load cache data from /tmp/ddns.cache

```

这个缓存时间是怎么设定的?  根据TTL？

**Comment by NewFuture** [comment]
> 这个缓存时间是怎么设定的? 根据TTL？

只要配置文件没有发生变化，缓存是一直有效的。

这个缓存是用来记录上次修改的内容，
如果这次和上次一样就不会发送更新的请求了

**Comment by zuosc** [comment]
> > 这个缓存时间是怎么设定的? 根据TTL？
> 
> 只要配置文件没有发生变化，缓存是一直有效的。
> 
> 这个缓存是用来记录上次修改的内容，
> 如果这次和上次一样就不会发送更新的请求了

哦哦哦  明白了！     是我的使用方式不对。
我直接改了DNSPOD，然后等这边刷新。  因为这边判定没变，所以不修改。  傻了~
