### ISSUE TITLE
Windows下监听ip变化的一个设想

### ISSUE THREAD

**Issue by lazzzy18** [NewFuture/DDNS#41]
windows 下有个函数 

[NotifyIpInterfaceChange](https://docs.microsoft.com/en-us/windows/desktop/api/netioapi/nf-netioapi-notifyipinterfacechange)

使用这个函数可以监听到ip的变化(Windows Vista 及 Windows Server 2008 之后的版本)，我看作者实现监听ip变化的原理是5分钟循环检测。可不可以在5分钟循环的基础上再加上使用这个API。这样的话会更加及时的检测到ip的变化。

**Comment by NewFuture** [comment]
嗯 系统调用是效率和实时性最高的
但是不一定合适

1. 不能满足所有场景，比如外网IP(路由器/网关的出口IP)
2. DNS的更新是非实时的，实际上做不到实时更新
3. 这个API好像不是 跨平台，python 原生接口还想没有找到相关API


源码可以根据需要随意修改使用 😄
