### ISSUE TITLE
固定IP应该怎么写？

### ISSUE THREAD

**Issue by once375ml** [NewFuture/DDNS#410]
"index4": "100.103.172.20",
"index6": "fd7a:115c:a1e0:ab12:4843:cd96:6267:ac14",
或者
"index4": "regex:100\\.103\\.172\\.20",
"index6": "regex:fd7a\\:115c\\:a1e0\\:ab12\\:4843\\:cd96\\:6267\\:ac14",

debug都显示：
2023-10-23 12:50:01,936 <run.update_ip> 99@run.py
[ERROR] Fail to get ipv4 address!
2023-10-23 12:50:01,966 <run.update_ip> 99@run.py
[ERROR] Fail to get ipv6 address!

**Comment by IIIlllIIllIIIll** [comment]
```json
"index4": ["shell:echo 100.103.172.20"]
```

**Comment by once375ml** [comment]
> ```json
> "index4": "shell:echo 100.103.172.20"
> ```

Windows平台就是"index4": "cmd:echo 100.103.172.20"  ？

**Comment by once375ml** [comment]
> ```json
> "index4": "shell:echo 100.103.172.20"
> ```

已经生效了，谢谢帮助！

**Comment by NewFuture** [comment]
什么场景会有正需求？
固定直接在DNS server上配好了不久行了😂

**Comment by once375ml** [comment]
> 什么场景会有正需求？ 固定直接在DNS server上配好了不就行了😂

脑抽了，记得CNAME时，一个域名下既显示IPv4，又显示IPv6，怎么自己设置就只能设置A记录，或者只能AAA记录呢。
于是就想到了这个软件，让它来Hack，等它Hack完了才发现，哦，原来是每个域名分别设置一个A记录，一个AAA记录啊……

**Comment by NewFuture** [comment]
😸
