### ISSUE TITLE
[debug]Cache is empty  我用pmon2 启动python编译后的二进制，然后显示这个。正常嘛

### ISSUE THREAD

**Issue by dragononly** [NewFuture/DDNS#427]
## 版本信息 (version info)

* DDNS Version: last
* OS Version： linux
* Type(运行方式): Binary/Python2/Python3 python 3.9
* related issues (相关问题): Cache is empty 

## **复现步骤 (To Reproduce)**
pmon2 启动编译后的python

**Comment by xiongyu258** [comment]
ME TOO，因为不会python，网上教程自学打包exe，发现报错也是这个

**Comment by NewFuture** [comment]
没有缓存，正常的
