### ISSUE TITLE
[debug] cloudflare如果配置的域名包含大写 cloudflare则不会删除旧的ip 而是直接新增一个相同子域名

### ISSUE THREAD

**Issue by LOVE2CMOL** [NewFuture/DDNS#431]
## 版本信息 (version info)

* DDNS Version: v3.0.0@2024-03-01T11:59:30+00:00
* OS Version： Linux version 5.14.0-284.30.1.el9_2.x86_64 (mockbuild@iad1-prod-build001.bld.equ.rockylinux.org) (gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4), GNU ld version 2.35.2-37.el9) #1 SMP PREEMPT_DYNAMIC Sat Sep 16 09:55:41 UTC 2023
* Type(运行方式): Python3

## **复现步骤 (To Reproduce)**
设置一个包含大小写的域名即可
![image](https://github.com/NewFuture/DDNS/assets/28857775/205b8f06-fcdf-4cac-9aff-cd74b82b4682)

## 补充说明 (Additional context)
我估计是代码中没有做大小写匹配 导致的问题

**Comment by NewFuture** [comment]
统一小写处理，可以fix这个bug
