### ISSUE TITLE
一直显示内网IP

### ISSUE THREAD

**Issue by zx19lucky** [NewFuture/DDNS#443]
大佬帮我看看，我的环境是unraid。
![image](https://github.com/NewFuture/DDNS/assets/174412735/771d1983-e757-465b-b242-59db8e48a6c6)

**Comment by zx19lucky** [comment]
修改了 public，url 网卡序号都是一个内网ip，估计是我自己的问题了。

**Comment by NewFuture** [comment]
变量名`DDNS_INDEX4`?
