### ISSUE TITLE
[debug]Docker中使用，报错

### ISSUE THREAD

**Issue by BI4KIA** [NewFuture/DDNS#445]
## **描述问题 (Describe the bug)**
docker容器中使用环境变量模式，报错。反馈。

## 版本信息 (version info)

* DDNS Version: 3.0.2
* OS Version： RouterOs container

### 调试输出 (debug output)

```sh
粘贴输出日志
/entrypoint.sh: exec: line 12: illegal option -e

## 补充说明 (Additional context)
<!-- Add any other context about the problem here. -->

**Comment by NN708** [comment]
您好，请您最好给出完整的命令。猜测您将 `-e` 参数写在了 `newfuture/ddns` 之后，而按 Docker 命令的规范应当写在其之前。

**Comment by BI4KIA** [comment]
> 您好，请您最好给出完整的命令。猜测您将 `-e` 参数写在了 `newfuture/ddns` 之后，而按 Docker 命令的规范应当写在其之前。

感谢您的指点，受制于RouterOS系统的限制， `-e `参数貌似无法使用命令行的形式在`newfuture/ddns` 之前设置，目前我已改为config.json文件的方式配置成功。但手动使用 `/ddns -c config.json`命令更新时会提示，`WARNING:root:Cache file is out of dated.`目前不影响ip的更新，但是否会影响判断更新的时间？

**Comment by NN708** [comment]
不影响，更新默认是固定 5 分钟一次。

**Comment by BI4KIA** [comment]
> 不影响，更新默认是固定 5 分钟一次。

我重新修改了entrypoint.sh文件，更新时间调整为2分钟，因为我发现在容器随系统开机时，等待5分钟首次更新ip，时间是有点长🤣。

**Comment by BI4KIA** [comment]
另外，ipv6获取到的是容器的地址，对使用来说并没有意义。能否有命令可以修改'240:?'的子网段，按照EUI64标准改为上级网关地址。

**Comment by NN708** [comment]
添加 `--network host`。

**Comment by BI4KIA** [comment]
> 添加 `--network host`。

该命令可能对RouterOS系统来说不起作用，最后通过‘ "index6": "shell:traceroute -6 -n -m 1 2400:3200::1 | egrep -o '24.*:.*:[a-z0-9]{3,4}:[a-z0-9]{3,4}'" ’这个奔办法解决了。
