### ISSUE TITLE
cloudflare 双栈域名解析提示:The record already exists

### ISSUE THREAD

**Issue by chendeben** [NewFuture/DDNS#48]
ipv4更新正常，ipv6无法更新，提示记录已存在

日志：

```
Cache is disabled!

myhome.97admin.com(A) ==> 117.30.233.225 [via DIRECT]
2019-03-26 12:11:35,481 <cloudflare.update_record> 113@/root/DDNS/dns/cloudflare.py
[DEBUG] >>>>>myhome.97admin.com(A)
2019-03-26 12:11:35,481 <cloudflare.request> 36@/root/DDNS/dns/cloudflare.py
[DEBUG] $s  : params:{'per_page': 50}
2019-03-26 12:11:40,498 <cloudflare.request> 36@/root/DDNS/dns/cloudflare.py
[DEBUG] $s /89a0fe0d09762c557fd0c7799efb1c9a/dns_records : params:{'per_page': 100, 'type': 'A', 'name': u'myhome.97admin.com'}

www.meitu.live(A) ==> 117.30.233.225 [via DIRECT]
2019-03-26 12:11:43,814 <cloudflare.update_record> 113@/root/DDNS/dns/cloudflare.py
[DEBUG] >>>>>www.meitu.live(A)
2019-03-26 12:11:43,814 <cloudflare.request> 36@/root/DDNS/dns/cloudflare.py
[DEBUG] $s  : params:{'per_page': 50}
2019-03-26 12:11:45,156 <cloudflare.request> 36@/root/DDNS/dns/cloudflare.py
[DEBUG] $s /0fe2194dc96703f47b271b7ca7051110/dns_records : params:{'per_page': 100, 'type': 'A', 'name': u'www.meitu.live'}

ipv6.97admin.com(AAAA) ==> 240e:d2:3d15:b500:9e8e:99ff:fe14:a164 [via DIRECT]
2019-03-26 12:11:51,161 <cloudflare.update_record> 113@/root/DDNS/dns/cloudflare.py
[DEBUG] >>>>>ipv6.97admin.com(AAAA)
2019-03-26 12:11:51,161 <cloudflare.request> 36@/root/DDNS/dns/cloudflare.py
[DEBUG] $s  : params:{'per_page': 50}
2019-03-26 12:11:55,820 <cloudflare.request> 36@/root/DDNS/dns/cloudflare.py
[DEBUG] $s /89a0fe0d09762c557fd0c7799efb1c9a/dns_records : params:{'content': u'240e:d2:3d15:b500:9e8e:99ff:fe14:a164', 'proxied': False, 'type': 'AAAA', 'name': u'ipv6.97admin.com', 'ttl': 600}
{"success":false,"errors":[{"code":81057,"message":"The record already exists."}],"messages":[],"result":null}
```

**Comment by NewFuture** [comment]
1. 换一个新的子域名有问题么？排除单个域名的问题
2. 可能是获取域名列表返回空的

https://github.com/NewFuture/DDNS/blob/f4a1766e0a96e93b88f40f3a7d07f656cf58b83e/dns/cloudflare.py#L118

@chendeben  方便的话可以打出来看看

我这没有 cloudflare 这个测不了

**Comment by liucedl** [comment]
好像是获取域名状态有问题，无论如何，总是要创建该域名的记录。
如果该域名不存在或者ipv6地址发生变更了，就会新建一个。如果ipv6地址没有变化，则创建失败，显示"The record already exists."

**Comment by NewFuture** [comment]
应该这个地方的缓存策略有问题 (cloudflare 的 api 这里用了过滤条件)
https://github.com/NewFuture/DDNS/blob/f4a1766e0a96e93b88f40f3a7d07f656cf58b83e/dns/cloudflare.py#L91-L97


前面查询ipv4的时候缓存了结果，(缓存key是`zoneid`)
后面查询ipv6的时候直接用了，但是里面没有对应的内容(condition不一样)

这里把condition序列化作为key的一部分应该可以解决这个问题

@liucedl 方便的话可以帮忙改一下

**Comment by NewFuture** [comment]
@tongyifan  有空可以帮忙看看一下，应该是这个问题

**Comment by chendeben** [comment]
> @tongyifan 有空可以帮忙看看一下，应该是这个问题

{u'11608ce51310ffc330d1d84d388aad97': {u'name': u'ipv6.97admin.com', u'proxied': False, u'content': u'2400:8902::f03c:91ff:fecc:1c31', u'ttl': 1, u'type': u'AAAA', u'id': u'11608ce51310ffc330d1d84d388aad97'}, u'ac2cd56f6e66dd2ed6b8a7425a457b3d': {u'name': u'ipv6.97admin.com', u'proxied': False, u'content': u'240e:d2:3d37:4f00:9e8e:99ff:fe14:a164', u'ttl': 600, u'type': u'AAAA', u'id': u'ac2cd56f6e66dd2ed6b8a7425a457b3d'}, u'f82e2dae78d6b6149bc75aa166157a76': {u'name': u'ipv6.97admin.com', u'proxied': False, u'content': u'240e:d2:3d36:8f00:9e8e:99ff:fe14:a164', u'ttl': 600, u'type': u'AAAA', u'id': u'f82e2dae78d6b6149bc75aa166157a76'}}

**Comment by chendeben** [comment]
> @tongyifan 有空可以帮忙看看一下，应该是这个问题

感觉是cloudflare允许存在多条不同ipv6的AAAA记录导致的

**Comment by NewFuture** [comment]
> 感觉是cloudflare允许存在多条不同ipv6的AAAA记录导致的

同一个域名同一个类型可以同时指定多个记录？

**Comment by wangmice** [comment]
> > 感觉是cloudflare允许存在多条不同ipv6的AAAA记录导致的
> 
> 同一个域名同一个类型可以同时指定多个记录？

我dnspod也出过这问题，同一子域名，同一类型可以有几个ip，解析的时候交替返回不同的ip（实际是解析到两个ip地址，但是程序使用的时候是交替的，比如第一次ping 返回第一个ip，第二次ping返回的第二个ip）。
