### ISSUE TITLE
运行exe程序时，出现了name ‘action ’ is not defined 的提示

### ISSUE THREAD

**Issue by jolnomedia** [NewFuture/DDNS#51]
时需要源代码运行吗
如题，配置文件如下：
`{
  "$schema": "https://ddns.newfuture.cc/schema.json",
  "debug": false,
  "dns": "alidns",
  "id": "1234Ip",
  "index4": 0,
  "index6": false,
  "ipv4": [
    "122.123jol.top"
  ],
  "ipv6": [
    
  ],
  "proxy": null,
  "token": "12345"
}`

谢谢大佬

**Comment by jolnomedia** [comment]
安装python后运行run.py，报错 global name 'action' is not defined

**Comment by NewFuture** [comment]
有空打一下Debug信息

**Comment by jolnomedia** [comment]
是这个吗，谢谢大佬，完全摸不着头脑

2019-04-03 18:25:56,288 <cache.load> 46@util\cache.py
[DEBUG] load cache data from C:\Users\ADMINI~1.PC-\AppData\Local\Temp\ddns.cache

========================= Wed Apr  3 18:25:56 2019 =========================
2019-04-03 18:25:56,310 <ip.local_v4> 39@util\ip.py
[DEBUG] [(<AddressFamily.AF_INET: 2>, 0, 0, '', ('192.168.2.101', 0)), (<Address
Family.AF_INET: 2>, 0, 0, '', ('192.168.248.1', 0)), (<AddressFamily.AF_INET: 2>
, 0, 0, '', ('192.168.163.1', 0))]

lab.nanjol.top(A) ==> 192.168.2.101 [via DIRECT]
2019-04-03 18:25:56,311 <alidns.update_record> 142@dns\alidns.py
[DEBUG] >>>>>lab.nanjol.top(A)
2019-04-03 18:25:56,311 <alidns.signature> 50@dns\alidns.py
[DEBUG] AccessKeyId=LTAIixxIFgRTA6Ip&Action=GetMainDomainName&Format=json&InputS
tring=lab.nanjol.top&SignatureMethod=HMAC-SHA1&SignatureNonce=860ab2f8-72d3-4dbc
-bdf4-e7b6c5d1d759&SignatureVersion=1.0&Timestamp=2019-04-03T10%3A25%3A56Z&Versi
on=2015-01-09
2019-04-03 18:25:56,312 <alidns.signature> 53@dns\alidns.py
[DEBUG] signString: POST&%2F&AccessKeyId%3DLTAIiQdIFgRTA6Ip%26Action%3DGetMainDo
mainName%26Format%3Djson%26InputString%3Dlab.nanjol.top%26SignatureMethod%3DHMAC
-SHA1%26SignatureNonce%3D860ab2f8-72d3-4dbc-bdf4-e7b6c5d1d759%26SignatureVersion
%3D1.0%26Timestamp%3D2019-04-03T10%253A25%253A56Z%26Version%3D2015-01-09
2019-04-03 18:25:56,312 <alidns.request> 70@dns\alidns.py
[DEBUG] params:{'Action': 'GetMainDomainName', 'InputString': 'lab.nanjol.top',
'Format': 'json', 'Version': '2015-01-09', 'AccessKeyId': 'LTxxIFgRTA6Ip', 'T
imestamp': '2019-04-03T10:25:56Z', 'SignatureMethod': 'HMAC-SHA1', 'SignatureNon
ce': UUID('860ab2f8-72d3-4dbc-bdf4-e7b6c5d1d759'), 'SignatureVersion': '1.0', 'S
ignature': b'npdElTp4fSz9KP1/Ea1z00dw0EE='}
name 'action' is not defined
2019-04-03 18:25:56,793 <cache.sync> 83@util\cache.py
[DEBUG] save cache data to C:\Users\ADMINI~1.PC-\AppData\Local\Temp\ddns.cache

**Comment by NewFuture** [comment]
https://github.com/NewFuture/DDNS/tree/NewFuture-fix-51
这个是之前修改的一个BUG，这个分支的看看

**Comment by NewFuture** [comment]
@jolnomedia 下载地址 https://github.com/NewFuture/DDNS/archive/NewFuture-fix-51.zip

**Comment by jolnomedia** [comment]
成功解决问题，谢谢大佬
