### ISSUE TITLE
macOS使用二进制文件提示SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by primovist** [NewFuture/DDNS#54]
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fa
iled: unable to get local issuer certificate (_ssl.c:1
045)

**Comment by NewFuture** [comment]
https证书验证有问题，试试
```
export PYTHONHTTPSVERIFY=0
./ddns-osx
```

**Comment by primovist** [comment]
> https证书验证有问题，试试
> ```
> export PYTHONHTTPSVERIFY=0
> ./ddns-osx
> ```
> 
> related #47 

看#47使用的是dnspod，而我使用的是aliyun，故障依旧

**Comment by NewFuture** [comment]
我确认一下这是系统配置还是python的问题

**Comment by primovist** [comment]
> 我确认一下这是系统配置还是python的问题

系统新安装的10.14.4，系统自带python 2.7.10
我回去用源码试试看。

**Comment by NewFuture** [comment]
这个和系统python的版本似乎关系不大，release出来的是python3.7编译的版本

你试试 上次python2.7编译出来的版本 
https://dev.azure.com/NewFuture-CI/2ab09aad-c4b4-4c57-ab1b-2fb92c485664/_apis/build/builds/83/artifacts?artifactName=ddns-mac-2.7&api-version=5.1-preview.5&%24format=zip

这里解释是python3.6之后对证书验证有变化
https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

**Comment by NewFuture** [comment]
源码如过也不行，在run.py加一下这个试试
```python
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by primovist** [comment]
> 源码如过也不行，在run.py加一下这个试试
> 
> ```python
> import ssl
> ssl._create_default_https_context = ssl._create_unverified_context
> ```

源码不用加这些声明就可以，但是编译之后就不可以了（2.7编译一样不行），是不是证书位置引用错误了？

**Comment by primovist** [comment]
还有个问题，如果IP地址没改变却执行了py文件，是仅提示一个 . 吗？

**Comment by NewFuture** [comment]
> 还有个问题，如果IP地址没改变却执行了py文件，是仅提示一个 . 吗？

是的，这个时候没有更新

**Comment by NewFuture** [comment]
@primovist 试试这个ssl正常么
https://dev.azure.com/NewFuture-CI/2ab09aad-c4b4-4c57-ab1b-2fb92c485664/_apis/build/builds/93/artifacts?artifactName=ddns-mac-3.7&api-version=5.1-preview.5&%24format=zip

**Comment by primovist** [comment]
> @primovist 试试这个ssl正常么
> https://dev.azure.com/NewFuture-CI/2ab09aad-c4b4-4c57-ab1b-2fb92c485664/_apis/build/builds/93/artifacts?artifactName=ddns-mac-3.7&api-version=5.1-preview.5&%24format=zip
> 

目前运行良好，提示为不需要更新的 .

**Comment by primovist** [comment]
> @primovist 试试这个ssl正常么
> https://dev.azure.com/NewFuture-CI/2ab09aad-c4b4-4c57-ab1b-2fb92c485664/_apis/build/builds/93/artifacts?artifactName=ddns-mac-3.7&api-version=5.1-preview.5&%24format=zip
> 

尝试新建域名，新编译的二进制文件运行正常！
感谢！

**Comment by NewFuture** [comment]
v2.5.8 release 了

https://github.com/NewFuture/DDNS/releases/tag/v2.5.8

**Comment by primovist** [comment]
> v2.5.8 release 了
> 
> https://github.com/NewFuture/DDNS/releases/tag/v2.5.8
> 

好的！谢谢通知！
