### ISSUE TITLE
2.5.8，windows server 2012 ssl报错

### ISSUE THREAD

**Issue by MengTS01** [NewFuture/DDNS#56]
www.xxx.net(A) ==> 11.128.18.61 [via DIRECT]
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
issuer certificate (_ssl.c:1056)

运行于Windows 2012

**Comment by primovist** [comment]
> www.xxx.net(A) ==> 11.128.18.61 [via DIRECT]
> [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local
> issuer certificate (_ssl.c:1056)
> 
> 运行于Windows 2012

参考#54

**Comment by NewFuture** [comment]
@MengTS01 试试这个最新build的

https://dev.azure.com/NewFuture-CI/2ab09aad-c4b4-4c57-ab1b-2fb92c485664/_apis/build/builds/102/artifacts?artifactName=ddns-win-3.7&api-version=5.1-preview.5&%24format=zip

**Comment by MengTS01** [comment]
> @MengTS01 试试这个最新build的
> 
> https://dev.azure.com/NewFuture-CI/2ab09aad-c4b4-4c57-ab1b-2fb92c485664/_apis/build/builds/102/artifacts?artifactName=ddns-win-3.7&api-version=5.1-preview.5&%24format=zip

试验了一下，错误一样，我使用的是编译版本，没有python环境。

**Comment by NewFuture** [comment]
@MengTS01 

这个可能和windows server默认的安全策略有关 https://github.com/geopy/geopy/issues/212#issuecomment-242774735 

用默认的IE打开 API地址,系统会自动下载证书,可能会有是否信任的提示
* 阿里云的打开 https://alidns.aliyuncs.com （400）
* DNSPod 打开https://dnsapi.cn

然后运行这个exe

如果还不行管理员权限运行试试

**Comment by MengTS01** [comment]
将https://alidns.aliyuncs.com放入到受信任的站点里面，可以了，2.5.8也可以了。

New Future <notifications@github.com> 于2019年4月28日周日 下午7:38写道：

**Comment by NewFuture** [comment]
好的
