### ISSUE TITLE
ERROR:root:[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)

### ISSUE THREAD

**Issue by ChihChieh** [NewFuture/DDNS#58]
在我的树莓派中运行出现错误:

pi.domain.com(AAAA) ==> 2408:84f0:ffc7:6c25:39dc:afc4:2c3a:bddf [via DIRECT] 
ERROR:root:[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)

配置应该是没有问题的，我在自己的win10上运行没有问题，代码搬到树莓派3b+后就不行了，查看dnspod上面ip并没有更新，

**Comment by NewFuture** [comment]
https  握手失败了，你用`wget` 或者 `curl` 连一下`https://dnsapi.cn`正常么？

**Comment by ChihChieh** [comment]
> https 握手失败了，你用`wget` 或者 `curl` 连一下`https://dnsapi.cn`正常么？

wget https://dnsapi.cn
--2019-05-20 08:09:19--  https://dnsapi.cn/
Resolving dnsapi.cn (dnsapi.cn)... 157.255.173.149
Connecting to dnsapi.cn (dnsapi.cn)|157.255.173.149|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/xml]
Saving to: ‘index.html’

index.html                     [ <=>                                    ]     190  --.-KB/s    in 0s      

2019-05-20 08:09:19 (19.4 MB/s) - ‘index.html’ saved [190]
这样子是正常吧

**Comment by haozhouxu** [comment]
也是遇到这个问题。会不会是这个原因：https://stackoverflow.com/questions/41584975/ssl-v3-handshake-failure-but-only-in-newer-versions-of-openssl

**Comment by NewFuture** [comment]
@haozhouxu 有可能

**Comment by haozhouxu** [comment]
找到一种方案：下载源代码，运行用python run.py ，注意：Python的版本为2
