### ISSUE TITLE
[windows][task] 运行源码或exe都提示系统找不到指定文件。

### ISSUE THREAD

**Issue by snakwu** [NewFuture/DDNS#64]
应该是缓存文件没找到

**Comment by NewFuture** [comment]
可以贴一下debug的log

**Comment by snakwu** [comment]
log是空白的，手动执行py和exe正常，就是win的计划任务里的执行信息显示失败，系统无法找到指定文件

**Comment by snakwu** [comment]
开启bedug，运行run.bat正常更新dns，当双击taske.bat创建定时任务运行，结果出现系统找不到指定文件，查找过没有创建tmp文件

**Comment by NewFuture** [comment]
路径是否有特殊字符？

定时任务里 `DDNS`这个任务对应的命令是？

**Comment by snakwu** [comment]
路径:D:\DDNS
![QQ图片20190621225400](https://user-images.githubusercontent.com/5343595/59931504-aadadd00-9477-11e9-97b3-5dcd7d9a7596.png)

**Comment by snakwu** [comment]
我估计是和创建定时任务的用户有关

**Comment by 5460** [comment]
我可能遇到了类似的问题，但我这里没有出现任何错误提示。
直接双击ddns.exe可以正常更新，但自己创建的计划任务就不行。
手动运行该任务，能看到进程里先出现1个ddns.exe，约1秒后出现第2个ddns.exe，再过2秒后二者一起退出。
ddns.cache文件内容为 €}q (X   ipv6q塜   ipv4q塽.

同一个任务里另一条curl操作可以正常执行。

**Comment by NewFuture** [comment]
@5460  这个配置启动没有指定配置文件,所以可能有问题
比如 `-c F:/software/net.../config.json`

**Comment by 5460** [comment]
@NewFuture 感谢指导，添加配置文件路径后，可以更新了
