### ISSUE TITLE
命中缓存能不能换个提示方式

### ISSUE THREAD

**Issue by zctmdc** [NewFuture/DDNS#65]
命中缓存能不能换个提示方式，输出一个点，意思不明确 ，希望修改为，无需更新之类的
还有就是不用缓存可以咩，去DNS上面查。
https://api.cloudflare.com/#dns-records-for-a-zone-dns-record-details

**Comment by NewFuture** [comment]
这个其实是为了方便查看日志，每5分钟一次，长时间看一次，看一下打点和更新的情况比较清楚

**Comment by aloneshepherd** [comment]
这个命中缓存对新手确实有点不太友好，看不懂，还以为出问题。。。

**Comment by qwqVictor** [comment]
这种输出其实很好，如果你写一个 shell 脚本想要判断它是否更新，如果更新再执行什么操作的时候，可以直接判断输出结果是否等于 ". " (虽然也许不加空格写脚本会更舒适) 来判断是否更新，非常简洁明了。
