### ISSUE TITLE
华芸Asustor，SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by weiyideai520** [NewFuture/DDNS#66]
我的机器是华芸的NAS，下载的是Linux的二进制文件，执行的适合报错了

ERROR:root:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)

**Comment by NewFuture** [comment]
duplicate #63
