### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 664052243** [NewFuture/DDNS#7]
Traceback (most recent call last):
  File "/home/ddns/run.py", line 91, in <module>
    main()
  File "/home/ddns/run.py", line 74, in main
    dns = getattr(__import__('dns', fromlist=[dns_provider]), dns_provider)
TypeError: Item in ``from list'' must be str, not unicode

**Comment by NewFuture** [comment]
贴一下python版本和配置文件

**Comment by kaguras** [comment]
应该是你配置文件文件的编码有问题，用utf-8编码格式保存试试




发自网易邮箱大师
在2017年09月04日 11:41，664052243 写道：

Traceback (most recent call last):
File "/home/ddns/run.py", line 91, in
main()
File "/home/ddns/run.py", line 74, in main
dns = getattr(import('dns', fromlist=[dns_provider]), dns_provider)
TypeError: Item in ``from list'' must be str, not unicode

**Comment by 664052243** [comment]
Python2.7
![image](https://user-images.githubusercontent.com/13130389/30011105-73ed3d2a-9167-11e7-98a8-ee90b1362bf7.png)

**Comment by kaguras** [comment]
把文件编码改下看看，改成UTF-8
在2017年9月4日 11:52，664052243<notifications@github.com> 写道：

Python2.7

**Comment by 664052243** [comment]
@kaguras 改过了 还是一样

**Comment by NewFuture** [comment]
OK,我测试一下

**Comment by 664052243** [comment]
@NewFuture 请问网卡是无线的支持吗？

**Comment by kaguras** [comment]
没试过，应该支持呢，我在手机上可以正常运行




在2017年9月4日 12:09，664052243<notifications@github.com> 写道：

@NewFuture 请问网卡是无线的支持吗？

**Comment by 664052243** [comment]
@kaguras 好的  多谢

**Comment by NewFuture** [comment]
@kaguras  谢谢, python 2的编码处理有点问题，修改了
@664052243  新版的试一下应该正常了，

宁外如 @kaguras  所言 和网卡属性无关

**Comment by 664052243** [comment]
@NewFuture 好的 我试试

**Comment by 664052243** [comment]
@NewFuture 解决了  多谢
