### ISSUE TITLE
CentOS7 Python3.7/2.7 CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by andy2999** [NewFuture/DDNS#71]
[root@localhost ddns]# ./ddns
inner.cdkpw.net(A) ==> 171.217.62.160 [via DIRECT]
ERROR:root:[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)
ERROR:root:<urlopen error [Errno 101] Network is unreachable>

**Comment by NewFuture** [comment]
duplicate #63
