### ISSUE TITLE
[Suggestions] Add custom method of getting IP support. 

### ISSUE THREAD

**Issue by qwqVictor** [NewFuture/DDNS#77]
ENG:
Some advanced users may want to use a more flexible method to get the IP for DDNS, like getting IP through UPnP. But the DDNS client can't integrate everything to meet users' approval. So please allow user to specify the command to get the IP, and DDNS can read it from standard output.

CHN:
一些高级用户可能想要使用更加弹性的方法来获取 DDNS 需要的 IP，比如通过 UPnP 来获取 IP。但是 DDNS 客户端不可能内建所有用户需要的方法。所以请允许用户指定获取 IP 的命令行指令，DDNS 只需从标准输出流中读取即可。

**Comment by NewFuture** [comment]
这个想法不错，可以和其它工具集成，

比如这两种方案?

* option 1 stdin

```bash
getmyip | ddns
```

* option 2 cmd
```json
{
 "index4": "/bin/getmyip4"
}
```

**Comment by qwqVictor** [comment]
I prefer "option 2".
Because not all users use cron to run DDNS client. For example,  I use systemd timer to run DDNS client periodically, and it's really hard and not elegant to use pipe in systemd service.
By the way, I suggest that the command should be run in bash, in order to support the shell syntax like pipe. For example, I can use this command to get the IPv4 via UPnP:
```bash
upnpc -s | grep -m 1 'ExternalIPAddress =' | sed -e 's/^.*ExternalIPAddress \= \([^ \\]\+\).*$/\1/'
```
Looking forward to this feature!

我更青睐第二种方案。
因为不是所有用户都使用 cron 来运行 DDNS 客户端。例如，我使用 systemd timer 来周期性地运行 DDNS 客户端，而在 systemd 服务中使用管道是比较困难并且也不优雅的。
另外，我建议将命令运行在 bash 里，这样可以支持 shell 的语法例如管道符号。例如，我可以用以下命令来通过 UPnP 获取 IPv4 地址:
```bash
upnpc -s | grep -m 1 'ExternalIPAddress =' | sed -e 's/^.*ExternalIPAddress \= \([^ \\]\+\).*$/\1/'
```
期待这个功能的加入！

**Comment by NewFuture** [comment]
这两种格式？
```
shell:shell string
```
```
cmd:cmd string
```

**Comment by qwqVictor** [comment]
我不太能理解上述两种格式的说法。我的想法是，对于以下配置文件:
```json
{
    "index4": "upnpc -s | grep -m 1 'ExternalIPAddress =' | sed -e 's/^.*ExternalIPAddress \= \([^ \\]\+\).*$/\1/'"
}
```
在获取 IPv4 的时候，DDNS 执行 `sh -c "upnpc -s | grep -m 1 'ExternalIPAddress =' | sed -e 's/^.*ExternalIPAddress \= \([^ \\]\+\).*$/\1/'"`，并读取输出的结果，以该结果作为最终获取的 IPv4。

**Comment by NewFuture** [comment]
加个前缀以避免与现有配置方式冲突

**Comment by qwqVictor** [comment]
那么就用
```json
{
    "index4": "cmd: upnpc -s | grep -m 1 'ExternalIPAddress =' | sed -e 's/^.*ExternalIPAddress \\= \\([^ \\\\]\\+\\).*$/\\1/'"
}
```
吧。

**Comment by NewFuture** [comment]
嗯，有空的时候加一下这个feature

**Comment by NewFuture** [comment]
PR #79  实现这个功能
