### ISSUE TITLE
DNPSOD根域名 (@域名) 记录判断错误

### ISSUE THREAD

**Issue by 664052243** [NewFuture/DDNS#8]
![image](https://user-images.githubusercontent.com/13130389/30015036-96380224-9181-11e7-9775-a178c37d5c37.png)

**Comment by NewFuture** [comment]
@664052243  如果不是 `@`域名有问题么？

**Comment by 664052243** [comment]
根域名更新ip的话不会更新会创建多一条解析记录  在次运行脚本的话就会出现报错
我现在暂时去掉根域名就没问题了

**Comment by NewFuture** [comment]
对DNPSOD@这个地方有个bug

**Comment by NewFuture** [comment]
@664052243  可以使用 `@.your.domain`这种方式主动声明是根域名

**Comment by 664052243** [comment]
@NewFuture 好的

**Comment by NewFuture** [comment]
现在加上了自动判断的逻辑，如果是根域名会自动加`@`，原来的配置应该也可以用

**Comment by 664052243** [comment]
好的 感谢

**Comment by NewFuture** [comment]
谢谢反馈 😃
