### ISSUE TITLE
请问一下：阿里云国际该如何处理？

### ISSUE THREAD

**Issue by syuraking** [NewFuture/DDNS#82]
这边好像是阿里云国内的API处理，不知道阿里云国际那边如何操作呢？

**Comment by NewFuture** [comment]
是的，API文档和aliyun国内的一致否?

**Comment by syuraking** [comment]
表面上看是一致的，但是好像处理的URL不一样

**Comment by NewFuture** [comment]
中文文档写的是`alidns.aliyuncs.com` (比较新)
[英文文档](https://www.alibabacloud.com/help/doc-detail/34281.htm) 写的是 `dns.aliyuncs.com`

中文的和国内版是一样的，所以这个能直接用么？

**Comment by syuraking** [comment]
Non-authoritative answer:
alidns.aliyuncs.com	canonical name = alidns.aliyuncs.com.gds.alibabadns.com.
alidns.aliyuncs.com.gds.alibabadns.com	canonical name = popunify.ap-southeast-1.aliyuncs.com.
popunify.ap-southeast-1.aliyuncs.com	canonical name = popunify.ap-southeast-1.aliyuncs.com.gds.alibabadns.com.
Name:	popunify.ap-southeast-1.aliyuncs.com.gds.alibabadns.com
Address: 47.88.198.14
-----------------------------------------
Non-authoritative answer:
dns.aliyuncs.com	canonical name = popunify-public.aliyuncs.com.
popunify-public.aliyuncs.com	canonical name = popunify-public.aliyuncs.com.gds.alibabadns.com.
Name:	popunify-public.aliyuncs.com.gds.alibabadns.com
Address: 106.11.61.112


两边解析出来的结果不一样，这样，我下月会有新服务器，到时，我直接上测试好了。

**Comment by NewFuture** [comment]
可以参照 https://github.com/NewFuture/DDNS/blob/master/dns/dnspod_com.py
加一个 `alibabacloud.py`试试，能行的话可以提个PR 😆

**Comment by syuraking** [comment]
已经测试，API方式，国内国外通用，无需要修改地址

**Comment by NewFuture** [comment]
@syuraking  谢谢
