### ISSUE TITLE
public ip 链接无法访问

### ISSUE THREAD

**Issue by snakwu** [NewFuture/DDNS#83]
========================= Sat Sep  7 12:01:09 2019 =========================
ERROR:root:<urlopen error timed out>

**Comment by snakwu** [comment]
ERROR:root: urlopen error timed out

**Comment by snakwu** [comment]
2019-09-07 17:24:20,398 <run.main> 160@./run.py
[INFO] DDNS[${BUILD_SOURCEBRANCHNAME}@${BUILD_DATE}] run: posix,linux2
2019-09-07 17:24:20,398 <cache.load> 48@/home/snakwu/DDNS/util/cache.py
[DEBUG] load cache data from /tmp/ddns.cache
2019-09-07 17:24:20,398 <cache.load> 62@/home/snakwu/DDNS/util/cache.py
[INFO] cache file not exist
========================= Sat Sep  7 17:24:20 2019 =========================
2019-09-07 17:25:20,465 <ip.public_v6> 55@/home/snakwu/DDNS/util/ip.py
[ERROR] <urlopen error timed out>

**Comment by snakwu** [comment]
2019-09-07 17:24:20,398 <run.main> 160@./run.py
[INFO] DDNS[${BUILD_SOURCEBRANCHNAME}@${BUILD_DATE}] run: posix,linux2
2019-09-07 17:24:20,398 <cache.load> 48@/home/snakwu/DDNS/util/cache.py
[DEBUG] load cache data from /tmp/ddns.cache
2019-09-07 17:24:20,398 <cache.load> 62@/home/snakwu/DDNS/util/cache.py
[INFO] cache file not exist
========================= Sat Sep  7 17:24:20 2019 =========================
2019-09-07 17:25:20,465 <ip.public_v6> 55@/home/snakwu/DDNS/util/ip.py
[ERROR]  urlopen error timed out

**Comment by NewFuture** [comment]
cloudflare连接超时，很可能是网络问题

**Comment by snakwu** [comment]
检查过，网络没有问题，我别一个伙伴，不同地区省份的，之前一直用得很好，今天同样开始不行了，个人猜测是不是cloudflare更新了什么东西！

**Comment by NewFuture** [comment]
你在那台机子上命令行访问 `https://api.cloudflare.com` 看看可用正常访问么

**Comment by snakwu** [comment]
访问正常，客户端我传不上图

**Comment by snakwu** [comment]
curl https://api.cloudflare.com
这样访问正常，出现很多数据

**Comment by snakwu** [comment]
![QQ图片20190909001732](https://user-images.githubusercontent.com/5343595/64491136-3efa5a80-d297-11e9-93ef-09080206c384.png)

**Comment by chendeben** [comment]
遇到相同问题，
`2019-09-09 10:11:34,671 <ip.public_v6> 55@/usr/lib/python2.7/site-packages/util/ip.py
[ERROR] <urlopen error timed out>`

**Comment by chendeben** [comment]
路由器上面的另外一个插件是正常更新DNS的，这台机器更新的时候，一直提示urlopen error timed out，这台机器的acme.sh也是可以正常使用的（所以访问cloudflare是没有问题的）

**Comment by chendeben** [comment]
util/ip.py这个文件，获取ipv6的时候，那个接口失效了，建议换一下，我这边测试改成"http://v6.ip.zxinc.org/getip"后正常更新

**Comment by snakwu** [comment]
谢谢你的临时解决办法,我也去试试

**Comment by snakwu** [comment]
果然,是iipv6地址获取接口问题!

**Comment by NewFuture** [comment]
似乎这个地址被墙了。有什么API推荐的作为默认值？

另外 #36 这个feature 很有必要实现一下

**Comment by snakwu** [comment]
应该不是墙,感觉是接口更换了!

**Comment by NewFuture** [comment]
tracks in #85

**Comment by NewFuture** [comment]
#90 修改了默认网址并支持自定义域名
