### ISSUE TITLE
可以支持腾讯云吗？

### ISSUE THREAD

**Issue by zhiyuan2016** [NewFuture/DDNS#84]
好像没有在里面看到支持腾讯云dns的选项，以后会支持腾讯云吗？

**Comment by zhiyuan2016** [comment]
> 这个可以有，有兴趣可以提个PR 😄

不用了，腾讯和dnspod是一家的，可以用腾讯云登录的账号登录dnspod
为这个我绕了一个大弯路🤪

**Comment by lirener** [comment]
最近DNSPOD国际强制升级为腾讯云了……我不小心中招了
config.json里面设置"dns"
dnspod_com要改成dnspod了……然后密匙要再自己申请一份

腾讯云密匙管理教程：
https://docs.dnspod.cn/account/5f2d466de8320f1a740d9ff3/
设置中心：
https://console.dnspod.cn/account/token#

DNSPOD国际登录：https://console.dnspod.com/
DNSPOD腾讯云登录：https://console.dnspod.cn/
我的邮箱是使用QQ邮箱……用过QQ登录就变成腾讯云了 目前是强制 所有设置也丢失了
劝大家没有使用的 尽力不要使用QQ登录腾讯云..
邮箱登录验证美国手机后点击进入控制台暂时可以登录
