### ISSUE TITLE
ip没变化下启动报错

### ISSUE THREAD

**Issue by 664052243** [NewFuture/DDNS#9]
Traceback (most recent call last):
  File "/home/ddns/run.py", line 91, in <module>
    main()
  File "/home/ddns/run.py", line 86, in main
    update_ip('4', cache, dns)
  File "/home/ddns/run.py", line 60, in update_ip
    print (dns.update_record(domain, value, record_type=record_type))
  File "/home/ddns/dns/dnspod.py", line 164, in update_record
    sub_domain=sub, record_type=record_type, record_line="默认", ttl=600)
  File "/home/ddns/dns/dnspod.py", line 61, in request
    raise Exception(data.get('status', {}))
Exception: {u'message': u'Domain record already exists', u'code': u'104', u'created_at': u'2017-09-04 15:13:33'}

**Comment by NewFuture** [comment]
这个可能运行后手动改了解析和本地缓存不一致造成的，你可以清掉本地缓存试试:
> 编辑一下配置文件，然后保存

**Comment by 664052243** [comment]
@NewFuture 我确实手动删除了重复的主域名 然后在跑了一下就报错了

**Comment by NewFuture** [comment]
修改配置文件之后还是会重复?

**Comment by 664052243** [comment]
@NewFuture 修改配置文件后依然会报错  主域名重复问题只是在ip改变后才会出现

**Comment by NewFuture** [comment]
是因为有多个主域名的 原因？ #8

**Comment by 664052243** [comment]
只有一个主域名

**Comment by NewFuture** [comment]
这个问题是否也是只有根域名才有?

**Comment by 664052243** [comment]
@NewFuture  这个是根域名才有的

**Comment by NewFuture** [comment]
这个应该和#8是一个问题
