### ISSUE TITLE
C:\WINDOWS\System32 目录下的config.json起到什么作用？

### ISSUE THREAD

**Issue by C0ye** [NewFuture/DDNS#91]
发现这么个文件，里面的内容看起来是一个示例config.json，我现在用的是和DDNS同目录的配置文件，这个可以删掉吗？

**Comment by NewFuture** [comment]
可以删掉

**Comment by NewFuture** [comment]
这个应该是以系统权限调用ddns(比如定时任务) 没有指定配置文件产生

**Comment by C0ye** [comment]
> 这个应该是以系统权限调用ddns(比如定时任务) 没有指定配置文件产生

好的，谢谢
