### ISSUE TITLE
阿里云DDNS报错

### ISSUE THREAD

**Issue by agcharon** [NewFuture/DDNS#93]
ERROR:root:<urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

已经在其它网络的机器上测试，报相同的错误

**Comment by NewFuture** [comment]
#92 的问题 ？ 如果是可以先指定一个域名

**Comment by zangzhuo** [comment]
请问在哪里先指定一个域名？您这个代码，在我的服务器上之前使用都没有问题，到9月3日是最后一次正常修改AAAA记录。

**Comment by agcharon** [comment]
更新，我是使用的alidns，现在已经恢复正常了，怀疑是阿里云的服务暂时出问题了

**Comment by zangzhuo** [comment]
谢谢您！问题解决了！更新以后就可以了！

**Comment by agcharon** [comment]
好的，谢谢作者！
