### ISSUE TITLE
编译版，为什么大多数情况下运行后只输出一个点。是缓存结果吗？

### ISSUE THREAD

**Issue by StarsRiver-der** [NewFuture/DDNS#99]
crontab 两分钟执行一次，结果log里面全是点？？？

**Comment by StarsRiver-der** [comment]
试了一下确实是缓存功能的一部分，只有检测到ip变化才修改解析。

这里有一个问题：两个配置文件在同一时间被执行，只有其中一个可以成功，也是缓存的锅吧。

**Comment by NewFuture** [comment]
`.` 表示缓存命中，跳过更新
#65
